import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_5_jlpt_exam'

rewrites = {
    # part_14
    "Thứ tự sắp xếp: Pref [記者は] + Chunk1 [被災地の現状を] + Chunk2 [視察し] + Chunk3 [がてら、現地の] + Chunk4 [住民に話を] + Suff [聞くことにした。]\\n- Giải thích: Danh từ chỉ đối tượng 「被災地の現状を」 bổ nghĩa cho động từ 「視察し」 (dạng liên kết Masu-form bỏ -masuの「視察する」). Ngữ pháp 「V-ます＋がてら」 biểu thị việc làm hành động này nhân tiện/đồng thời làm hành động khác. Tiếp theo, 「現地の」 (của địa phương) liên kết tự nhiên để bổ nghĩa cho danh từ 「住民」 (người dân) trong cụm 「住民に話を」 (nói chuyện với người dân). Đuôi câu kết thúc bằng cụm quyết định hành động 「聞くことにした」。": "Cấu trúc 「V-ますがてら」 diễn tả việc kết hợp làm hai việc cùng lúc (nhân tiện, tiện thể). Chủ thể 「記者は」 (nhà báo) lấy mục đích chính là 「被災地の現状を視察し」 (thị sát tình hình vùng thiên tai) đi kèm 「がてら」 (nhân tiện đó). Tiếp theo là hành động phụ 「現地の住民に話を」 (nói chuyện với người dân địa phương), dẫn tới quyết định 「聞くことにした」 (đã quyết định lắng nghe).",
    "Thứ tự sắp xếp: Pref [新しい] + Chunk1 [経済政策が] + Chunk2 [成功したの] + Chunk3 [かというと、決して] + Chunk4 [そうとは言えない] + Suff [実態がある。]\\n- Giải thích: Tính từ 「新しい」 bổ nghĩa cho 「経済政策」. Trợ từ 「が」 đi sau chủ ngữ chínhのmệnh đề phụ. Ngữ pháp 「V-た＋のかというと」 (liệu có phải là... hay không) đòi hỏi động từ thể quá khứ thân mật đi với 「の」. Phó từ phủ định 「決して」 (tuyệt đối không) thường đi kèm với thể phủ định ở phía sau, tạo mối liên kết chặt针对 với 「そうとは言えない」 (không thể nói như vậy). Danh từ 「実態」 (thực tế) đứng sau bổ nghĩa bởi mệnh đề trước nó, kết thúc bằng động từ chỉ sự tồn tại 「ある」。": "Cấu trúc 「～かというと」 (nếu hỏi là có... hay không thì) mở ra một sự phản biện. Mệnh đề giả định 「新しい経済政策が成功したのかというと」 (nếu hỏi chính sách kinh tế mới có thành công hay không). Thực tế lại phủ định điều đó bằng 「決してそうとは言えない」 (tuyệt đối không thể nói là như vậy). Kết quả phơi bày một 「実態がある」 (có một thực trạng như thế).",
    "Thứ tự sắp xếp: Pref [作家がこの] + Chunk1 [小説を執筆した] + Chunk2 [理由はなぜ] + Chunk3 [かというと、現代社会への] + Chunk4 [強い危機感が] + Suff [あったからだ。]\\n- Giải thích: Chủ từ 「作家が」 bổ nghĩa cho cụm hành động 「小説を執筆した」 (viết tiểu thuyết). 「理由はなぜ」 (lý do tại sao) đi kèm với ngữ pháp 「かというと」 tạo thành cụm từ hỏi 「なぜかというと」 (lý do là bởi vì). Cụm chỉ đối tượng 「現代社会への」 (hướng tới xã hội hiện đại) bổ nghĩa trực tiếp cho danh từ 「強い危機感」 (lòng khủng hoảng mạnh mẽ). Cuối cùng, cấu trúc giải thích nguyên nhân 「あったからだ」 (là vì đã có) hoàn thiện câu.": "Cấu trúc 「理由はなぜかというと」 (nếu hỏi lý do là tại sao thì là vì...) dùng để giải thích căn nguyên. Vấn đề đặt ra là việc 「作家がこの小説を執筆した理由はなぜかというと」 (lý do nhà văn chấp bút viết cuốn tiểu thuyết này là gì). Lời giải đáp nằm ở 「現代社会への強い危機感が」 (một cảm giác khủng hoảng sâu sắc về xã hội hiện đại), được chốt bằng 「あったからだ」 (là bởi vì đã tồn tại cảm giác đó).",
    "Thứ tự sắp xếp: Pref [漆黒の空に] + Chunk1 [激しい稲妻が] + Chunk2 [走ったか] + Chunk3 [と思うと、大地を] + Chunk4 [揺るがす轟音が] + Suff [響き渡った。]\\n- Giải thích: Cụm chỉ địa điểm 「漆黒の空に」 đi kèm với chủ ngữ 「激しい稲妻が」. Động từ 「走る」 ở thể quá khứ 「走った」 kết hợp với ngữ pháp 「かと思うと」 (vừa mới... thì ngay lập tức). 「大地を」 (trái đất/mặt đất) làm tân ngữ cho động từ 「揺るがす」 (làm rung chuyển). Động từ này bổ nghĩa cho danh từ 「轟音」 (tiếng gầm rú). Câu kết thúc bằng động từ diễn tả âm thanh vang vọng 「響き渡った」。": "Cấu trúc 「～かと思うと」 (vừa mới... thì ngay lập tức) diễn tả hai sự kiện nối tiếp chớp nhoáng. Trên nền 「漆黒の空に」 (bầu trời đen như mực), hiện tượng 「激しい稲妻が走ったかと思うと」 (tia chớp dữ dội vừa lóe lên). Ngay tắp lự, 「大地を揺るがす轟音が」 (tiếng gầm rú rung chuyển cả mặt đất) đã 「響き渡った」 (vang vọng khắp không gian).",
    "Thứ tự sắp xếp: Pref [その少女の] + Chunk1 [瞳は、] + Chunk2 [吸い込まれそう] + Chunk3 [かと思う] + Chunk4 [ほど澄み] + Suff [切っていた。]\\n- Giải thích: Cụm chủ ngữ 「その少女の瞳は」 (đôi mắtのcô gái đó). Trạng thái 「吸い込まれそう」 (như thể bị hút vào) kết hợp với 「かと思うほど」 (đến mức tưởng chừng như là). Động từ 「澄む」 (trong trẻo) chia ở dạng liên kết 「澄み」 đi với động từ bổ trợ 「切る」 (hoàn toàn/cực kỳ) tạo thành 「澄み切っていた」 (hoàn toàn trong vắt) để kết thúc câu mô tả trạng thái.": "Cấu trúc 「～かと思うほど」 (đến mức tưởng chừng như) dùng để so sánh cường điệu. Vẻ đẹp của 「その少女の瞳は」 (đôi mắt cô thiếu nữ ấy) gợi lên cảm giác 「吸い込まれそうかと思うほど」 (tưởng như sắp bị hút hồn vào đó). Cảm giác đó làm nổi bật sự trong veo tột độ 「澄み切っていた」 (đã tĩnh lặng và trong vắt).",
    "Thứ tự sắp xếp: Pref [若者が] + Chunk1 [伝統文化を] + Chunk2 [敬遠する] + Chunk3 [かと思えば、熱心に] + Chunk4 [学ぶ若者も] + Suff [増えているという。]\\n- Giải thích: Chủ ngữ 「若者が」 thực hiện hành động lánh xa 「伝統文化を敬遠する」. Ngữ pháp 「V-る＋かと思えば」 biểu thị sự tương phản (vừa mới thấy thế này thì lại có thế khác). Trạng từ 「熱心に」 (chăm chỉ/nhiệt tình) bổ nghĩa cho động từ 「学ぶ」 (học). Cụm 「学ぶ若者も」 đóng vai trò chủ ngữ mới ở vế sau, đi kèm với động từ tự động 「増えている」 (đang tăng lên) và kết thúc bằng cấu trúc truyền đạt thông tin 「という」。": "Cấu trúc 「～かと思えば」 (cứ tưởng là... nhưng hóa ra lại) đưa ra hai sự việc hoàn toàn trái ngược. Một mặt, ta thấy 「若者が伝統文化を敬遠するかと思えば」 (cứ ngỡ giới trẻ đang xa lánh văn hóa truyền thống). Mặt khác, thực tế lại là 「熱心に学ぶ若者も」 (những người trẻ nhiệt huyết theo học) đang dần 「増えているという」 (nghe nói là đang ngày một tăng lên).",
    "Thứ tự sắp xếp: Pref [彼は] + Chunk1 [静かに微笑んだ] + Chunk2 [かと思ったら、] + Chunk3 [突然激しい] + Chunk4 [怒りを見せて] + Suff [立ち上がった。]\\n- Giải thích: Chủ ngữ 「彼は」 đi với động từ thể quá khứ 「静かに微笑んだ」. Ngữ pháp 「V-た＋かと思ったら」 biểu thị một hành động xảy ra gần như đồng thời hoặc ngay sau hành động trước đầy bất ngờ. Phó từ chỉ thời gian 「突然」 bổ nghĩa cho tính từ 「激しい」 (mãnh liệt). Tính từ này bổ nghĩa cho danh từ 「怒り」 (sự tức giận). Cụm 「怒りを見せて」 (tỏ vẻ giận dữ) liên kết với động từ hành động cuối cùng 「立ち上がった」 (đứng phắt dậy).": "Cấu trúc 「～かと思ったら」 (vừa mới... thì bỗng nhiên) diễn tả sự chuyển biến thái độ đột ngột. Chủ thể 「彼は」 (anh ta) vừa có biểu hiện 「静かに微笑んだかと思ったら」 (vừa mới mỉm cười điềm tĩnh). Ngay lập tức, anh ta 「突然激しい怒りを見せて」 (đột nhiên lộ ra sự phẫn nộ dữ dội) và có hành động 「立ち上がった」 (đứng phắt dậy).",
    "Thứ tự sắp xếp: Pref [今日は] + Chunk1 [遠くに住む] + Chunk2 [祖母から] + Chunk3 [手紙が] + Chunk4 [届く] + Suff [かな。]\\n- Giải thích: Định ngữ 「遠くに住む」 (sống ở nơi xa) bổ nghĩa cho danh từ 「祖母」 (bà). Trợ từ 「から」 chỉ nguồn gốc xuất phát gửi thư. Chủ ngữのhành động nhận là 「手紙が」. Động từ tự động 「届く」 (đến/được gửi tới) đi trực tiếp trước vĩ ngữ tình thái biểu thị sự phân vân, tự hỏiのbản thân 「かな」。": "Trợ từ 「かな」 cuối câu thể hiện sự tự hỏi, mong ngóng (không biết là... có hay không). Đối tượng hướng tới là 「遠くに住む祖母から」 (từ người bà sống ở nơi xa). Câu tự hỏi xoay quanh việc 「今日は手紙が届くかな」 (hôm nay không biết liệu thư có đến nơi không nhỉ).",
    "Thứ tự sắp xếp: Pref [あの] + Chunk1 [若き日の] + Chunk2 [情熱を] + Chunk3 [取り戻す方法が] + Chunk4 [何かあれば良いの] + Suff [だがな。]\\n- Giải thích: Cụm từ 「あの若き日の」 (những ngày trẻ tuổi ấy) bổ nghĩa cho danh từ 「情熱」 (nhiệt huyết). Danh từ này là tân ngữ cho động từ 「取り戻す」 (lấy lại). Cụm 「取り戻す方法が」 (phương pháp lấy lại) làm chủ ngữ cho vế giả định 「何かあれば」 (nếu có cái gì đó). Mẫu câu ước muốn 「良いのだが」 (thì tốt biết mấy) kết hợp với trợ từ cuối câu mang sắc thái hoài niệm, cảm thán văn chương 「な」 tạo thành 「だがな」。": "Cấu trúc 「～ばいいのだがな」 (giá mà có... thì tốt biết mấy) bộc lộ sự nuối tiếc sâu sắc. Khao khát tìm lại 「あの若き日の情熱を」 (bầu nhiệt huyết của những tháng năm tuổi trẻ ấy). Khao khát đó kết tụ thành lời ước 「取り戻す方法が何かあれば」 (nếu có cách nào đó để giành lại), khép lại bằng tiếng thở dài 「良いのだがな」 (thì thật là tốt biết bao).",
    "Thứ tự sắp xếp: Pref [地震が] + Chunk1 [起きた] + Chunk2 [ときは] + Chunk3 [かならず] + Chunk4 [机の] + Suff [下に入ってください。]\\n- Giải thích: Mệnh đề phụ 「地震が起きた」 bổ nghĩa cho danh từ chỉ thời điểm 「とき」 đi kèm trợ từ 「は」 để nhấn mạnh giả thuyết. Phó từ 「かならず」 (nhất định/luôn luôn) đứng trước để nhấn mạnh tính bắt buộcのhành động sau đó. Cụm danh từ sở hữu 「机の」 bổ nghĩa cho danh từ chỉ phương hướng 「下」 (dưới gầm bàn). Kết thúc bằng cấu trúc yêu cầu lịch sự 「に入ってください」。": "Phó từ 「かならず」 (nhất định phải, tuyệt đối) mang tính mệnh lệnh an toàn. Trong tình huống khẩn cấp 「地震が起きたときは」 (khi xảy ra động đất). Lệnh đưa ra là 「かならず机の下に」 (nhất định phải chui xuống gầm bàn), chốt bằng hành động cụ thể 「入ってください」 (xin hãy chui vào).",
    "Thứ tự sắp xếp: Pref [高度な] + Chunk1 [技術が] + Chunk2 [かならずしも] + Chunk3 [人々の生活を] + Chunk4 [豊かにするとは] + Suff [限らない。]\\n- Giải thích: Tính từ 「高度な」 bổ nghĩa cho danh từ 「技術」. Phó từ phủ định một phần 「かならずしも」 luôn đi kèm với dạng phủ định ở cuối câu, ở đây là cấu trúc 「とは限らない」 (không hẳn là). Tân ngữ 「人々の生活を」 chịu sự tác độngのđộng từ biến đổi trạng thái 「豊かにする」 (làm cho phong phú). Cụm 「豊かにする」 kết hợp với trợ từ liên kết 「とは」 để dẫn vào vĩ ngữ phủ định 「限らない」。": "Cấu trúc 「かならずしも～とは限らない」 (không nhất thiết lúc nào cũng...) phủ định lại một định kiến. Mặc dù có 「高度な技術が」 (công nghệ kỹ thuật cao). Nhưng điều đó 「かならずしも人々の生活を」 (không có nghĩa là nhất định đời sống con người). Sẽ được 「豊かにするとは限らない」 (làm cho phong phú lên).",
    "Thứ tự sắp xếp: Pref [この不適切な] + Chunk1 [発言は、] + Chunk2 [隣国との] + Chunk3 [深刻な外交問題に] + Chunk4 [発展し] + Suff [かねない。]\\n- Giải thích: Chủ ngữ chính 「この不適切な発言は」 (phát ngôn không thỏa đáng này). Cụm 「隣国との」 (với nước láng giềng) bổ nghĩa cho danh từ ghép 「深刻な外交問題」 (vấn đề ngoại giao nghiêm trọng). Cụm từ chỉ hướng biến đổi kết quả đi kèm với trợ từ 「に」. Động từ 「発展する」 chia về thể liên kết Masu-form bỏ -masu là 「発展し」 để kết hợp trực tiếp với ngữ pháp chỉ nguy cơ, khả năng xấu 「かねない」 (có nguy cơ/có thể dẫn đến).": "Cấu trúc 「V-かねない」 (lo sợ rằng sẽ, e là sẽ) đưa ra cảnh báo về một rủi ro tiềm tàng. Bắt nguồn từ 「この不適切な発言は」 (phát ngôn thiếu chừng mực này). Rủi ro có thể lan rộng thành 「隣国との深刻な外交問題に」 (một cuộc khủng hoảng ngoại giao nghiêm trọng với nước láng giềng). Cảnh báo được chốt lại bằng 「発展しかねない」 (rất có khả năng sẽ tiến triển thành).",
    "Thứ tự sắp xếp: Pref [企業秘密に] + Chunk1 [関わる] + Chunk2 [重要な情報については、] + Chunk3 [現時点では] + Chunk4 [お答えし] + Suff [かねます。]\\n- Giải thích: Cụm từ 「企業秘密に関わる」 (liên quan đến bí mật kinh doanh) đóng vai trò định ngữ bổ nghĩa cho cụm danh từ 「重要な情報」 (thông tin quan trọng) đi kèm trợ từ chủ đề 「については」. Cụm chỉ thời gian 「現時点では」 (ở thời điểm hiện tại). Động từ khiêm nhường ngữ 「お答えする」 chia ở dạng Masu-form bỏ -masu là 「お答えし」 kết hợp trực tiếp với cấu trúc từ chối lịch sự 「かねます」 (khó lòng/không thể).": "Cấu trúc 「V-かねます」 (khó lòng mà, không thể) là cách từ chối khéo léo trong văn phong trang trọng. Đối với phạm trù 「企業秘密に関わる重要な情報については」 (những thông tin trọng yếu liên quan tới bí mật doanh nghiệp). Lời khước từ được đưa ra dựa trên 「現時点では」 (tại thời điểm hiện tại). Dẫn đến kết luận cuối cùng 「お答えしかねます」 (chúng tôi xin phép không thể trả lời).",
    "Thứ tự sắp xếp: Pref [犯人は] + Chunk1 [刑事の] + Chunk2 [姿を] + Chunk3 [見るが] + Chunk4 [はやいか、路地裏へ] + Suff [向かって走り去った。]\\n- Giải thích: Chủ ngữ 「犯人は」. Cụm sở hữu 「刑事の」 bổ nghĩa cho danh từ 「姿」 (bóng dáng). Động từ thể từ điển 「見る」 đi trực tiếp với cấu trúc 「がはやいか」 (vừa mới... ngay lập tức). Trạng từ chỉ hướng chuyển động 「路地裏へ」 (hướng về phía ngõ hẻm) đi kèm động từ liên kết 「向かって」 (hướng về) và kết thúc bằng động từ phức chỉ hành động trốn chạy 「走り去った」。": "Cấu trúc 「～がはやいか」 (ngay khi vừa... thì lập tức) miêu tả tốc độ phản ứng chớp nhoáng. Kẻ tình nghi 「犯人は」 (tên tội phạm) ngay khoảnh khắc 「刑事の姿を見るがはやいか」 (vừa thoáng thấy bóng dáng cảnh sát). Hắn ta lập tức 「路地裏へ向かって」 (đâm đầu vào con hẻm) và tẩu thoát 「走り去った」 (chạy biến đi mất).",
    "Thứ tự sắp xếp: Pref [今年の夏は] + Chunk1 [平年よりも] + Chunk2 [かなり気温が] + Chunk3 [高くなる] + Chunk4 [かも] + Suff [れない。]\\n- Giải thích: Cụm từ so sánh 「平年よりも」 (so với mọi năm). Trạng từ 「かなり」 (khá là) bổ nghĩa cho tính từ chỉ mức độのdanh từ chủ ngữ 「気温が」. Tính từ 「高い」 biến đổi trạng thái thành 「高くなる」 (trở nên cao). Cụm động từ này kết hợp trực tiếp với ngữ pháp phỏng đoán 「かもしれない」 được tách thành 「かも」 và phần đuôi 「れない」 để hoàn thành cấu trúc.": "Cấu trúc phỏng đoán 「かもしれない」 (có lẽ, không chừng) diễn đạt một khả năng xảy ra. So sánh với quá khứ 「今年の夏は平年よりも」 (mùa hè năm nay so với mọi năm). Có khả năng là 「かなり気温が高くなる」 (nhiệt độ sẽ tăng lên khá cao). Khả năng này được bỏ ngỏ bằng 「かもしれない」 (cũng không biết chừng).",
    "Thứ tự sắp xếp: Pref [たしかに彼の] + Chunk1 [言う通り] + Chunk2 [かもしれないが、] + Chunk3 [私は別の] + Chunk4 [方法を] + Suff [信じたい。]\\n- Giải thích: Phó từ 「たしかに」 (quả thực/chắc chắn) đi với cụm sở hữu 「彼の」. Danh từ 「言う通り」 (như lời nói) kết hợp trực tiếp với cấu trúc phỏng đoán nhượng bộ 「かもしれないが」 (có lẽ là... nhưng). Chủ ngữ 「私」 kết hợp định ngữ 「別の」 để bổ nghĩa cho danh từ 「方法」. Cuối cùng, danh từ này làm tân ngữ cho động từ thể hiện mong muốn 「信じたい」 (muốn tin tưởng).": "Cấu trúc nhượng bộ 「～かもしれないが」 (có thể là... nhưng) thể hiện sự đồng tình một nửa. Thừa nhận rằng 「たしかに彼の言う通りかもしれないが」 (có lẽ quả thực đúng như lời anh ta nói). Tuy nhiên, lập trường kiên định của 「私は」 (bản thân tôi) là 「別の方法を信じたい」 (muốn đặt niềm tin vào một phương thức khác).",
    "Thứ tự sắp xếp: Pref [強い風が] + Chunk1 [吹けば、] + Chunk2 [古い木が] + Chunk3 [倒れて道路を] + Chunk4 [ふさぐかも] + Suff [れない。]\\n- Giải thích: Cấu trúc điều kiện 「吹けば」 (nếu thổi) nối tiếp chủ ngữ 「強い風が」. Ở vế sau, chủ ngữ 「古い木が」 thực hiện hành động liên hoàn: tự động từ 「倒れて」 (đổ xuống) liên kết trực tiếp với hành động tác động 「道路をふさぐ」 (chặn đường). Động từ thể từ điển 「ふさぐ」 kết hợp với cấu trúc phỏng đoán khả năng 「かもしれない」 được chia tách tự nhiên tại từ 「かも」 và 「れない」。": "Cấu trúc phỏng đoán rủi ro 「～かもしれない」 (có nguy cơ sẽ). Bắt đầu từ giả định 「強い風が吹けば」 (nếu có gió thổi mạnh). Hệ lụy tiếp theo là 「古い木が倒れて」 (cây cổ thụ ngã đổ). Hậu quả cuối cùng dẫn tới 「道路をふさぐかもしれない」 (có khả năng sẽ gây ách tắc đường sá).",
    "Thứ tự sắp xếp: Pref [もしあの時に] + Chunk1 [真実を] + Chunk2 [告げていたら、] + Chunk3 [事態は好転して] + Chunk4 [いたかも] + Suff [れない。]\\n- Giải thích: Phó từ giả định 「もし」 đi kèm với cụm từ chỉ thời điểm 「あの時に」. Tân ngữ 「真実を」 chịu tác động bởi động từ thể điều kiện quá khứ 「告げていたら」 (nếu đã nói ra). Mệnh đề kết quả có chủ ngữ là 「事態は」 (tình hình). Trạng thái hoàn thành 「好転していた」 (đã chuyển biến tốt) được tách ra ở phần trợ động từ 「いた」 đi liền với cấu trúc phỏng đoán quá khứ 「かもしれない」 (chia tách thành 「かも」 và 「れない」)。": "Cấu trúc giả định quá khứ 「～ていたら...かもしれない」 (giá mà đã... thì có lẽ đã). Giả định về một thực tại ảo 「もしあの時に真実を告げていたら」 (giá như vào lúc đó đã nói ra sự thật). Nếu vậy, 「事態は好転していたかもしれない」 (tình hình có lẽ đã xoay chuyển theo chiều hướng tốt đẹp hơn).",
    "Thứ tự sắp xếp: Pref [彼はもう] + Chunk1 [私の] + Chunk2 [名前さえ] + Chunk3 [忘れてしまった] + Chunk4 [かも] + Suff [わからない。]\\n- Giải thích: Chủ ngữ 「彼は」 cùng phó từ hoàn thành 「もう」 (đã). Cụm sở hữu 「私の」 bổ nghĩa cho danh từ 「名前」 đi kèm trợ từ nhấn mạnh tiêu cực 「さえ」 (ngay cả). Động từ thể quá khứ hoàn thành 「忘れてしまった」 (đã quên mất) đi trước cấu trúc phỏng đoán không chắc chắn 「かもわからない」 (được tách đôi ở vị trí 「かも」 và 「わからない」 để tạo nhịp điệu sắp xếp).": "Cấu trúc phỏng đoán tiêu cực 「～かもわからない」 (có lẽ cũng không chừng). Nghĩ về đối phương 「彼はもう」 (anh ấy có lẽ đã), đi kèm với sự cường điệu 「私の名前さえ」 (đến ngay cả tên của tôi). Mọi thứ hội tụ lại trong nỗi sợ 「忘れてしまったかもわからない」 (có khi đã quên sạch mất rồi).",
    "Thứ tự sắp xếp: Pref [来期の景気が] + Chunk1 [本当に] + Chunk2 [回復するか] + Chunk3 [わからない] + Chunk4 [状況が] + Suff [続いている。]\\n- Giải thích: Mệnh đề chủ đề 「来期の景気が」 (nền kinh tế kỳ tới). Trạng từ 「本当に」 (thực sự) bổ nghĩa cho động từ 「回復する」 (phục hồi). Trợ từ nghi vấn 「か」 đi sau động từ tạo mệnh đề nghi vấn không chắc chắn kết hợp trực tiếp với tính từ 「わからない」 (không biết/chưa rõ). Cả cụm mệnh đề nghi vấn này đóng vai trò định ngữ bổ nghĩa cho danh từ 「状況」 (tình hình). Kết thúc bằng động từ trạng thái kéo dài 「続いている」。": "Cấu trúc nghi vấn gián tiếp 「～かわからない」 (không biết liệu có... hay không). Dấu hỏi được đặt ra cho 「来期の景気が本当に回復するか」 (tình hình kinh tế kỳ tới liệu có thực sự phục hồi hay không). Sự mơ hồ đó được đúc kết thành 「わからない状況が」 (một tình trạng mù mịt) vẫn đang 「続いている」 (tiếp diễn).",

    # part_22
    "Cấu trúc V-ざるを得ない mang ý nghĩa 「dù không muốn nhưng buộc phải làm hành động V vì hoàn cảnh thực tế không cho phép lựa chọn khác」. Động từ nhóm 2 認める (thừa nhận) bỏ ない thay bằng ざるを得ない thành 認めざるを得ない (buộc phải thừa nhận). Trình tự logic: Hoàn cảnh ép buộc (動かぬ証拠を前にして) -> Chủ thể hành động (経営陣は) -> Đối tượng tác động (自らの不正を) -> Hành vi bắt buộc (認めざるを得なかった)。": "Cấu trúc 「V-ざるを得ない」 (đành phải, buộc phải) biểu thị sự đầu hàng trước hoàn cảnh. Đứng trước áp lực 「動かぬ証拠を前にして」 (trước những bằng chứng không thể chối cãi), giới cầm quyền 「経営陣は」 (ban lãnh đạo). Cuối cùng không còn cách nào khác ngoài việc 「自らの不正を認めざるを得なかった」 (buộc phải thú nhận hành vi sai trái của chính mình).",
    "Cấu trúc N しか + V-ない (thể phủ định) mang ý nghĩa giới hạn 「chỉ có N」. Trong tiểu thuyết miêu tả cảnh vật: 「Trong ngôi làng bị hoang tàn」 (荒廃した村には), 「chỉ có duy nhất một cây cổ thụ」 (一本の古木しか) 「là còn sót lại」 (残っていなかった). Trình tự logic: Trạng ngữ nơi chốn -> Chủ ngữ bị giới hạn -> Động từ phủ định tồn tại.": "Cấu trúc giới hạn cực đoan 「しか...ない」 (chỉ có... mà thôi). Khung cảnh hoang tàn 「荒廃した村には」 (trong ngôi làng điêu tàn ấy) mở ra. Sự cô độc được cô đặc lại ở 「一本の古木しか」 (duy chỉ còn một thân cây cổ thụ). Và kết thúc bằng trạng thái bi đát 「残っていなかった」 (là vẫn còn trơ trọi lại).",
    
    # part_23
    "「過ぎ去って」 (V-te) liên kết với 「しまえば」 (thể điều kiện giả địnhのしまう) tạo nghĩa giả định 「nếu trôi qua」. 「一時の」 (danh từ + の) đóng vai trò định ngữ bổ nghĩa cho 「幻影」. Cấu trúc 「N + でしかない」 biểu thị sự giới hạn phủ định 「chẳng qua chỉ là」. Thứ tự sắp xếp đúng cú pháp: [Điều kiện giả định] -> [Định ngữ] -> [Danh từ + でしか] + [phủ định ない].": "Cấu trúc giới hạn 「～でしかない」 (chẳng qua cũng chỉ là) phơi bày bản chất sự việc. Một khi ranh giới thời gian 「過ぎ去ってしまえば」 (nếu một khi đã trôi qua rồi). Thì mọi thứ 「一時の幻影でしかない」 (chỉ còn là thứ ảo ảnh phù du của một thời) mà thôi.",
    "「私たちは」 là chủ ngữ thực hiện hành động. 「持ち物を」 là tân ngữ chịu tác độngのđộng từ liên kết 「まとめて」 (V-te). Hành động tiếp nối tiếp theo là 「山を下りる」 (xuống núi). Cấu trúc 「V-ru + しかない」 thể hiện ý chí không còn lựa chọn nào khác ngoài việc thực hiện hành động V. Thứ tự đúng: [Chủ ngữ] -> [Tân ngữ + Động từ nối] -> [Động từ chính + しか] + [phủ định ない].": "Cấu trúc đường cùng 「V-るしかない」 (chỉ còn cách là, không còn cách nào khác). Khi lâm vào thế bí, 「私たちは」 (chúng tôi) chỉ có thể 「持ち物をまとめて」 (gom góp đồ đạc). Lựa chọn duy nhất còn lại là 「山を下りるしかない」 (không còn cách nào khác ngoài việc xuống núi).",
    "「しかし」 là liên từ nối nghịch cảnh (tuy nhiên) đứng đầu câu sau. 「実用化には」 (đối với việc đưa vào thực tiễn) là cụm giới hạn phạm vi tác động. 「まだ」 là phó từ chỉ trạng thái chưa hoàn thành bổ nghĩa cho vị ngữ. 「時間が」 là chủ ngữのtự động từ 「かかる」 (tốn thời gian). Thứ tự logic tự nhiên: [Liên từ] -> [Phạm vi tác động] -> [Phó từ] -> [Chủ ngữ] + [Động từ].": "Liên từ 「しかし」 (tuy nhiên) lật ngược lại kỳ vọng. Chuyển sang thực tiễn, việc 「実用化には」 (đưa vào ứng dụng thực tế). Bị vấp phải rào cản là 「まだ時間がかかる」 (vẫn sẽ còn tốn khá nhiều thời gian).",
    "「しかしながら」 là liên từ chỉ sự tương phản mang sắc thái trang trọng (tuy nhiên). 「地方の」 (ở địa phương) bổ nghĩa cho danh từ 「雇用情勢」 (tình hình việc làm). 「依然として」 là phó từ bổ nghĩa cho cụm vị ngữ 「厳しいままだ」 (vẫn còn nghiêm trọng) để nhấn mạnh trạng thái không đổi. Thứ tự logic tự nhiên: [Liên từ trang trọng] -> [Định ngữ] -> [Chủ ngữ chính] -> [Phó từ] + [Tính từ vị ngữ].": "Liên từ trang trọng 「しかしながら」 (mặc dù vậy) phác họa một thực tế trái ngược. Trọng tâm là 「地方の雇用情勢は」 (tình hình việc làm ở các địa phương). Tình cảnh đó 「依然として厳しいままだ」 (vẫn đang trong trạng thái vô cùng ảm đạm).",
    "「ここで」 chỉ vị trí xảy ra hành động (tại đây). 「一晩」 là lượng từ chỉ thời gian (một đêm) bổ nghĩa cho động từ. 「待つ」 bổ nghĩa trực tiếp cho danh từ 「しかた」 trong cấu trúc 「V-ru + しかたがない」 (không còn cách nào khác ngoài việc V). Thứ tự đúng: [Địa điểm] -> [Thời gian] -> [Động từ] -> [chủ thể ngữ pháp しかたが] + [phủ định ない].": "Cấu trúc 「V-るしかたがない」 (đành phải, không còn cách nào khác) bộc lộ sự cam chịu. Đứng giữa bối cảnh 「ここで」 (tại nơi này), phương án duy nhất là 「一晩」 (một đêm). Và đi đến quyết định 「待つしかたがない」 (đành phải chờ đợi chứ không còn cách nào).",
    "「政府や」 (chính phủ và...) liên kết ngang hàng với 「民間の」 (thuộc tư nhân) để làm định ngữ. 「今後の」 (từ nay về sau) bổ nghĩa thêm cho danh từ trung tâm 「支援体制」 (thể chế hỗ trợ). Cấu trúc 「N + しだいだ」 chỉ sự phụ thuộc quyết định vào danh từ đó. Thứ tự logic: [Định ngữ liên hợp 1] -> [Định ngữ 2] -> [Định ngữ 3] -> [Danh từ chính] + [しだいだ].": "Cấu trúc 「N次第だ」 (tùy thuộc hoàn toàn vào) quy trách nhiệm cho một nhân tố. Vấn đề là 「政府や民間の」 (của cả chính phủ và khối tư nhân). Mọi thứ đặt cược vào 「今後の支援体制しだいだ」 (phụ thuộc vào hệ thống hỗ trợ từ nay về sau).",
    "「皆様に」 chỉ đối tượng chịu ảnh hưởngのhành động phiền hà. 「多大な」 là tính từ đuôi -na bổ nghĩa cho danh từ 「ご迷惑」. 「おかけした」 là dạng kính ngữ/khiêm nhườngのhành động làm phiền (V-ta) bổ nghĩa cho danh từ 「次第です」 trong cấu trúc 「V-ta + 次第だ」 dùng để trình bày, giải thích đầu đuôi sự tình. Thứ tự logic: [Đối tượng] -> [Tính từ] -> [Danh từ] -> [V-ta kính ngữ] + [次第です].": "Cấu trúc giãi bày 「V-た次第です」 (sự tình là đã...) thể hiện thái độ phân trần lịch sự. Hành vi hướng tới 「皆様に多大な」 (rất nhiều sự phiền hà tới quý vị). Sự cố đó kết tinh trong lời tạ lỗi 「ご迷惑をおかけした次第です」 (sự tình là chúng tôi đã gây ra cớ sự này).",
    "「事と」 liên kết với 「次第」 tạo thành thành ngữ cố định 「事と次第」 (tình hình sự việc). 「によっては」 đứng sau danh từ mang nghĩa 「tùy thuộc vào」. 「この古い」 (cũ kỹ này) bổ nghĩa trực tiếp cho danh từ 「同盟」 ở vị ngữ chính. Thứ tự logic: [事と] -> [次第に] -> [よっては] -> [Định từ chỉ định và tính từ] + [Tân ngữ + Vị ngữ].": "Cụm từ cố định 「事と次第によっては」 (tùy thuộc vào diễn biến của sự việc). Nó mở ra một nguy cơ tiềm tàng. Rằng có thể 「この古い同盟関係さえも」 (ngay cả mối quan hệ đồng minh lâu đời này). Cũng có nguy cơ bị đe dọa phá vỡ.",
    "「したがって」 (Vì vậy/Do đó) là liên từ đứng đầu vế sau để nối kết quả nguyên nhân. 「来月から」 chỉ mốc thời gian bắt đầu. 「製品の」 bổ nghĩa cho danh từ 「価格」 để tạo thành cụm tân ngữ đi kèm trợ từ 「を」. Hành động tác động cuối cùng là 「値上げする」. Thứ tự logic: [Liên từ nhân quả] -> [Mốc thời gian] -> [N-no] -> [Tân ngữ + を] + [Động từ].": "Liên từ nhân quả 「したがって」 (do đó, chính vì vậy) dẫn lối đến một quyết định tất yếu. Bắt đầu từ 「来月から」 (kể từ tháng sau). Quyết định được ban hành là 「製品の価格を値上げする」 (sẽ tiến hành tăng giá các mặt hàng sản phẩm).",
    "「実は」 (Thực ra) là trạng từ đứng đầu mệnh đề giải thích sự thật khuất tất. 「内面は」 đóng vai trò chủ ngữのmệnh đề này. 「不安で」 (bởi sự lo lắng) là cụm chỉ trạng thái/nguyên nhân đi kèm với bổ ngữ 「いっぱい」 (đầy rẫy). 「なのだ」 là dạng nhấn mạnh sự thậtの「だ」. Thứ tự đúng: [Trạng từ] -> [Chủ ngữ -wa] -> [Cụm nguyên nhân -de] -> [ippai] + [vị ngữ kết thúcなのだ].": "Phó từ 「実は」 (thực ra thì) được dùng để lột mặt nạ vỏ bọc. Khác với vẻ ngoài, 「内面は」 (tâm tư bên trong) lại chứa đựng một sự thật phũ phàng. Đó là 「不安でいっぱいなのだ」 (tràn ngập những nỗi hoang mang lo sợ).",
    "「実を言うと」 (Nói thật ra thì) là cụm phó từ cố định tách từ 「実」 và 「言う」. 「彼がその」 gồm chủ ngữ 「彼」 đi với trợ từ 「が」 và từ chỉ định 「その」 bổ nghĩa cho 「秘密」. 「秘密を」 là tân ngữ chịu tác độngのmệnh đề bổ ngữ 「漏らした」 (đã làm rò rỉ) bổ nghĩa cho danh từ chỉ người 「張本人」 (kẻ cầm đầu/chủ mưu). Thứ tự logic: [Cụm phó từ tiết lộ sự thật] -> [Chủ ngữ + chỉ định từ] -> [Tân ngữ + を] + [Định ngữ + Danh từ vị ngữ].": "Cụm từ mào đầu 「実を言うと」 (thú thực mà nói thì) chuẩn bị tiết lộ một bí mật động trời. Sự thật bị bóc trần là 「彼がその秘密を漏らした」 (việc hắn ta chính là kẻ đã làm lộ bí mật đó). Hắn ta đích thị là 「張本人だ」 (tên đầu sỏ gây ra mọi chuyện).",
    "「実のところ」 là cụm phó từ cố định có nghĩa là 「thực chất là/thực tế là」. 「運営の」 bổ nghĩa cho danh từ 「舞台裏」 (phía sau cánh gà/hậu trường). 「舞台裏は」 đóng vai trò chủ ngữ chínhのmệnh đề tiếp theo, đi với vị ngữ chỉ trạng thái 「かなり混乱している」 (khá hỗn loạn). Thứ tự logic: [Cụm phó từ] -> [Định ngữ N-no] -> [Chủ ngữ -wa] + [Vị ngữ trạng thái].": "Cụm từ 「実のところ」 (trên thực tế thì) phơi bày một góc khuất. Khuất lấp đằng sau ánh hào quang, 「運営の舞台裏は」 (phía sau hậu trường của khâu tổ chức) lại là một bức tranh khác. Đó là tình cảnh 「かなり混乱している」 (đang rơi vào trạng thái khá là hỗn loạn).",
    "「会社の」 đóng vai trò định ngữ sở hữu bổ nghĩa cho danh từ 「金」. 「金にまで」 là cụm chỉ mức độ cực đoan đi kèm trợ từ 「まで」 (đến tận mức...). 「手を染める」 (nhúng tay vào/dính chàm) là cụm động từ bổ nghĩa trực tiếp cho danh từ 「始末」 trong cấu trúc ngữ pháp 「V-ru + 始末だ」 diễn tả một kết cục tồi tệ không mong muốn. Thứ tự đúng: [N-no] -> [N-ni made] -> [Tân ngữ + を] -> [Động từ V-ru] + [始末だ].": "Cấu trúc kết cục tồi tệ 「V-る始末だ」 (cuối cùng dẫn tới nông nỗi...). Sự tha hóa bắt đầu từ việc 「会社の金にまで」 (đến ngay cả tiền công quỹ của công ty). Kẻ đó cũng mờ mắt 「手を染める始末だ」 (đi đến bước đường cùng là nhúng chàm vào).",
    "「じゃあ」 là liên từ dùng trong hội thoại mang tính suy luận (Thế thì/Vậy thì) dựa trên thông tin người kia vừa nói. 「明日の」 là định ngữ chỉ thời gian bổ nghĩa cho 「ハイキング」. 「ハイキングは」 là chủ đề chính được thảo luận. 「中止だね」 là danh từ vị ngữ đi kèm từ biểu thị cảm xúc 「ね」. Thứ tự logic: [Liên từ suy luận] -> [Định ngữ] -> [Chủ ngữ -wa] -> [Vị ngữ] + [Trợ từ cuối câu].": "Liên từ 「じゃあ」 (vậy thì, thế thì) dùng để đưa ra kết luận từ hoàn cảnh trước mắt. Đối tượng được nhắc tới là 「明日のハイキングは」 (buổi đi dã ngoại vào ngày mai). Từ đó đưa ra phán quyết 「中止だね」 (thành ra là bị hủy rồi nhỉ).",
    "「じゃあ」 là liên từ dùng để chuyển đổi chủ đề nói chuyện (Thế thì/Sau đây...). 「次の」 bổ nghĩa cho danh từ 「議題」 (đề tài thảo luận tiếp theo). 「議題に」 chỉ hướng đích đến đi kèm trợ từ 「に」. 「移りましょう」 là dạng ý chí kêu gọi 「ましょう」のđộng từ 「移る」 chia ở thể liên dụng. Thứ tự logic: [Liên từ chuyển đổi] -> [Định ngữ] -> [Danh từ chỉ hướng -ni] -> [V-masu stem] + [ましょう].": "Liên từ 「じゃあ」 (vậy thì, tiếp theo) dùng để ngắt mạch và bẻ lái câu chuyện. Hướng tới mục tiêu mới 「次の議題に」 (sang chủ đề thảo luận tiếp theo). Đề xuất đưa ra là 「移りましょう」 (chúng ta cùng chuyển sang nào)."
}

for i in range(14, 26):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 5 Batch 1 (parts 14-25) manually reviewed and rewritten successfully!")
