import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_4_literature'

rewrites = {
    # part_22
    "Cấu trúc biểu thị sự xin phép: V-させて (thể sai khiến) + ください。Thứ tự sắp xếp tự nhiên: 「どうか」 (phó từ khẩn cầu) bổ nghĩa cho hành động cuối câu -> 「私に」 (chỉ đối tượng thực hiện hành động sai khiến đi với trợ từ に) -> 「最後の瞬間まで」 (trạng ngữ chỉ thời gian) -> 「語らせて」 (thể sai khiến nhóm 1の語る) -> 「ください」 (yêu cầu lịch sự).": "Cấu trúc 「V-させてください」 biểu thị sự xin phép (xin hãy cho tôi làm...). Lời khẩn cầu mở đầu bằng phó từ 「どうか」 (xin hãy). Tiếp đến là chủ thể hành động 「私に」 (cho phép tôi) và giới hạn thời gian 「最後の瞬間まで」 (cho đến khoảnh khắc cuối cùng). Tất cả dẫn đến mong mỏi 「語らせてください」 (được nói ra).",
    "Cấu trúc 「Nしか～ない」 biểu thị sự duy nhất (chỉ có...). Thứ tự sắp xếp tự nhiên: 「一人の」 (lượng từ bổ nghĩa cho danh từ chỉ người) -> 「社員」 (danh từ chỉ đối tượng) -> 「しか」 (trợ từ đi sau danh từ) -> 「残って」 (thể てのđộng từ 残る) -> 「いなかった」 (thể phủ địnhのいる đi kèm sau thể て, kết hợp với しか để nhấn mạnh chỉ còn lại).": "Cấu trúc 「Nしか～ない」 nhấn mạnh tính chất duy nhất (chỉ có... mà thôi). Sự đơn độc thể hiện qua 「一人の社員」 (một người nhân viên) kết hợp với 「しか」 (chỉ). Trạng thái cuối cùng bị giới hạn lại bằng cụm phủ định 「残っていなかった」 (đã chẳng còn sót lại).",

    # part_28
    "Thứ tự sắp xếp dựa trên sự liệt kê các danh từ làm tân ngữ cho động từ 置いた ở cuối câu. 「古い本」 (sách cũ) và 「黒い万年筆」 (bút máy màu đen) là các danh từ được liệt kê trước. Liên từ 「そうして」 dùng để nối danh từ cuối cùng 「一枚の」 (một tấm - bổ nghĩa cho 写真) vào chuỗi liệt kê. Cấu trúc đầy đủ là 「[N1]、[N2]、そうして、[N3]を [Động từ]」.": "Câu văn liệt kê các đối tượng nhằm phục vụ cho hành động chính 「置いた」 (đã đặt). Ban đầu là 「古い本」 (quyển sách cũ) và 「黒い万年筆」 (cây bút máy đen). Liên từ 「そうして」 (và rồi) kết nối đối tượng cuối cùng 「一枚の写真」 (một bức ảnh) trước khi đi đến động từ.",

    # part_39
    "Câu nói về lý tưởngのngười nhà báo. Ở đây 「つまり」 (tức là) dùng để giải thích rõ hơn, diễn đạt lại cụm 「真実を追うこと」 (việc theo đuổi sự thật) thành 「権力の監視」 (giám sát quyền lực). Thứ tự sắp xếp tự nhiên theo ngữ pháp: Trợ từ 「を」 đi sau danh từ 「真実」 để làm tân ngữ cho danh từ hóa 「追うこと」; liên từ 「つまり」 liên kết hai cụm đồng nghĩa; trợ từ 「に」 đi sau danh từ chỉ mục đích 「監視」 để bổ nghĩa cho động từ 「命を捧げた」 (cống hiến sinh mạng cho...).": "Liên từ 「つまり」 (nghĩa là, nói cách khác) được dùng để đúc kết lại ý nghĩa. Việc 「真実を追うこと」 (theo đuổi sự thật) được làm rõ hơn qua 「つまり」. Nó đồng nghĩa với đích đến 「権力の監視に」 (vào việc giám sát quyền lực), để rồi dẫn tới sự cống hiến lớn lao 「命を捧げた」 (đã dâng hiến cả sinh mạng).",
    "Câu mang tính chất bình luận thời sự về một dự luật. 「つまり」 ở đây dùng để đưa ra kết luận diễn dịch cuối cùng (「Tóm lại là/Nói tóm lại...」). Thứ tự sắp xếp đúng cú pháp: Chủ ngữ 「この法案の可決は」 đứng trước; liên từ 「つまり」 đứng đầu mệnh đề kết luận bổ nghĩa cho trạng thái thực tế 「実質的な増税」 (tăng thuế trên thực tế); cụm động từ 「意味しているのだ」 (nghĩa là...) đứng ở cuối câu để hoàn thành cấu trúc biểu thị ý nghĩa.": "Liên từ 「つまり」 (tóm lại là) đưa ra kết luận rút ra từ một sự kiện. Việc 「この法案の可決は」 (sự thông qua dự luật này) được 「つまり」 đúc kết bản chất. Hệ quả thực tế của nó là 「実質的な増税を意味しているのだ」 (chính là sự tăng thuế trên thực tế).",
    "Cấu trúc 「V-る + つもりで」 biểu thị trạng thái chuẩn bị tinh thần hoặc mang mục đích, ý định khi thực hiện hành động tiếp theo. Thứ tự sắp xếp câu văn văn học: Cụm tân ngữ chỉ đối tượng 「波乱万丈な半生を」 (nửa đời đầy sóng gió) đứng trước địa điểm/hình thức 「小説に」 (vào tiểu thuyết) và động từ 「書く」; động từ 「書く」 bổ nghĩa cho danh từ 「つもりで」 để thể hiện ý định; vế sau kết thúc bằng cụm hành động thực tế 「ペンを取った」 (đã cầm bút).": "Cấu trúc 「つもりで」 biểu thị ý định và tâm thế sẵn sàng. Mục đích 「波乱万丈な半生を小説に」 (đem nửa đời sóng gió viết thành tiểu thuyết) được gắn với động từ 「書く」 (viết). Nó hợp lại với 「つもりで」 (với ý định đó) để thôi thúc hành động 「ペンを取った」 (cầm bút lên).",
    "Cấu trúc 「V-た + つもりで」 diễn tả giả định xem như đã thực hiện hành động đó (dù thực tế chưa) để lấy quyết tâm làm việc khác. Thứ tự sắp xếp câu mang tính chất quyết liệtのphóng viên điều tra: Trạng từ 「もう」 (đã) đi kèm động từ quá khứ 「死んだ」 bổ nghĩa cho danh từ 「つもりで」 (với tâm thế như đã chết); vế sau là cụm tân ngữ 「社会の闇を」 (góc tối xã hội) bổ nghĩa cho động từ 「暴く」 (vạch trần); từ 「暴く」 bổ nghĩa cho danh từ 「取材」 (hoạt động lấy tin/phóng sự) làm mục tiêu cho hành động cuối 「挑む」 (thử thách/dấn thân).": "Cấu trúc 「V-たつもりで」 giả định một trạng thái cực đoan để lấy quyết tâm. Trạng thái 「もう死んだ」 (đã chết rồi) kết hợp với 「つもりで」 (mang tâm thế). Tâm thế tử vì đạo đó nhằm mục tiêu 「社会の闇を暴く」 (vạch trần góc khuất xã hội) trước khi dấn thân vào hành động 「取材に挑む」 (bước vào cuộc tác nghiệp điều tra).",
    "Cấu trúc lặp lại tính từ đuôi イ 「A-くて A-くて + ならない/仕方がない」 nhằm nhấn mạnh cảm xúc vô cùng mãnh liệt, không thể kìm nén được. Thứ tự sắp xếp trong bản tin phóng sự: Chủ ngữ 「被害者の母親は」 đứng đầu mệnh đề chính; tính từ 「悔しい」 (tiếc nuối, uất hận) được lặp lại thành 「悔しくて悔しくて」 để nhấn mạnh nỗi đau; tiếp theo là cụm biểu thị mức độ cực hạn 「ならなかった」 (không chịu nổi) kết hợp với trợ từ trích dẫn 「と」; cuối cùng là hành động miêu tả biểu cảm 「涙を拭った」 (lau nước mắt).": "Cấu trúc lặp tính từ 「～くて～くてならない」 đẩy cảm xúc lên đỉnh điểm (vô cùng..., hết sức...). Sự đau xót của 「被害者の母親は」 (mẹ nạn nhân) được khắc họa qua sự lặp lại 「悔しくて悔しくて」 (uất hận đến mức). Cảm xúc đó tràn ra 「ならなかった」 (không sao kìm nén nổi), kết thúc bằng động tác 「涙を拭った」 (lau đi dòng nước mắt).",
    "Cấu trúc yêu cầu lịch sự 「V-てあげてください」 (xin hãy làm việc gì đó có lợi cho đối tượng khác). Thứ tự sắp xếp lời thoại nhân vật: Trạng từ 「その」 kết hợp tính từ quá khứ 「傷ついた」 bổ nghĩa cho danh từ 「鳥を」 (chú chim bị thương); tiếp theo là cách thức hành động 「優しく手当てして」 (nhẹ nhàng chữa trị); động từ thể て kết hợp với 「あげて」 và kết thúc câu yêu cầu bằng 「ください」; cuối cùng bao bọc bằng dấu ngoặc kép và trợ từ 「と」 đi với động từ tường thuật 「頼んだ」 (đã cầu xin).": "Cấu trúc 「V-てあげてください」 diễn đạt sự nhờ vả vì lợi ích của người thứ ba. Đối tượng hướng đến là 「その傷ついた鳥を」 (chú chim bị thương đó). Cách thức 「優しく手当てして」 (nhẹ nhàng băng bó) kết hợp với mong mỏi 「あげてください」 (xin hãy làm cho nó). Cuối cùng, toàn bộ cụm trích dẫn khép lại bằng 「と頼んだ」 (đã khẩn cầu).",

    # part_41
    "Cấu trúc biểu thị trạng thái đang diễn ra: 「V-ている」. Ở đây động từ 「眠る」 (ngủ) chia sang thể Te là 「眠って」 đi kèm 「いる」 thành 「眠っている」 (đang ngủ). Thứ tự sắp xếp tự nhiên trong câu: Trạng ngữ chỉ nơi chốn 「古い公園の池の前に」 đứng đầu, tiếp theo là chủ ngữ chỉ đối tượng thực hiện hành động 「猫が」, phó từ bổ nghĩa cho động từ 「静かに」 đứng trước động từ liên kết 「眠っている」 tạo nên một câu tả cảnh hoàn chỉnh.": "Cấu trúc 「V-ている」 mô tả một trạng thái đang hiện diện. Bối cảnh 「古い公園の池の前に」 (trước cái hồ của khu công viên cũ) mở ra không gian. Ở đó, nhân vật chính 「猫が」 (chú mèo) ở trong trạng thái 「静かに」 (một cách tĩnh lặng) và kết thúc bằng hành động 「眠っている」 (đang say ngủ).",
    "Ngữ pháp 「V-ておく」 biểu thị việc chuẩn bị trước một hành động cho mục đích nào đó. Động từ 「調べる」 (tra cứu, tìm hiểu) được chia ở thể Te là 「調べて」 kết hợp với 「おく」. Thứ tự logic: Mục đích 「明日の取材のために」 (để chuẩn bị cho buổi thu thập thông tin ngày mai) -> Định ngữ chỉ sở hữu 「この町の」 bổ nghĩa cho danh từ tân ngữ 「歴史」 -> Tân ngữ kèm trợ từ chỉ đối tượng 「歴史を」 -> Phó từ bổ nghĩa 「よく」 -> Cấu trúc hành động chuẩn bị 「調べておく」.": "Cấu trúc 「V-ておく」 diễn tả sự chuẩn bị sẵn sàng (làm sẵn, làm trước). Động cơ là 「明日の取材のために」 (vì buổi phỏng vấn ngày mai). Đối tượng 「この町の歴史を」 (lịch sử của thị trấn này) được gắn với mức độ 「よく」 (kỹ lưỡng) và chốt bằng hành động chuẩn bị 「調べておく」 (tìm hiểu trước).",
    "Cấu trúc 「V-てからでないと... ない」 nghĩa là 「Nếu chưa làm V1 thì không thể làm V2」. Ở đây, V1 là 「確認する」 (xác nhận) chuyển thành 「確認して」 kết hợp với 「からでないと」. Thứ tự sắp xếp câu logic: Tân ngữ bổ nghĩa 「統計のデータを」 -> V1 thể Te 「確認して」 -> Liên kết giả định tiêu cực 「からでないと」 -> Định ngữ chỉ định 「この」 -> Chủ ngữ vế sau làm chủ thể tiếp nhận hành động phủ định khả năng 「社説は」 -> V2 thể phủ định khả năng 「書けない」 (không thể viết).": "Cấu trúc 「V-てからでないと...ない」 nhấn mạnh điều kiện tiên quyết (nếu chưa... thì không thể...). Việc kiểm chứng 「統計のデータを確認して」 (xác nhận dữ liệu thống kê) kết nối với 「からでないと」. Nếu thiếu đi bước này, kết quả 「この社説は」 (bài xã luận này) sẽ dẫn tới sự bế tắc 「書けない」 (chẳng thể nào viết được).",
    "Mẫu câu 「V-てからでないto...」 kết hợp với một kết quả không mong muốn ở thể bị động/thông thường (ở đây là 「怒られる」 - bị mắng). Trình tự logic: Đối tượng cấp trên 「編集長に」 -> Tân ngữ 「許可を」 -> Động từ nhận 「もらって」 -> Cấu trúc điều kiện ràng buộc 「からでないと」 -> Trạng từ thời gian vế sau 「後で」 -> Hệ quả tiêu cực kết thúc câu 「怒られる」.": "Cấu trúc 「V-てからでないと...」 báo trước một hệ quả xấu nếu bỏ qua thủ tục. Hành động 「編集長に許可をもらって」 (nhận được sự cho phép của tổng biên tập) nối với 「からでないと」. Nếu tự ý làm, 「後で」 (sau này) sẽ phải gánh chịu kết quả 「怒られる」 (bị mắng).",
    "Cấu trúc ngữ pháp cao cấp 「V-てからというもの（は）」 dùng để biểu thị kể từ sau khi một sự kiện xảy ra thì có một sự thay đổi lớn kéo dài liên tục đến nay. V1 là 「始まる」 (bắt đầu) chuyển thành thể Te 「始まって」. Thứ tự sắp xếp câu: Định ngữ cảm xúc 「あの悲惨な」 -> Chủ ngữ sự kiện vế đầu 「戦争が」 -> Hành động khởi đầu thể Te 「始まって」 -> Mẫu cấu trúc giới hạn thời điểm 「からというものは」 -> Nơi chốn khởi nguồnのsự thay đổi 「この街から」 -> Kết quả biến đổi tiêu cực kéo dài ở cuối câu 「笑顔が消えてしまった」.": "Cấu trúc 「V-てからというもの」 đánh dấu một bước ngoặt đem lại sự biến đổi sâu sắc. Sự kiện 「あの悲惨な戦争が始まって」 (kể từ khi cuộc chiến tranh thảm khốc đó bắt đầu) kết hợp với 「からというものは」. Từ thời điểm đó trở đi, 「この街から」 (từ thành phố này) đã dẫn tới thảm kịch 「笑顔が消えてしまった」 (nụ cười đã hoàn toàn biến mất).",
    "Cấu trúc 「V-てくる」 ở đây chỉ trạng thái/phương thức di chuyển tiến lại gần vị tríのngười nói (vừa thực hiện hành động V vừa tiến lại gần). Động từ di chuyển 「走る」 (chạy) chuyển sang thể Te 「走って」 kết hợp với 「きた」. Trình tự logic: Chủ ngữ thực hiện hành động 「目撃者は」 -> Trạng thái đồng thời 「震えながら」 (vừa run rẩy vừa...) -> Điểm đến danh từ 「警察署」 -> Trợ từ giới hạn điểm đến 「まで」 -> Động từ hành động di chuyển kết hợp thể hướng tâm 「走ってきた」.": "Cấu trúc 「V-てくる」 diễn tả hành động hướng về phía người chứng kiến. 「目撃者は」 (nhân chứng) đi cùng trạng thái 「震えながら」 (vừa run rẩy vừa...). Hướng đi xác định là 「警察署まで」 (đến tận đồn cảnh sát) và kết thúc bằng động tác lao tới 「走ってきた」 (đã chạy đến).",
    "Ý nghĩa 「V-てくる」 chỉ hướng di chuyển tiến về phía người nói hoặc về một điểm mốc không gian mà người nói đang đứng từ góc nhìn trần thuật. Động từ hồi hương 「帰る」 chuyển thành thể Te 「帰って」 kết hợp với động từ di chuyển gốc 「くる」 ở quá khứ 「きた」. Thứ tự logic: Chủ ngữ miêu tả 「若い写真家は」 -> Phó từ tần suất 「再び」 (lại một lần nữa) -> Định ngữ chỉ tính chất nơi chốn 「この荒れた」 -> Điểm đến kèm trợ từ chỉ hướng 「村に」 -> Tổ hợp động từ di chuyển hướng tâm 「帰ってきた」.": "Hướng tác động 「V-てくる」 cho thấy sự quay lại vị trí trung tâm của câu chuyện. 「若い写真家は」 (nhiếp ảnh gia trẻ) mang theo phó từ 「再び」 (một lần nữa). Anh hướng tới không gian 「この荒れた村に」 (về ngôi làng hoang tàn này) và hoàn thành hành trình 「帰ってきた」 (đã trở về).",
    "Ý nghĩa 「V-てくる」 (Kế khởi) biểu thị việc đi thực hiện một hành động ở một nơi khác rồi quay trở lại vị trí ban đầu (Làm việc gì đó rồi quay lại). Động từ hành động 「買う」 chia ở thể Te 「買って」 đi cùng 「きます」. Trình tự logic: Định ngữ thời gian 「今日の」 -> Tân ngữ mua sắm 「新聞を」 -> Phó từ mức độ mang tính giảm nhẹ 「ちょっと」 -> Nơi chốn xảy ra hành động 「売店で」 -> Hành động vế trước thể Te 「買って」 -> Hành động quay lại ở cuối câu 「きます」.": "Cấu trúc 「V-てくる」 diễn tả việc rời đi thực hiện hành động rồi sẽ quay về. Sự kiện là mua 「今日の新聞を」 (tờ báo hôm nay). Mức độ là 「ちょっと」 (một chốc), xảy ra tại 「売店で」 (quầy bán lẻ). Hành động 「買って」 kết nối với 「きます」 thể hiện sự dời gót đi mua rồi sẽ trở lại.",
    "Cấu trúc 「V-てくる」 biểu thị một trạng thái mới bắt đầu xuất hiện hoặc lọt vào tầm mắtのngười nói (xuất hiện, hiện ra). Động từ khả năng tự phát 「見える」 (nhìn thấy) chia ở thể Te 「見えて」 kết hợp với 「きた」. Thứ tự sắp xếp logic: Phó từ trạng thái 「ゆっくりと」 (chầm chậm) -> Chủ ngữ vế đầu 「黒い雲が」 -> Trạng thái biến đổi trung gian 「晴れて」 -> Đối tượng xuất hiện vế sau 「青い空が」 -> Biểu đạt sự xuất hiện ở cuối câu 「見えてきた」.": "Cấu trúc 「V-てくる」 đánh dấu một sự hiện diện mới bắt đầu tỏ tường. Diễn tiến mở đầu 「ゆっくりと黒い雲が晴れて」 (đám mây đen từ từ tan đi). Phía sau lớp mây đó, 「青い空が」 (bầu trời xanh thẳm) từ từ xuất hiện rõ rệt 「見えてきた」 (dần lộ ra).",
    "Cấu trúc 「V-てくる」 biểu thị hành độngのmột đối tượng khác hướng về phía người nói hoặc nhómのngười nói (ở đây người viết đứng ở lập trường chính phủ hoặc quan sát viên tiếp nhận). Động từ gửi 「送る」 được chia ở thể Te 「送って」 kết hợp trợ động từ biểu đạt hướng tác động 「きた」. Thứ tự logic: Chủ thể hành động 「野党の代表が」 -> Đối tượng nhận hành động hướng tâm 「政府に」 -> Tính từ bổ nghĩa 「厳しい」 -> Tân ngữ trực tiếp 「抗議を」 -> Động từ hành động hướng về phía đối tượng trung tâm 「送ってきた」.": "Cấu trúc 「V-てくる」 thể hiện việc hứng chịu một hành động từ phía khác dội tới. Phía phát động là 「野党の代表が」 (đại diện đảng đối lập) hướng mũi nhọn 「政府に」 (về phía chính phủ). Hành động đả kích 「厳しい抗議を」 (lời phản đối gay gắt) đập thẳng tới bằng 「送ってきた」 (đã gửi tới).",
    "Ngữ pháp 「V-てくれ」 là thể mệnh lệnh, yêu cầu một cách suồng sã, trực tiếp (hầu như chỉ dùng bởi nam giới hoặc trong các tình huống khẩn cấp, kịch tính trong tiểu thuyết). Động từ 「話す」 chia ở thể Te 「話して」 kết hợp với 「くれ」. Trình tự logic: Trạng từ thời gian cụ thể 「あの夜に」 -> Chủ ngữのmệnh đề phụ 「何が」 -> Động từ nghi vấn gián tiếp 「あったのか」 -> Tân ngữ đích thực 「真実を」 -> Động từ hành động yêu cầu mệnh lệnh kết thúc câu 「話してくれ」.": "Thể mệnh lệnh 「V-てくれ」 mang sắc thái suồng sã, bức thiết. Nhấn mạnh vào bí mật 「あの夜に何があったのか」 (đã xảy ra chuyện gì trong đêm đó). Tâm điểm là 「真実を」 (sự thật), dẫn tới tiếng thét đòi hỏi 「話してくれ」 (nói cho tôi biết đi).",
    "Cấu trúc 「V-てくれる」 diễn tả hành độngのngười khác mang lại lợi ích cho người nói hoặc người thuộc nhómのngười nói. Động từ 「教える」 chia ở thể Te 「教えて」 kết hợp với trợ động từ ban ơn 「くれた」. Thứ tự logic: Chủ thể thực hiện hành động tốt 「親切な先生が」 -> Người nhận lợi ích 「私に」 -> Định ngữ chỉ địa điểm 「図書館の」 -> Tân ngữ đối tượng 「道を」 -> Động từ chia thể Te kèm hành động ban ơn 「教えてくれた」.": "Cấu trúc 「V-てくれる」 dùng khi bản thân nhận được ơn huệ từ người khác. Chủ thể trao ơn là 「親切な先生が」 (giáo viên tốt bụng). Hướng tới người nhận 「私に」 (cho tôi), liên quan đến 「図書館の道を」 (đường đến thư viện), và kết thúc bằng sự mang ơn 「教えてくれた」 (đã chỉ dạy cho).",
    
    # part_42
    "Cấu trúc 「V-てやってくれないか」 dùng để nhờ vả một cách thân mật nhưng khẩn thiết. Thứ tự sắp xếp: 「記事に」 (trên bài báo) -> Động từ chia thể Te 「書いて」 (viết) -> 「やって」 (làm cho đối tượng yếu thế hoặc vai dưới) -> 「くれない」 (thể phủ địnhのくれる biểu thị ý nhờ vả) -> Trợ từ nghi vấn 「か」 kết thúc câu.": "Cấu trúc 「V-てやってくれないか」 là lời nhờ vả vừa thân tình vừa khẩn thiết. Sự mong mỏi là 「記事に」 (trên bài báo) có hành động 「書いて」 (viết). Tiếp đến là 「やってくれないか」 (cậu làm điều đó giúp được không) để cầu xin lòng thương hại cho người yếu thế.",
    "Cấu trúc khiêm nhường ngữ 「V-て差し上げる」 dùng khi làm việc có lợi cho người có vai vế cao hơn. Thứ tự sắp xếp: 「夫人に向かって」 (hướng về phía phu nhân) -> Động từ 「読む」 chia thể Te thành 「読んで」 -> Kết hợp trợ động từ khiêm nhường 「差し上げた」 chia ở quá khứ.": "Cấu trúc khiêm nhường 「V-て差し上げる」 chỉ việc phụng sự một nhân vật bề trên. Hành động 「夫人に向かって」 (hướng về phía vị phu nhân) đi kèm với động tác 「読んで」 (đọc). Toàn bộ tôn kính ấy hội tụ trong sự dâng hiến ở cuối câu 「差し上げた」 (đã đọc cho phu nhân nghe).",
    "Mẫu 「V-てのこと」 biểu thị ý nghĩa 「chính vì có V nên mới có kết quả ngày hôm nay」. Thứ tự sắp xếp: Chủ ngữ vế kết quả 「実現したのは」 -> Cụm danh từ bổ nghĩa 「水面下の」 -> Chủ ngữ vế điều kiện 「外交努力gì」 -> Đi liền với cấu trúc nhấn mạnh nguyên nhân 「あってのことだ」.": "Cấu trúc 「V-てのこと」 khẳng định nguồn cội của một thành quả (chính vì có... nên mới). Việc 「実現したのは」 (có thể hiện thực hóa được) đều bắt nguồn từ một lý do ẩn sau. Nguyên cớ đó là 「水面下の外交努力」 (nỗ lực ngoại giao ngầm) kết nối chặt chẽ với 「あってのことだ」 (là nhờ có).",
    "Mẫu 「Vのでは」 được dùng để đưa ra phán đoán dẫn đến kết cục không tốt từ thực tế. Thứ tự sắp xếp: Định ngữ 「そんなに重要な」 bổ nghĩa cho danh từ chỉ nơi chốn 「記事で」 -> Cụm tân ngữ 「ミスを連発しているのでは」 -> Tân ngữ vế sau 「読者の信頼を」 -> Động từ chỉ kết quả xấu 「失ってしまいますよ」.": "Cấu trúc 「Vのでは」 nêu lên một thực trạng để từ đó dự báo điềm gở. Môi trường 「そんなに重要な記事で」 (trong một bài báo quan trọng đến thế) xảy ra hiện tượng 「ミスを連発しているのでは」 (nếu mà cứ liên tiếp phạm sai lầm). Hậu quả không tránh khỏi là 「読者の信頼を失ってしまいますよ」 (sẽ đánh mất luôn lòng tin của độc giả đấy)."
}

for i in range(22, 43):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 4 Batch 1.2 (parts 22-42) manually reviewed and rewritten successfully!")
