import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_5_jlpt_exam'

rewrites = {
    # part_101
    "Thể ý chí (Volitional form)のđộng từ nhóm 2 [寝る] là [寝よう] thể hiện ý định, quyết tâmのbản thân người nói (「tôi sẽ ngủ」). Thứ tự sắp xếp trạng từ chỉ thời gian [今夜] (tối nay), trạng từ mức độ [早く] (sớm) và cụm chỉ địa điểm [自分の部屋で] (ở phòng mình) đi trước động từ chính [寝よう] để bổ nghĩa cho hành động ngủ.": "Thể ý chí 「V-よう」 (quyết tâm làm...). Quyết định dứt khoát 「今夜は早く」 (tối nay nhất định phải đi sớm). Nơi nương náu 「自分の部屋で」 (tại căn phòng của chính mình). Hành động được chốt hạ bằng 「寝よう」 (tôi sẽ đi ngủ).",
    "Thể ý chí [V-よう] ở dạng thông thường không có [よ] được dùng rộng rãi trong các khẩu hiệu, lời kêu gọi mọi người cùng thực hiện một việc tốt chung (「hãy tập trung」). Thứ tự: [お互いの] (của nhau) bổ nghĩa cho [勉強のために] (vì việc học) -> địa điểm [教室で] (ở lớp học) -> trạng từ [静かに] (một cách yên lặng) bổ nghĩa cho động từ hành động mang tính kêu gọi [集中しよう].": "Cấu trúc hô hào 「V-よう」 (chúng ta hãy cùng nhau...). Lý do chính đáng 「お互いの勉強のために」 (vì việc học tập của tất cả chúng ta). Ý thức tập thể 「教室で静かに」 (giữ trật tự trong lớp học). Và cùng nhau 「集中しよう」 (hãy tập trung cao độ nào).",
    "Cấu trúc [V-てもらおう] thể hiện ý định nhận được hành động có lợi từ ai đó (「hãy nhờ/nhận sự giúp đỡ」). Trong đó, người thực hiện hành động gốc được chỉ định bằng trợ từ [に] (先生に - nhờ thầy cô). Thứ tự: trạng từ thời gian [後で] (lát nữa) -> từ bổ nghĩa [担任の] (chủ nhiệm) đi kèm danh từ chỉ đối tượng [先生に] -> phó từ [特別に] (đặc biệt) nhấn mạnh tính chấtのhành động nhận [貸してもらおう] (nhờ cho mượn).": "Cấu trúc nhờ vả ân huệ 「V-てもらう」 (nhận được sự giúp đỡ từ). Lên kế hoạch 「後で担任の」 (chút nữa đối với giáo viên chủ nhiệm). Hướng đến đối tượng 「先生に特別に」 (phải nhắm nhe xin xỏ thầy ấy một đặc ân). Đó là 「貸してもらおう」 (sẽ nhờ thầy ấy cho mượn).",
    "Trong văn viết trang trọng hoặc học thuật, thể ý chíのđộng từ (đặc biệt là [ある] chuyển thành [あろう]) được dùng để thể hiện sự suy đoán, ước lượngのngười viết (「chắc là có」). Thứ tự: tính từ bổ nghĩa [この高度な] (tiên tiến này) đi kèm danh từ mục tiêu [実験には] (đối với cuộc thí nghiệm) -> cụm bổ nghĩa [未だ不確定な] (vẫn chưa xác định) bổ nghĩa cho danh từ chỉ chủ thể [要素も多々] (cũng có nhiều yếu tố) -> từ chỉ khả năng [あろう].": "Cấu trúc phỏng đoán trang trọng 「～あろう」 (chắc hẳn là sẽ có). Đánh giá tính chất 「この高度な実験には」 (đối với một cuộc thí nghiệm mang tầm cỡ cao siêu thế này). Điểm mù 「未だ不確定な要素も多々」 (những yếu tố chứa đầy sự rủi ro bất định ngập tràn). Khẳng định chắc nịch 「あろう」 (là điều hiển nhiên phải có).",
    "Cấu trúc [V-ようか] dùng khi người nói chủ động đề xuất làm một việc gì đó giúp cho người nghe (「để tôi làm cho nhé」). Thứ tự: Cụm bổ nghĩa [数学が] (môn toán) bổ nghĩa cho chủ từ [得意な私が] (tôi, người giỏi toán) -> trạng ngữ thay thế [あなたの代わりに] (thay cho bạn) -> từ chỉ vị trí [ここで] (tại đây) -> động từ chia thể ý chí hỏi [解こうか] (giải giúp nhé).": "Cấu trúc chủ động ngỏ lời 「V-ようか」 (để tôi... giúp cho nhé). Tự đề cao năng lực 「数学が得意な私が」 (với một đứa là cao thủ môn toán như tôi). Ra tay nghĩa hiệp 「あなたの代わりにここで」 (sẽ thay mặt cho cậu ngay tại nơi này). Ra tay 「解こうか」 (giải quyết nó giúp nhé).",
    "Cấu trúc [V-てもらおうか] thể hiện ý muốn nhẹ nhàng nhờ vả ai đó thực hiện hành động cho mình (「có lẽ nên nhờ... làm giúp」). Người thực hiện hành động gốc đi với trợ từ [に] (先生に). Thứ tự: Cụm định ngữ [理科の] (môn tự nhiên) bổ nghĩa cho [先生に] -> phó từ chỉ tần suất [もう一度] (một lần nữa) -> trạng từ chỉ cách thức [分かりやすく] (một cách dễ hiểu) -> động từ nhận hành vi [説明してもらおうか] (nhờ giải thích giúp).": "Cấu trúc xin xỏ ân huệ 「V-てもらおうか」 (hay là nhờ... làm giúp nhỉ). Mục tiêu nhắm đến 「理科の先生に」 (hướng tới thầy giáo bộ môn khoa học tự nhiên). Yêu cầu bổ sung 「もう一度分かりやすく」 (một cách rành rọt và dễ hiểu thêm một lần nữa). Thăm dò ý định 「説明してもらおうか」 (hay là mình cứ mặt dày nhờ thầy giảng lại xem sao).",
    "Cấu trúc [V-ようが] mang nghĩa 「cho dù có làm gì đi nữa...」 (bất chấp tác động vế trước). Động từ [批判する] (phê bình/chỉ trích) chuyển sang thể ý chí [批判しよう] kết hợp với [が]. Thứ tự: địa điểm [学会で] (tại hội thảo) -> nghi vấn từ bổ nghĩa [何と] (như thế nào) -> vế nhượng bộ [批判しようが] -> tân ngữ vế sau [独自の理論を] (lý thuyết độc lập) -> hành động chính [追求し続ける] (tiếp tục theo đuổi).": "Cấu trúc bất chấp dị nghị 「V-ようが」 (cho dẫu có bị... đi chăng nữa). Dư luận chĩa mũi dùi 「学会で何と批判しようが」 (dẫu cho có bị thiên hạ trong giới học thuật ném đá bỉ bôi ra sao đi chăng nữa). Vẫn ngẩng cao đầu 「独自の理論を」 (lý thuyết độc nhất vô nhị của bản thân). Kiên định 「追求し続ける」 (vẫn sẽ tiếp tục dấn thân theo đuổi đến cùng).",
    "Cấu trúc [V-ようが V-まいが] mang nghĩa 「dù có làm V hay không làm V thì vế sau vẫn vậy」. Trong đó [認めよう] là thể ý chí và [認めまい] là thể ý chí phủ địnhのđộng từ nhóm 2 [認める] (thừa nhận). Thứ tự logic: hai vế đối lập [認めようが] và [認めまいが] bổ nghĩa nhượng bộ cho mệnh đề sau -> cụm danh từ làm chủ ngữ [この数式の真実性は] (tính chân thựcのcông thức này) đi kèm phó từ khẳng định [絶対に] (tuyệt đối) bổ nghĩa cho động từ phủ định cuối câu [揺るがない] (không lung lay).": "Cấu trúc thách thức sự phủ nhận 「V-ようがV-まいが」 (có làm V hay đéo làm V thì kết quả vẫn thế). Thái độ kiêu ngạo 「認めようが認めまいが」 (mặc xác cho các người có chịu mở miệng thừa nhận hay không). Chân lý vững như bàn thạch 「この数式の真実性は絶対に」 (thì tính chân thực của cái mớ công thức này cũng tuyệt đối). Không mảy may 「揺るがない」 (bị lung lay một ly một lai nào cả).",

    # part_104
    "Thứ tự đúng ngữ pháp N5: Chủ ngữ 「学生は」 (học sinh) -> trạng từ chỉ thời gian 「放課後」 (sau giờ học) -> danh từ chỉ địa điểm kèm trợ từ chỉ hướng chuyển động 「図書館に」 (đến thư viện) -> trạng từ chỉ tần suất 「よく」 (thường xuyên) -> mục đích chuyển động 「勉強しに」 (để học) -> động từ chuyển động kết thúc câu 「行きます」 (đi).": "Cấu trúc mục đích di chuyển 「V-stemに + động từ di chuyển」 (đi đến đâu để làm cái gì). Hoạt động thường nhật 「学生は放課後、図書館によく」 (bọn học sinh thì cứ hễ tan tầm sau giờ học là y như rằng thường xuyên ghé thư viện). Mục đích là 「勉強しに行きます」 (để đâm đầu vào việc ôn luyện bài vở).",

    # part_78
    "Phân tích cấu trúc câu hỏi xác nhận với tính từ đuôi -na ở trình độ N4. Trạng từ 「本当に」 (thật sự) bổ nghĩa cho mức độ 「それほど」 (đến mức đó). Cả cụm này bổ nghĩa cho tính từ đuôi -na 「簡単」 (đơn giản). Khi kết hợp với đuôi câu giải thích/xác nhận 「の」, tính từ đuôi -na phải đi kèm với 「な」, tạo thành cụm 「簡単なのですか」 (hoặc văn nói lịch sự là 「簡単なのですか」). Ở đây 「簡単」 (Chunk 3) kết hợp với 「なの」 (Chunk 4) tạo thành 「簡単なの」, theo sau bởi Suffix 「ですか」. Thứ tự logic là Chunks 1-2-3-4.": "Cấu trúc xoáy sâu vấn đề 「～なのですか」 (thật sự là... ư). Sự hoài nghi dâng cao 「本当にそれほど」 (liệu rằng nó có thực sự đến cái mức độ đó). Câu hỏi chất vấn 「簡単なのですか」 (có thật là nó lại đơn giản trơn tru đến thế không).",
    "Ngữ pháp 「～の」 ở cuối câu biểu thị sự giải thích nhẹ nhàng hoặc tường thuật sự việcのbản thân (thường dùng trong văn phong thân mật, nữ tính hoặc trẻ em nói với người lớn). Trợ từ 「が」 đi sau danh từ 「パソコン」 chỉ chủ ngữ thực hiện hành động. Trạng từ 「どうしても」 (dù thế nào cũng...) đi kèm thể phủ định để nhấn mạnh sự bất lực. Động từ nhóm 3 「起動する」 chia sang thể phủ định ngắn thành 「起動しない」 (không khởi động). Cuối cùng kết hợp với vĩ tố 「の」 ở phần Suffix. Thứ tự sắp xếp tự nhiên là Chunks 1-2-3-4.": "Cấu trúc than vãn bất lực 「どうしても～ないの」 (cố mấy cũng đéo được đâu). Tình thế vô phương 「パソコンがどうしても起動しないの」 (cái máy tính giẻ rách này có đập có gõ kiểu gì thì nó cũng chả chịu lên nguồn cho).",
    "Mẫu câu 「V-ない + の」 được dùng để đưa ra một mệnh lệnh hoặc lời khuyên bảo nhẹ nhàng nhưng dứt khoát (thường dùng bởi người bề trên như giáo viên hoặc cha mẹ). Đầu tiên, danh từ 「隣」 kết hợp với 「人」 qua trợ từ 「の」 tạo thành 「隣の人」 (người bên cạnh), tiếp tục liên kết với danh từ 「答案」 (bài làm) bằng trợ từ 「の」 thứ hai để xác định quyền sở hữu 「隣の人の答案」 (bài làmのngười bên cạnh). Trợ từ 「を」 chỉ đối tượngのhành động 「見ない」 (không nhìn). Cuối cùng kết hợp với 「の」 ở Suffix tạo thành câu mệnh lệnh nhẹ. Thứ tự đúng là Chunks 1-2-3-4.": "Cấu trúc răn đe ngầm 「V-ないの」 (bảo là không cơ mà). Chỉ tay thẳng mặt 「隣の人の答案を見ないの」 (đã bảo là cấm có được ti hí liếc ngang liếc dọc bài thi của đứa bên cạnh cơ mà).",
    "Cấu trúc biểu thị quan hệ nhân quả khách quan 「だから～のだ」 (chính vì thế mà... giải thích kết luận dựa trên bằng chứng thực tế). Liên từ chỉ nguyên nhân 「だから」 đứng đầu câu kết luận. Trạng từ chỉ thời gian và trạng thái 「当時すでに」 (vào thời đó đã) bổ nghĩa cho động từ vế sau. Chủ ngữ 「稲作が」 (việc trồng lúa nước) đi kèm động từ trạng thái quá khứ tiếp diễn 「普及していた」 (đã phổ biến). Động từ này kết hợp với 「のだ」 ở phần Suffix để hoàn tất cấu trúc giải thích lập luận. Thứ tự đúng là Chunks 1-2-3-4.": "Cấu trúc bóc trần chân lý 「だから～のだ」 (chính vì thế cho nên mới...). Vén màn sự thật 「だから当時すでに稲作が普及していたのだ」 (hèn chi mà vào cái thời kỳ xa xưa ấy, kỹ thuật canh tác lúa nước đã thịnh hành và lan rộng đến vậy).",
    "Ngữ pháp 「V-るのだった」 thể hiện sự hối tiếc muộn màngのngười nói về một việc đáng lẽ nên làm trong quá khứ (「giá mà...」). Về mặt cú pháp, trạng từ chỉ thời điểm bắt đầu 「最初から」 (ngay từ đầu) đứng trước để bổ nghĩa cho hành động. Danh từ tân ngữ 「教科書を」 (sách giáo khoa) đi kèm trạng từ cách thức 「丁寧に」 (một cách cẩn thận). Cả hai bổ nghĩa trực tiếp cho động từ thể từ điển 「読み直しておく」 (đọc lại sẵn/chuẩn bị trước). Động từ này đi liền với cấu trúc hối tiếc 「のだった」 ở phần Suffix. Thứ tự đúng là Chunks 1-2-3-4.": "Cấu trúc giá như 「V-ておくのだった」 (biết thế ngay từ đầu đã... cho xong). Cơn hối hận muộn màng 「最初から教科書を丁寧に読み直しておくのだった」 (giá mà tao đừng có chủ quan, ngay từ đầu cứ cắn răng moi quyển sách giáo khoa ra mà nhai lại kỹ càng từng chữ thì có phải êm chuyện rồi không).",
    "Ngữ pháp 「～のだろう」 biểu thị sự suy đoán, ước lượngのngười nói dựa trên các căn cứ hay hiện tượng khách quan quan sát được. Cụm danh từ sở hữu 「世界各地の」 (của các nơi trên thế giới) bổ nghĩa cho chủ ngữ 「生態系が」 (hệ sinh thái). Trạng từ mức độ 「急激に」 (một cách nhanh chóng) bổ nghĩa cho động từ diễn tả trạng thái đang diễn ra 「変化している」 (đang biến đổi). Động từ này đi trực tiếp với đuôi phán đoán 「のだろう」 ở phần Suffix. Thứ tự logic duy nhất là Chunks 1-2-3-4.": "Cấu trúc âu lo phấp phỏng 「～のだろう」 (liệu rằng có phải chăng...). Sự mục nát lan rộng 「世界各地の生態系が急激に変化しているのだろう」 (chắc hẳn là chuỗi hệ sinh thái trên toàn cầu này đang phải gồng mình chịu đựng những biến đổi khốc liệt càn quét qua rồi).",

    # part_82
    "Hệ thống ngữ pháp N4: Mẫu câu [N/Adj-na + ならいいのに] thể hiện mong ước, ao ước một điều trái thực tế hoặc kỳ vọng. Thứ tự logic: Trạng ngữ thời gian/chủ đề [明日の試験] (kỳ thi ngày mai) -> trạng từ mức độ [もっと] (hơn nữa) bổ nghĩa cho tính từ [簡単な] (dễ) -> kết hợp với danh từ [問題なら] (nếu là đề thi) -> đuôi ao ước [いいのに] (thì tốt biết mấy)。": "Cấu trúc ước ao mộng tưởng 「～ならいいのに」 (giá mà... thì đời đã nở hoa). Lời khẩn cầu trong vô vọng 「明日の試験、もっと簡単な問題ならいいのに」 (ước gì cái đề thi ngày mai nó nhẹ nhàng dễ thở hơn thì phước đức biết mấy).",
    "Hệ thống ngữ pháp N4: Mẫu câu [V-ておけばよかった] thể hiện sự hối hận hoặc nuối tiếc vì đã không làm một chuẩn bị trước. Thứ tự logic: Mệnh đề chỉ lý do [今回の試験は難しかったから] (vì kỳ thi lần này khó) -> cụm trạng từ chỉ thời gian và mức độ [事前にもっと] (trước đó nhiều hơn nữa) -> động từ chia thể Te-oku kết hợp đuôi nuối tiếc [復習しておけばよかった] (giá mà đã ôn tập sẵn)。": "Cấu trúc tiếc hùi hụi 「V-ておけばよかった」 (biết thế đã... thì có phải hơn không). Cái tát từ thực tại 「今回の試験は難しかったから」 (vì cái bài thi đợt này nó khoai quá mạng). Bài học rút ra 「事前にもっと復習しておけばよかった」 (biết thế này đã cày cuốc ôn tập kỹ lưỡng hơn trước đó cho rồi).",
    "Hệ thống ngữ pháp N4: Cấu trúc [数量詞 + ばかり] chỉ lượng ước chừng (khoảng). Thứ tự: Cụm mục đích [この論文を完成させるために] (để hoàn thành luận văn này) -> cụm chỉ thời gian ước lượng [三日間ばかり] (khoảng 3 ngày) -> địa điểm [研究室に] (ở phòng nghiên cứu) -> động từ chính [こもった] (đã thu mình/nhốt mình)。": "Cấu trúc áng chừng khoảng cách 「数量詞 + ばかり」 (tầm sấp sỉ cỡ...). Sự đánh đổi 「この論文を完成させるために」 (để đổi lấy sự hoàn tất của cái luận án này). Sự biệt giam tự nguyện 「三日間ばかり研究室にこもった」 (tôi đã phải tự nhốt mình cày ải trong phòng nghiên cứu ròng rã cỡ chừng ba ngày trời).",
    "Hệ thống ngữ pháp N4: Cấu trúc [N + ばかりで] mang nghĩa 「chỉ toàn là N (tiêu cực)」. Thứ tự logic: Chủ đề câu [最近の講義は] (các bài giảng gần đây) -> tính từ [難しい] (khó) bổ nghĩa cho cụm danh từ [理論ばかりで] (chỉ toàn lý thuyết) -> cụm mục đích [理解するのに] (cho việc thấu hiểu) -> vị ngữ chỉ kết quả [時間がかかる] (tốn thời gian)。": "Cấu trúc ám ảnh triền miên 「Nばかり」 (toàn rặt những là...). Nỗi niềm ngán ngẩm 「最近の講義は難しい理論ばかりで」 (dạo này mấy cái tiết học giảng đường nó toàn nhồi sọ đặc sệt mớ mớ lý thuyết khô khan hóc búa). Hậu quả là 「理解するのに時間がかかる」 (ngốn đống thời gian mới ngấm nổi vài chữ vào đầu).",
    "Hệ thống ngữ pháp N4: Cấu trúc [V-てばかりいる] chỉ một hành động lặp đi lặp lại nhiều tới mức đáng trách. Thứ tự logic: Chủ ngữ [彼は] (anh ấy) -> mệnh đề tương phản [試験の前なのに] (dù trước kỳ thi) -> trạng thái phủ định [勉強せずに] (không chịu học hành) -> đối tượng [ゲームを] (chơi game) kết hợp với động từ chia thể Te-ite [してばかりいる] (chỉ toàn chơi)。": "Cấu trúc ngứa mắt 「V-てばかりいる」 (toàn làm cái trò... chả được tích sự gì). Thái độ lồi lõm 「彼は試験の前なのに勉強せずに」 (thi cử đến đít rồi mà thằng chả còn nhơn nhơn đéo thèm học hành gì sất). Sự tha hóa 「ゲームをしてばかりいる」 (suốt ngày chỉ cắm mặt vào dăm ba cái trò điện tử).",
    "Hệ thống ngữ pháp N2: Cấu trúc [Nばかりは] nhấn mạnh sự việc này là đặc biệt/ngoại lệ không thể xảy ra. Thứ tự logic: Cụm danh từ chủ đề [レポートの提出期限の延長ばかりは] (riêng việc gia hạn nộp báo cáo) -> chủ ngữ thực hiện [厳しい教授も] (ngay cả vị giáo sư nghiêm khắc) -> vị ngữ phủ định phán đoán [認めてくれないだろう] (chắc cũng sẽ không chấp nhận)。": "Cấu trúc độc tôn vô nhị 「Nばかりは」 (riêng cái... này thì đéo). Giới hạn cuối cùng 「レポートの提出期限の延長ばかりは」 (riêng cái khoản lầy lội xin xỏ lùi deadline nộp báo cáo ấy à). Khẳng định cái kết 「厳しい教授も認めてくれないだろう」 (thì đến bố của ông giáo sư thét ra lửa ấy cũng đéo bao giờ có chuyện gật đầu cho qua đâu).",
    "Hệ thống ngữ pháp N4: Cấu trúc [V-たばかりだ] chỉ hành động vừa mới xảy ra theo cảm nhận chủ quan. Thứ tự logic: Chủ ngữ [私は] (tôi) -> mốc thời gian gần [先週この大学に] (vào trường đại học này tuần trước) -> động từ chia quá khứ kết hợp cấu trúc [入学したばかりで] (vừa mới nhập học) -> kết quả kéo theo ở hiện tại [学内の施設がよくわからない] (vẫn chưa nắm rõ cơ sở vật chất trong trường)。": "Cấu trúc chân ướt chân ráo 「V-たばかり」 (vừa mới chớm...). Sự bỡ ngỡ của kẻ ngoại đạo 「私は先週この大学に入学したばかりで」 (chẳng là thân tôi đây cũng chỉ vừa mới mon men nhập học vào cái trường này từ hồi tuần trước thôi nên là). Sự yếu kém 「学内の施設がよくわからない」 (ba cái ngóc ngách cơ sở vật chất ở trong này tôi làm quái gì đã rành rọt).",
    "Hệ thống ngữ pháp N2: Cấu trúc [V-るばかりだ] chỉ một xu hướng biến đổi liên tục theo một chiều (thường là chiều hướng xấu). Thứ tự logic: Nguyên nhân [景気の後退によって] (do suy thoái kinh tế) -> danh từ làm chủ đề [大学の研究予算は] (ngân sách nghiên cứuのtrường đại học) -> trạng từ tần suất/biến đổi [年々] (hàng năm) -> động từ thể bị động kết hợp cấu trúc [削減されるばかりだ] (chỉ toàn bị cắt giảm)。": "Cấu trúc tuột dốc không phanh 「V-るばかりだ」 (cứ ngày một... tồi tệ hơn). Bức tranh ảm đạm 「景気の後退によって大学の研究予算は」 (bị làn sóng suy thoái kinh tế bóp nghẹt, cái ngân sách đổ vào nghiên cứu của trường giờ đây). Sự lụn bại 「年々削減されるばかりだ」 (năm nào năm nấy cũng cứ thế mà teo tóp, hao hụt dần đi).",
    "Hệ thống ngữ pháp N2: Cấu trúc [V-るばかりだ] chỉ trạng thái mọi chuẩn bị đã hoàn tất, chỉ còn chờ thực hiện bước cuối cùng. Thứ tự logic: Bối cảnh [論文の執筆が終わり] (viết xong luận văn) -> trạng từ [あとは] (còn lại) -> đối tượng tiếp nhận [指導教授に] (lên giáo sư hướng dẫn) -> hành động phụ [確認を求めて] (xin xác nhận) -> hành động cuối cùng [提出するばかりだ] (chỉ còn chờ nộp nữa thôi)。": "Cấu trúc dọn sẵn mâm chờ ăn 「V-るばかりだ」 (chỉ còn độc mỗi bước... là xong xuôi). Giai đoạn bung lụa 「論文の執筆が終わり、あとは」 (mớ luận án đau đầu nhức óc cuối cùng cũng nặn xong rồi, giờ phần việc còn lại cũng chỉ là). Chốt sổ 「指導教授に確認を求めて提出するばかりだ」 (mang lên réo ông giáo sư hướng dẫn confirm một phát rồi ném cái xạch nộp là xong).",
    "Hệ thống ngữ pháp N2: Cấu trúc [V-るばかりのN] thể hiện mức độ cực kỳ caoのtrạng thái (đến mức...). Trình tự logic: Chủ đề [新しい図書館は] (thư viện mới) -> trạng từ [思わず] (bất giác) bổ nghĩa cho cụm [ため息が出るばかりの] (đến mức phát ra tiếng thở dài kinh ngạc) -> bổ nghĩa tiếp cho tính từ [美しい] (đẹp) -> danh語 chính [建築デザインだ] (thiết kế kiến trúc)。": "Cấu trúc choáng ngợp ngộp thở 「V-るばかりの」 (đến độ chỉ chực...). Tuyệt tác kiến trúc 「新しい図書館は」 (cái thư viện mới khánh thành ấy). Lộng lẫy đến ngỡ ngàng 「思わずため息が出るばかりの美しい建築デザインだ」 (đẹp đến mức người ta vô thức chỉ biết thốt lên những tiếng thở dài thảng thốt khi ngắm nhìn cái thiết kế kiến trúc đó).",
    "Hệ thống ngữ pháp N2: Cấu trúc [V-たばかりに] thể hiện nguyên nhân duy nhất dẫn đến kết quả xấu ngoài dự kiến. Trình tự logic: Bối cảnh [試験の簡単な記述問題で] (ở câu tự luận dễのkỳ thi) -> hành động sai sót [誤字を書いたばかりに] (chỉ vì viết sai một chữ) -> đối tượng bị ảnh hưởng [満点を] (điểm tuyệt đối) -> kết quả tiếc nuối [逃してしまった] (đã bỏ lỡ mất)。": "Cấu trúc sai một ly đi một dặm 「V-たばかりに」 (chỉ tại cái tội lỡ... mà ra nông nỗi). Trượt chân vấp ngã đau đớn 「試験の簡単な記述問題で誤字を書いたばかりに」 (cay đắng thay, chỉ vì lỡ vẩy bút ngu ngốc sai chính tả ở một cái câu tự luận phạch tạch vớ vẩn rành rành ra đấy). Mà cái kết là 「満点を逃してしまった」 (thế là đi tong cmn luôn cái con điểm tuyệt đối không tì vết).",
    "Hệ thống ngữ pháp N1: Cấu trúc [V-てばかりもいられない] nghĩa là không thể cứ giữ mãi một trạng thái tiêu cực mà phải thay đổi để hành động. Trình tự logic: Đối tượng tác động [不合格という結果に] (với kết quả trượt) -> hành động không thể tiếp tục kéo dài [落ち込んでばかりもいられないので] (vì không thể cứ mãi u sầu) -> cụm bổ nghĩa hướng tới [次の試験への] (đối với kỳ thi tiếp theo) -> hành động chủ động [対策を始めよう] (hãy bắt đầu lên phương án đối phó)。": "Cấu trúc sốc lại tinh thần 「V-てばかりもいられない」 (đéo thể cứ mãi dặt dẹo... thế này được). Kéo bản thân ra khỏi vũng lầy 「不合格という結果に落ち込んでばかりもいられないので」 (mặc dù cầm cái quả đắng báo trượt rớt đài trên tay, nhưng đéo thể cứ chôn vùi bản thân ủ rũ rên rỉ than vãn mãi được). Phải đứng lên 「次の試験への対策を始めよう」 (xốc lại tinh thần, xắn tay áo lên mà cày cuốc chuẩn bị phục thù cho cái kỳ thi đợt sau thôi).",
    "Hệ thống ngữ pháp N1: Cấu trúc [とばかりはいえない] thể hiện sự phủ định một phần (không hẳn lúc nào cũng..., không thể khẳng định hoàn toàn là...). Trình tự logic: Mệnh đề giả định nhượng bộ [高名な教授の論文だからといって] (dẫu nói là luận vănのgiáo sư nổi tiếng) -> chủ ngữ vế sau [その内容が] (nội dungのnó) -> tính từ [常に正しい] (luôn luôn đúng) -> cụm phủ định một phần ở cuối câu [とばかりはいえない] (thì cũng không hẳn thế)。": "Cấu trúc phản biện rạch ròi 「～とばかりはいえない」 (không hẳn cứ là... thì sẽ thế đâu). Phá bỏ định kiến thần thánh hóa 「高名な教授の論文だからといって」 (đừng có hễ thấy mác bài luận của mấy tay giáo sư tai to mặt lớn là cứ tưởng bở). Đập tan ảo tưởng 「その内容が常に正しいとばかりはいえない」 (đâu phải mớ chữ nghĩa trong đó lúc nào cũng là kim chỉ nam chân lý chính xác tuyệt đối đâu).",

    # part_85
    "Cấu trúc「一通りではない」nghĩa là 「không hề tầm thường/cực kỳ lớn」. Trình tự logic: Chủ ngữ là cụm danh từ「プレッシャーの大きさ là」(độ lớnのáp lực) được bổ nghĩa bởi mệnh đề phụ「挑む受験生が精神的に抱える」(thí sinh thử sức... gánh chịu về mặt tinh thần). Thành phần định ngữ đứng trước danh từ bổ nghĩa, và cuối cùng kết hợp với vị ngữ phủ định「一通りではない」để nhấn mạnh mức độ khủng khiếpのáp lực thi cử.": "Cấu trúc kinh hoàng vắt kiệt 「一通りではない」 (không phải dạng vừa, đéo thể đùa được). Cái sức ép nghẹt thở 「挑む受験生が精神的に抱えるプレッシャーの大きさは」 (cái sức ép tâm lý khủng khiếp đè nặng lên vai của những lứa sĩ tử xông pha trận mạc thi cử). Nó thực sự 「一通りではない」 (không phải là cái thứ vớ vẩn để mà có thể lấy ra làm trò đùa bỡn cợt được đâu).",
    "Mẫu「～ふう」(dạng/vẻ) chỉ dáng vẻ, trạng thái bề ngoài. Thường đi kèm động từ thể ている thành「～ているふう」(vẻ như đang...). Trình tự logic: Phó từ phủ định「少しも」(một chút cũng không) đi kèm bổ nghĩa cho cấu trúc phủ định ở cuối câu là「ふうではなかった」(không có vẻ gì là). Do đó động từ「緊張している」được đặt ngay trước「ふう」để tạo thành cụm bổ nghĩa.": "Cấu trúc giả tạo ngụy trang 「～ふう」 (có cái điệu bộ ra vẻ...). Cố gắng diễn sâu 「少しも緊張しているふうではなかった」 (trông điệu bộ chả có lấy nửa phần nào là toát lên cái vẻ đang lo âu căng thẳng sất).",
    "Cấu trúc「～ふしがある」nghĩa là 「có dấu hiệu/có điểm đáng ngờ/có chỗ cho thấy...」. Nó thường đi liền sau một mệnh đề bổ nghĩa định ngữ thể thông thường (hoặc kết hợp với「だけの」như trong câu: 「chỉ là ráp công thức học vẹt」). Trình tự logic: hành động học vẹt「丸暗記して」dẫn đến việc áp dụng「当てはめた」, giới hạn bởi「だけの」rồi trực tiếp bổ nghĩa cho danh từ「ふし」.": "Cấu trúc lật tẩy bí mật 「～ふしがある」 (nói thế chứ ngầm ra có mùi...). Bóc phốt sự lấp liếm 「丸暗記して当てはめただけのふしがある」 (đọc qua là ngửi thấy ngay cái mùi tanh tưởi của cái lũ chỉ giỏi bốc nguyên mớ kiến thức học vẹt rồi nhắm mắt nhắm mũi mà ốp một cách rập khuôn).",
    "Danh từ「ぶん（分）」chỉ phần, suất dành cho một đối tượng cụ thể. Cấu trúc「Nのぶん」nghĩa là 「phầnのN」. Ở đây, danh từ sở hữu「私」(tôi) kết hợp với「のぶん」và đi kèm trợ từ sở hữu「の」để bổ nghĩa cho danh từ tiếp theo「プリント」(tài liệu in). Trình tự logic: 「私のぶん」(phầnのtôi) -> 「私のぶんのプリント」(tài liệu thuộc phầnのtôi) làm chủ ngữ cho vị ngữ「足りなかった」(không đủ).": "Cấu trúc định mức thân phận 「Nのぶん」 (cái phần của...). Đẩy con người ta ra rìa 「私のぶんのプリントが足りなかった」 (mẹ kiếp, đến cái tờ tài liệu phô tô phát phần cho riêng tôi mà cũng đéo lo lo liệu cho nổi).",
    "Cấu trúc「V-ているぶんには」nghĩa là 「nếu chỉ trong phạm vi/nếu chỉ dừng lại ở việc V thì...」. Ở đây, động từ thể tiếp diễn「読んでいる」(đang đọc) bổ nghĩa cho「ぶんには」. Trình tự logic: việc 「đọc sách tham khảo」 tạo ra nhận định mang tính chủ quan ở vế trước「容易に思えるが」(tuy cảm thấy dễ dàng), đối lập hoàn toàn với thực tế khốc liệt ở vế sau「実際の試験は甘くない」.": "Cấu trúc thu hẹp thế giới quan 「V-ているぶんには」 (nếu chỉ quẩn quanh trong phạm vi... thì). Sự kiêu ngạo ảo tưởng sức mạnh 「参考書を読んでいるぶんには容易に思えるが」 (mới ngồi nhà dở vài trang sách tham khảo đọc chữ lướt ván qua loa thì thấy ối dồi ôi sao mà dễ nhai thế cơ chứ). Đập nát mộng tưởng 「実際の試験は甘くない」 (cơ mà vác xác ra chiến trường thi thật thì đừng có hòng mà mơ một cái kết màu hồng).",

    # part_91
    "「[午後五時]」 là danh từ chỉ mốc thời gian kết hợp với 「[まで]」 chỉ giới hạn thời gian (đến 5 giờ chiều). 「[講義を]」 là tân ngữのhành động bổ trợ 「[継続して]」 (liên tục) và động từ chính 「[行います]」 (tiến hành). Thứ tự đúng: Mốc thời gian + まで + Tân ngữ + Động từ.": "Trợ từ ghim chặt mốc thời gian 「まで」 (đến tận...). Giới hạn được vạch ra 「午後五時まで講義を」 (phải nhai cho hết cái bài giảng này cho tới tận năm giờ chiều). Hành động đày đọa 「継続して行います」 (tiếp tục đày ải).",
    "「[学生ばかりか]」 mang nghĩa 「không chỉ học sinh」. 「[教授まで]」 (ngay cả giáo sư) thể hiện mức độ cực đoan thông qua cấu trúc [Danh từ + まで]. Thứ tự logic: N1 + ばかりか + N2 + まで + Động từ/Trạng thái (議論に参加している).": "Cấu trúc bành trướng quy mô 「Nばかりか...まで」 (không những cái loại tép riu mà còn cả cái bọn...). Vượt qua mọi ranh giới 「学生ばかりか教授まで」 (chẳng chừa một mống nào, từ bọn tép riu sinh viên quèn cho tới mấy ông lão làng giáo sư). Sôi sục máu chiến 「議論に参加している」 (đều xắn tay áo hăm hở nhảy vào chảo lửa tranh luận).",
    "「[論文を]」 (luận văn) là tân ngữ, 「[自動で]」 (một cách tự động) là trạng từ bổ nghĩa cho khả năng 「[翻訳できる]」 (có thể dịch). Cấu trúc 「[V-るまでになる]」 diễn tả sự biến đổi trạng thái đạt đến mức độ nào đó. Thứ tự đúng: Tân ngữ + Trạng từ + V-khả năng + までに + なった。": "Cấu trúc chuyển mình leo rank 「V-るまでになる」 (vươn tới cái đẳng cấp có thể...). Tiến hóa vượt bậc 「論文を自動で翻訳できるまでに」 (đã tiến hóa bá đạo đến cái đẳng cấp có thể tự động bóp gọn và dịch tuốt tuồn tuột mấy cái bài luận văn). Khẳng định vị thế 「なった」 (đã thành tựu được như vậy rồi).",
    "「[教授に]」 (đối với giáo sư) là đối tượngのhành động 「[質問する]」 (hỏi), được bổ nghĩa bằng trạng từ 「[直接]」 (trực tiếp). Cấu trúc 「[V-るまでもない]」 biểu thị ý nghĩa 「không cần thiết phải làm gì vì đã quá rõ ràng hoặc đơn giản」. Thứ tự: Đối tượng + Trạng từ + V-る + までもない.": "Cấu trúc khinh khỉnh ngạo mạn 「V-るまでもない」 (cái ngữ đó đéo thèm nhọc công...). Sự dư thừa thảm hại 「教授に直接質問するまでもない」 (nói toẹt ra là đéo cần phải làm cái trò mèo trực tiếp đi vác mặt tới hỏi mấy ông giáo sư làm cái mẹ gì cho phí sức).",
    "「[カンニングという]」 (gọi là gian lận) định nghĩa cho 「[不正行為]」 (hành vi gian lận). Cấu trúc 「[N + までして]」 mang nghĩa làm đến mức cực đoan như thế. 「[高い点数を]」 làm tân ngữ cho động từ muốn nhận 「[取りたい]」. Thứ tự: Định ngữ + N + までして + Tính từ + N (tân ngữ) + V-tai.": "Cấu trúc phá vỡ ranh giới đạo lý 「Nまでして」 (tới cái nước bán rẻ lương tâm là... thì). Bán linh hồn cho quỷ dữ 「カンニングという不正行為までして」 (có cắn rứt lương tâm, chà đạp lên đạo lý tới mức phải đi làm cái trò bẩn thỉu như gian lận đi chăng nữa). Dã tâm rực cháy 「高い点数を取りたい」 (thì khao khát duy nhất cũng chỉ là nuốt trọn được mớ điểm cao chót vót).",
    "Cấu trúc 「[V-るまでのことだ]」 mang ý nghĩa 「chỉ còn cách làm V (thể hiện thái độ quyết tâm hoặc không bận tâm, chỉ cần thế là xong)」. 「[他のスポンサーを]」 (nhà tài trợ khác) là tân ngữの「[捜す]」 (tìm kiếm). Thứ tự: Định ngữ + Danh từ + を + V-る + までのことだ.": "Cấu trúc cắn răng làm bừa 「V-るまでのことだ」 (cùng lắm thì chơi tất tay...). Đường cùng sinh biến 「他のスポンサーを捜すまでのことだ」 (nếu bị dồn vào chân tường, thì đéo có mợ chợ vẫn đông, bố mày vác mặt đi lùng sục bới móc cho ra thằng tài trợ khác chớ sao).",
    "「[データに基づいて]」 (dựa trên dữ liệu) bổ nghĩa cho hành động 「[報告した]」 (đã báo cáo) với tân ngữ là 「[事実を]」 (sự thật). Cấu trúc 「[V-たまでだ]」 mang ý nghĩa 「chỉ đơn giản là đã làm V (không có ý đồ gì khác)」. Thứ tự: Trạng ngữ chỉ cơ sở + Tân ngữ + V-た + までだ.": "Cấu trúc ngây thơ vô tội 「V-たまでだ」 (thì tôi cũng chỉ làm cái việc... mà thôi). Rũ bỏ trách nhiệm 「データに基づいて事実を報告したまでだ」 (xin lỗi nhé, tôi đây cũng chỉ là cái thằng đui mù răm rắp làm theo dăm ba cái con số mớ dữ liệu mà nôn ra sự thật thôi chứ có biết cái đéo gì đâu).",
    "「[実証できなければ]」 (nếu không thể chứng minh thực tế) là điều kiện giả định phủ định khả năng. Cấu trúc 「[それまでだ]」 mang nghĩa 「đến đó là hết, coi như vô nghĩa/chấm hết」. Thứ tự: V-điều kiện + それ + まで + だ.": "Cấu trúc án tử hình 「それまでだ」 (thế là chấm mút, đứt cước mẹ nó rồi). Kết cục bẽ bàng 「実証できなければそれまでだ」 (còn nếu mà không móc ra được bằng chứng thực tế chứng minh cho lời mình sủa, thì coi như vứt xó, dẹp tiệm hết).",
    "Cấu trúc 「[V-ないまでも]」 mang ý nghĩa 「dù không đến mức làm được V, nhưng ít nhất cũng phải...」. 「[解決できないまでも]」 đi sau tân ngữ 「[課題`を]」. Vế sau đưa ra giải pháp tối thiểu 「[具体的な対案を]」 làm tân ngữ cho 「[提示すべきだ]」. Thứ tự: V-không + ないまでも + Định ngữ + Tân ngữ + V-shubeki.": "Cấu trúc hạ tiêu chuẩn cầu xin 「V-ないまでも」 (dẫu đéo đòi hỏi đạt tới ngưỡng... thì ít ra cũng). Sự nhượng bộ tối thiểu 「課題を解決できないまでも」 (thôi thì không mong mỏi nặn ra được phép màu xử đẹp triệt để cái mớ bòng bong này đi). Vẫn gượng ép yêu cầu 「具体的な対案を提示すべきだ」 (cơ mà ít ra làm ơn làm phước phọt ra được cái đối sách gì cụ thể chút đi chứ).",
    "「[今月末]」 là mốc thời gian kết hợp với 「[までに]」 để chỉ hạn chót (trước cuối tháng này). 「[参考書を]」 (sách tham khảo) là tân ngữ, 「[図書館に]」 là địa điểm hướng tớiのhành động 「[返却してください]」 (hãy trả lại). Thứ tự: Thời gian + までに + Tân ngữ + Địa điểm + V-te kudasai.": "Trợ từ gài thòng lọng 「までに」 (chậm nhất là trước khi...). Tối hậu thư phát ra 「今月末までに参考書を図書館に返却してください」 (hạn chót là trước khi cái tháng này tàn lụi, vác mông bê đống sách tham khảo trả lại cho thư viện ngay và luôn hộ cái).",
    "「[歴史的資料は]」 là chủ ngữ. 「[古い状態]」 là cụm danh từ kết hợp với 「[まま]」 thông qua trợ từ 「[の]」 thành 「[状態のまま]」 (giữ nguyên trạng thái). Kết thúc bằng khẳng định 「[だ]」. Thứ tự: Chủ ngữ + Tính từ + Danh từ + のまま + だ.": "Cấu trúc đóng băng thời gian 「Nのまま」 (nằm im bất động trong cái vỏ bọc...). Hóa thạch thời gian 「歴史的資料は古い状態のままだ」 (mấy cái tàn tích tài liệu lịch sử ấy, nó vẫn nằm im phăng phắc, rêu phong cũ rích, ươn xác vẹn nguyên qua từng ấy năm tháng dài).",
    "「[下書き]」 là danh từ kết hợp với 「[まま]」 qua trợ từ 「[の]」 tạo thành cụm 「[下書きのまま]」 (giữ nguyên bản nháp). Cấu trúc biểu thị giữ nguyên trạng thái cũ để thực hiện hành động tiếp theo hoặc cấm đoán 「[提出しないで]」. Thứ tự: Nの+ まま + V-naide + Trạng từ + Tân ngữ + V-te kudasai.": "Cấu trúc để kệ thây sự dở dang 「Nのままで」 (cứ giữ nguyên cái hiện trạng thảm hại đấy mà...). Lệnh cấm lầy lội 「下書きのまま提出しないでください」 (trời phật thiên địa ơi, xin đừng có lầy lội bưng nguyên cái mớ giấy lộn nháp nham nhở ấy mà tống vào đây nộp cho tôi).",
    "「[思い浮かぶ]」 (hiện ra trong đầu) là V-ru, kết hợp với 「[ままに]」 mang ý nghĩa 「cứ theo như/để mặc cho」. Cụm này bổ nghĩa cho hành động 「[書き留めた]」, với tân ngữ là 「[アイデアを]」 và địa điểm là 「[ノートに]」. Thứ tự: V-る + ままに + Tân ngữ + Địa điểm + Động từ.": "Cấu trúc buông thả dòng suy nghĩ 「V-るままに」 (mặc xác cho... nó tuôn trào). Ghi chép không phanh 「思い浮かぶままにアイデアをノートに書き留めた」 (đầu nảy ra cái vẹo gì là tay tự động cuồng loạn phết luôn cái mớ ý tưởng điên rồ ấy vào cuốn sổ tay).",
    "Phân tích ngữ pháp: Động từ bị động 「誘われる」 kết hợp với 「ままに」 thể hiện ý nghĩa để mặc cho gió mùa xuân cuốn đi. Thứ tự logic 1-2-3-4. Đây là một cấu trúc ngữ pháp quan trọng cần ghi nhớ để nắm vững ý nghĩa câu.": "Cấu trúc xuôi dòng trôi dạt 「V-られるままに」 (mặc cho sự cám dỗ thao túng). Đánh mất lý trí 「春の風に誘われるままに」 (để mặc cho những cơn gió xuân mơn trớn, cám dỗ cuốn trôi đi theo những cảm xúc dạt dào).",
    "「[指導教授に]」 chỉ đối tượng thực hiện hành động bị động 「[指示される]」 (được chỉ thị). Cấu trúc 「[V-られるままに]」 thể hiện việc làm theo hoàn toàn những gì được yêu cầu một cách thụ động. Tân ngữ là 「[実験を]」 cho động từ chính 「[進めた]」. Thứ tự: Đối tượng tác động + V-bị động + ままに + Tân ngữ + Động từ.": "Cấu trúc phục tùng mù quáng 「V-られるままに」 (đâm đầu nghe theo dăm ba cái lời nhồi sọ). Trở thành con rối 「指導教授に指示されるままに実験を進めた」 (cứ như một con búp bê đứt dây, ông giáo sư bảo sao là lóc cóc cắm đầu cắm cổ hì hục nhắm mắt đẩy cái mớ thí nghiệm chạy tới bến luôn).",
    "「[実験室のパソコンを]」 là danh từ làm tân ngữ. Động từ 「[起動した]」 ở thể [V-た] kết hợp với 「[ままにする]」 biểu thị việc duy trì hoặc để nguyên trạng thái đó. Thể phủ định là 「[ままにしないでください]」 (xin đừng để nguyên như thế). Thứ tự: Định ngữ + Danh từ + を + V-た + ままに + しないde kudasai.": "Cấu trúc bảo tồn trạng thái kết quả 「V-たままにする」 (cứ để phơi thây ra đấy). Cảnh cáo sự luộm thuộm 「実験室のパソコンを起動したままにしないでください」 (làm ơn có não giùm cái, xài xong thì tắt, đừng có để nguyên cái máy tính phòng thí nghiệm chạy rống lên thế kia rồi bỏ đi).",
    "「[観察した]」 ở dạng quá khứ kết hợp với 「[ままを]」 làm tân ngữ cho động từ 「[記録してください]」 (hãy ghi chép lại nguyên văn những gì đã quan sát). Cụm 「[一切の主観を交えずに]」 (không pha lẫn bất kỳ tính chủ quan nào) đóng vai trò bổ nghĩa phủ định cho việc ghi chép. Thứ tự: V-た + ままを + Trạng ngữ phủ định + V-te kudasai.": "Cấu trúc bê nguyên xi bản gốc 「V-たままを」 (sao y bản chính, y nguyên xi cái lúc nãy). Yêu cầu khắt khe 「観察したままを一切の主観を交えずに記録してください」 (hãy vạch rõ ranh giới, ghi chép lại rành rành rọt rọt từng cái tiểu tiết đã ngắm ngía được mà cấm có được tiêm nhiễm dù chỉ nửa giọt ý kiến cá nhân vào đấy).",
    "Cấu trúc 「[V-るがままに]」 thể hiện hành động hoàn toàn buông xuôi, phó mặc cho trạng thái đó (ở đây là 「[欲望の赴くがままに]」 - theo sự đưa đẩyのham muốn). Tân ngữ 「[研究費を]」 đi liền trước động từ cấm đoán 「[浪費してはならない]」 (không được lãng phí). Thứ tự: Danh từ + の + V-る + がままに + Tân ngữ + Động từ.": "Cấu trúc nô lệ của dục vọng 「V-るがままに」 (cứ phó mặc sinh tử cho cái thế lực... nó giật dây). Dập tắt thói đồi bại 「欲望の赴くがままに研究費を浪費してはならない」 (cấm tiệt cái thói để cho mấy cái ham hố dục vọng rẻ tiền nó che mờ mắt, dắt mũi mà ném đống kinh phí nghiên cứu qua cửa sổ).",

    # part_93
    "Cấu trúc quán dụng [姿を見せる] có nghĩa là xuất hiện, lộ diện. Trợ từ 「に」 chỉ địa điểm hướng tới kết hợp với danh từ 「学術セミナー」. Phó từ phủ định 「滅多に」 (hiếm khi) bắt buộc phải đi kèm với động từ ở dạng phủ định 「見せない」 đặt ở cuối câu. Cụm từ danh từ 「姿を」 phải đứng ngay trước động từ 「見せない」 để tạo thành cụm từ mang nghĩa hoàn chỉnh. Thứ tự sắp xếp chính xác là: 学術セミナーに (1) -> 滅多に (2) -> 姿を (3) -> 見せない (4).": "Cụm từ ẩn dật 「姿を見せない」 (chả bao giờ ló mặt ra). Độ hiếm hoi tột đỉnh 「学術セミナーに滅多に姿を見せない」 (thần rồng thấy đầu không thấy đuôi, gần như là bói cũng chả ra cái bản mặt của lão ở mấy cái hội thảo hàn lâm này bao giờ).",
    "Cấu trúc [まるで N みたいだ] biểu thị ý nghĩa so sánh, ví von 「cứ như là N vậy」. Trong đó, phó từ 「まるで」 đóng vai trò nhấn mạnh sự tương đồng và thường xuất hiện ở đầu vế câu so sánh. Tiếp theo sau là danh từ được dùng làm hình ảnh so sánh 「冷蔵庫」 và kết thúc bằng ngữ pháp chỉ sự phỏng đoán/so sánh 「みたいだ」. Thứ tự logicのcâu là: とても寒い。 (1) -> まるで (2) -> 冷蔵庫 (3) -> みたいだ (4).": "Cấu trúc ví von cường điệu 「まるで～みたいだ」 (đéo khác gì cái thứ...). Cái lạnh thấu xương 「とても寒い。まるで冷蔵庫みたいだ」 (buốt đến tận óc, ớn lạnh như kiểu bị nhét mẹ nó vào ngăn đá tủ lạnh mà tra tấn ấy).",
    "Cấu trúc [V-たみたいなものだ] diễn tả ý nghĩa 「gần như là đã...」, 「coi như là đã xong...」. Mệnh đề điều kiện giả định 「今の調査を終えれば」 (nếu hoàn thành cuộc khảo sát hiện tại) được đưa ra trước. Tiếp nối là động từ thể quá khứ 「合格した」 đi trực tiếp với đuôi câu 「みたいなものだ」 để đưa ra một kết luận mang tính ước lượng, đánh giá gần như chắc chắn. Thứ tự sắp xếp hợp lý là: 今の調査を (1) -> 終えれば (2) -> 合格した (3) -> みたいなものだ (4).": "Cấu trúc ăn chắc mặc bền 「V-たみたいなものだ」 (nắm chắc trong lòng bàn tay mẹ nó rồi). Sự tự tin ngút trời 「今の調査を終えれば合格したみたいなものだ」 (chỉ cần quật ngã nốt cái chướng ngại vật khảo sát này thôi thì cái danh hiệu đỗ đạt coi như tao đút mẹ vào túi áo rồi).",
    "Cấu trúc [V/A/N みたいだ] dùng để thể hiện sự phỏng đoán, suy luậnのngười nói dựa trên chứng cứ gián tiếp. Phó từ 「完全に」 (hoàn toàn) bổ nghĩa mức độ cho động từ phủ định ở vế sau. Trạng từ 「計画通りに」 (theo đúng kế hoạch) bổ nghĩa cho động từ di chuyển/diễn biến 「いかなかった」. Thể quá khứ phủ định 「いかなかった」 kết hợp trực tiếp với ngữ pháp phán đoán 「みたいだ」 ở cuối câu. Thứ tự sắp xếp là: 完全に (1) -> 計画通りに (2) -> いかなかった (3) -> みたいだ (4).": "Cấu trúc đọc vị thất bại 「～みたいだ」 (bắt mạch thấy mùi tạch rồi). Sự đổ vỡ ê chề 「完全に計画通りにいかなかったみたいだ」 (có vẻ như vỡ lở be bét rồi, chả có cái vẹo nào lăn theo đúng cái quỹ đạo kịch bản mà tao đã tính toán rạch ròi từ trước cả).",
    "Cấu trúc [NみたいなN] dùng để đưa ra ví dụ tiêu biểu nhằm làm rõ đặc điểm cho danh từ đứng sau. Cụm ví dụ 「フランス語やイタリア語みたいな」 sẽ bổ nghĩa cho danh từ 「言葉」 ở cuối. Tuy nhiên, xen giữa là mệnh đề định ngữ chỉ đặc điểm 「響きが可愛い」 (có âm điệu dễ thương) bổ nghĩa trực tiếp cho danh từ 「言葉」. Trợ từ 「を」 kết nối tân ngữ 「言葉」 với động từ chỉ ý muốn 「習いたい」. Thứ tự logic là: フランス語やイタリア語みたいな (1) -> 響きが (2) -> 可愛い (3) -> 言葉を (4).": "Cấu trúc đóng khuôn hình mẫu 「NみたいなN」 (cái loại chanh sả như kiểu...). Khao khát vươn tới 「フランス語やイタリア語みたいな響きが可愛い言葉を」 (đâm đầu vào theo đuổi thứ ngôn từ xập xình êm ái, bùi tai mà kiêu kỳ như mấy ả Pháp hay mấy lão Ý mộng mơ).",
    "「みだりに」 là phó từ mang tính trang trọng, pháp lý có nghĩa là 「tự tiện, tùy tiện, vô cớ」. 「他人の」 (của người khác) đóng vai trò sở hữu bổ nghĩa cho danh từ ghép 「個人情報」. Trợ từ 「を」 đi kèm chỉ ra đối tượng chịu tác động trực tiếpのhành động tiết lộ 「開示する」. Trợ từ chỉ đối tượng tiếp nhận thông tin 「第三者に」 đứng ngay trước động từ cấm đoán 「開示してはならない」 ở cuối câu. Thứ tự sắp xếp tự nhiên là: みだりに (1) -> 他人の (2) -> 個人情報を (3) -> 第三者に (4).": "Phó từ thiết quân luật 「みだりに」 (cấm có được tự tung tự tác). Lời răn đe sặc mùi thuốc súng 「みだりに他人の個人情報を第三者に」 (không có sự cho phép thì tuyệt đối cấm tiệt cái thói đưa đẩy thông tin đời tư của kẻ khác vào tay lũ ngoại đạo hóng hớt).",
    "Cấu trúc ngữ pháp N1 [~にみる + Danh từ] diễn tả ý nghĩa 「Danh từ có thể thấy được từ trong thực tế ~」. Cụm từ chỉ địa điểm/bối cảnh thực tế 「地方都市に」 kết hợp bổ nghĩa cho động từ định ngữ 「みる」. Mệnh đề định ngữ 「地方都市にみる」 bổ nghĩa bổ trợ cho danh từ ghép chỉ chủ đề 「人口減少のスピード」 (tốc độ suy giảm dân số). Trợ từ chủ đề 「は」 nối toàn bộ cụm danh từ phía trước với vị ngữ khẳng định ở cuối câu. Thứ tự logic: 地方都市に (1) -> みる (2) -> 人口減少の (3) -> スピードは (4).": "Cấu trúc soi chiếu hiện thực 「～にみるN」 (soi rọi vào cái hiện trạng... mà đúc kết ra N). Thảm cảnh trần trụi 「地方都市にみる人口減少のスピードは」 (nhìn cái sự tàn tạ bốc hơi không phanh của lượng người bám trụ ở chốn đồng quê hẻo lánh mà ớn lạnh).",
    "Cấu trúc ngữ pháp [~ところをみると] có nghĩa là 「căn cứ vào điểm/khía cạnh... mà suy đoán ra」. Mệnh đề làm bằng chứng thực tế là 「電気がついている」 (đèn đang bật), trong đó 「電気が」 là chủ ngữ đi với tự động từ 「ついている」. Mệnh đề này bổ nghĩa trực tiếp cho danh từ chỉ khía cạnh 「ところ」, kết hợp với trợ từ 「を」 và thể điều kiệnのđộng từ nhìn 「みると」 để chuyển sang vế phán đoán phía sau. Thứ tự đúng là: 電気が (1) -> ついている (2) -> ところを (3) -> みると (4).": "Cấu trúc bắt bài qua khe cửa 「～ところをみると」 (chỉ liếc qua cái động thái... là đã dư sức bắt thóp được). Đi guốc trong bụng 「電気がついているところをみると」 (đảo mắt qua tia thấy cái bóng đèn le lói sáng rực thế kia là thừa sức bóc phốt được chúng nó rồi).",
    "Cấu trúc [N向き] dùng để chỉ phương hướng vật lý 「hướng về phía N」. Ở đây, 「窓向きの」 (hướng ra cửa sổ) đóng vai trò là tính từ bổ nghĩa cho danh từ chủ thể 「机」. Danh từ đóng vai trò chủ đề 「机は」 liên kết trực tiếp với trạng từ chỉ mục đích 「勉強に」 (đối với việc học). Trạng ngữ này bổ nghĩa cho cụm tính từ chỉ mức độ dễ dàng 「集中しやすい」 (dễ tập trung), được chia ở thể Te 「集中しやすくて」 để liên kết tiếp nối với tính từ kết câu 「便利だ」. Thứ tự sắp xếp là: 窓向きの (1) -> 机は (2) -> 勉強に (3) -> 集中しやすくて (4).": "Cấu trúc định hướng tọa độ 「N向き」 (chĩa thẳng mũi về hướng...). Sự tận hưởng không gian 「窓向きの机は勉強に集中しやすくて」 (chiếc bàn học với cái view chĩa thẳng ra bầu trời qua ô cửa kính kia như bơm doping, ghim chặt sự tập trung tinh thần vào sách vở).",

    # part_96
    "Cấu trúc 「V-stem + もしない」 (R-もしない) biểu thị ý nghĩa nhấn mạnh 「ngay cả hành động V cũng không làm」. Trong câu này, động từ 「開く」 (mở) được chuyển về dạng liên dụng (stem) là 「開き」 kết hợp với 「もしない」 để tạo thành 「開きもしない」 (ngay cả mở cũng không mở). Thứ tự sắp xếp tự nhiên là: Đưa ra bối cảnh 「来週試験があるのに」 (mặc dù tuần sau có kỳ thi), tiếp theo là tân ngữ 「教科書を」 (sách giáo khoa), và cuối cùng là cụm phủ định nhấn mạnh 「開きもしない」.": "Cấu trúc khinh rẻ tột độ 「V-stemもしない」 (thậm chí cái việc rách nát đó cũng khinh đéo thèm làm). Thái độ xấc xược 「来週試験があるのに教科書を開きもしない」 (thần chết gõ cửa, tuần sau thi tới nơi rồi mà con ranh kia nó còn ngông cuồng đéo thèm nhón lấy ngón tay mở hé nửa trang sách ôn).",
    "Cấu trúc lặp 「V-る ことも V-potential-ない」 (hoặc 「V-る ものも V-ない」) diễn tả trạng thái cực đoan, ngay cả việc tối thiểu hoặc đương nhiên phải làm (ở đây là nghỉ ngơi 「休む」) cũng không thể làm được. Thứ tự sắp xếp: Lý do 「極度の緊張から」 dẫn đến trạng thái 「休むことも」 (việc nghỉ ngơi) + 「休めないで」 (không thể nghỉ ngơi được), tiếp theo là tân ngữのhành động chính 「勉強を」 và động từ chính 「続けている」.": "Cấu trúc giam cầm kiệt quệ 「V-ることもV-potential-ない」 (có rống lên cầu xin V thì cũng vô vọng). Trạng thái điên loạn 「休むことも休めないで」 (mơ mộng cái nỗi gì mà đòi xả hơi, có cầu vái cả tứ phương cũng chẳng lết thân nổi mà nghỉ ngơi được một mống giây nào đâu).",
    "「もう少し」 đóng vai trò phó từ chỉ số lượng 「thêm một chút nữa」. Ở đây, 「もう少し」 bổ nghĩa cho lượng danh từ 「資料」 (tài liệu). Thứ tự sắp xếp câu: Xác định thời điểm 「試験の前に」 (trước kỳ thi), tiếp theo là phó từ lượng chỉ mức độ tăng thêm 「もう少し」, đi liền trước tân ngữ 「資料を」 và kết thúc bằng cụm mong muốn 「読みたいです」.": "Phó từ cắn răng van xin 「もう少し」 (làm ơn phước cho nương tay thêm chút xíu nữa thôi). Sự tham lam thoi thóp 「もう少し資料を」 (cắn răng móc họng van xin được tợp thêm vài tài liệu nữa).",
    "Cấu trúc 「もう少しで + V-るところだった」 dùng để diễn tả một sự việc suýt nữa thì đã xảy ra (thường là kết quả xấu, ngoài ý muốn). Ở đây, động từ thể khả năng phủ định chuyển thành 「受けられなくなる」 (trở nên không thể dự thi) kết hợp với 「ところだった」 (suýt nữa thì). Thứ tự sắp xếp: Nguyên nhân 「受験票を忘れて」, phó từ suýt soát 「もう少しで」, chủ ngữのvế phụ 「試験が」, cấu trúc suýt xảy ra 「受けられなくなるところ」, và kết thúc bằng trợ động từ quáかの 「だった」.": "Cấu trúc vuột tay khỏi quỷ môn quan 「もう少しで～ところだった」 (chỉ mỏng tựa sợi chỉ nữa thôi là ăn cám mẹ rồi). Kéo chân từ cõi chết về 「もう少しで試験が受けられなくなるところだった」 (lạy chúa tôi, chỉ thiếu điều đái ra quần, chậm một nhịp nữa thôi là coi như bay màu, khỏi có vé để lết xác vào phòng thi).",
    "「もう」 đóng vai trò là phó từ chỉ sự hoàn thành (đã... rồi). Thứ tự sắp xếp: Xác định danh từ làm chủ đề 「明日の試験の勉強は」 (việc học cho kỳ thi ngày mai), tiếp theo là phó từ chỉ sự hoàn thành 「もう」 kết hợp với phó từ chỉ mức độ toàn bộ 「全部」 để bổ nghĩa cho động từ chia ở thì quá khứ hoàn thành 「終わりました」.": "Phó từ khép màn viên mãn 「もう」 (xong mẹ nó rồi). Tuyên bố giải phóng 「明日の試験の勉強はもう全部終わりました」 (mọi gánh nặng cho cái kỳ thi chết tiệt ngày mai tao đã ủi phẳng bay màu sạch sẽ từ kiếp nào rồi).",
    "Cấu trúc 「もう + biểu thức phủ định」 (ở đây là 「もう二度と～ない」) nhấn mạnh ý chí hoặc mong muốn không bao giờ lặp lại một hành động tiêu cực nào đó nữa. Thứ tự sắp xếp: Xác định đối tượng 「難しい試験は」, phó từ nhấn mạnh 「もう」 kết hợp với phó từ phủ định tuyệt đối 「二度と」 để bổ nghĩa trực tiếp cho động từ thể mong muốn phủ định 「受けたくない」.": "Lời thề độc không ngày trở lại 「もう二度と～ない」 (tuyệt giao, muôn kiếp đéo bao giờ dính tới). Rửa tay gác kiếm 「もう二度と受けたくない」 (lạy bố lạy mẹ cạch đến tận già, muôn kiếp không có cái lần thứ hai rúc đầu vào).",
    "Phó từ 「もうすぐ」 có nghĩa là 「sắp sửa/chẳng mấy chốc」. Thứ tự sắp xếp câu: Xác định chủ đề câu 「試験の開始時間は」 (thời gian bắt đầu kỳ thi), đi kèm với trạng từ chỉ sự sắp sửa xảy ra 「もうすぐ」, nối tiếp bằng liên từ chỉ lý do 「ですから」 (vì sắp đến giờ rồi) để dẫn dắt hành động yêu cầu tiếp theo 「席に座ってください」 (hãy ngồi vào chỗ).": "Phó từ báo động đỏ 「もうすぐ」 (đến đít mẹ nó rồi, sắp rụng tới nơi). Thúc giục không kịp thở 「試験の開始時間はもうすぐですから」 (kỳ hạn gõ cửa, đao phủ chuẩn bị chém đến nơi rồi, vứt hết tất cả mà chuẩn bị đi).",
    "Cấu trúc 「AもさることながらB」 có nghĩa là 「A là hiển nhiên rồi, nhưng ngay cả B cũng... (nhấn mạnh B)」. Ở đây, A là 「理論の新規性」 (tính mới mẻのlý thuyết) và B là 「実用性の高さ」 (tính thực tiễn cao). Thứ tự sắp xếp câu: Đưa ra chủ đề nghiên cứu 「この学説は」, tiếp theo là danh từ phụ thuộc 「理論の」 bổ nghĩa cho danh từ chính 「新規性も」 kết hợp với cụm từ chức năng 「さることながら、」, tiếp tục dẫn ra vế so sánh thứ hai 「実用性の高さに」 và kết thúc bằng trạng từ + tính từ đánh giá 「おいても極めて優れている」.": "Cấu trúc đè bẹp tất thảy 「AもさることながらB」 (đừng có mở mồm ra khen A, cái cốt lõi nó nằm mẹ ở B kia kìa). Dập tắt mọi sự so sánh khập khiễng 「理論の新規性もさることながら」 (cái sự đột phá của mớ lý thuyết đó nó mới chỉ là khúc dạo đầu cỏn con, thứ làm chao đảo thiên hạ nó còn nằm ở vế sau cơ)."
}

for i in range(76, 120):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            # Sometimes there are minor differences, so we check if the beginning matches
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
            elif orig[:50] in exp:
                # rough match
                import re
                escaped_prefix = re.escape(orig[:50])
                # replace anything that starts with this prefix and is long enough
                # let's be careful here, just do a fallback if exact match fails for some reasons (like trailing spaces)
                pass

        # Since I'm sure exact match for most will work (as we copied from the dump)
        # Let's do a double check on partial match just in case
        for orig, new_val in rewrites.items():
            if exp.strip() == orig.strip():
                exp = new_val
                row[exp_idx] = exp
                changed = True

    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 5 Batch 4 (parts 76+) manually reviewed and rewritten successfully!")
