import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_2_business'

fixes = {
    "part_11.csv-1": "Cấu trúc 'A-く思います' biểu thị cảm xúc, suy nghĩ của người nói đối với một sự việc. Ở đây '申し訳なく思います' nghĩa là 'cảm thấy có lỗi'. Câu bắt đầu với '不快な' bổ nghĩa cho danh từ '思い', tiếp theo là '思いをさせてしまった' đi với danh từ chỉ đối tượng 'お客様に'. Thể thông thường của động từ kết hợp với 'こと' để danh từ hóa cụm vế trước, làm tân ngữ cho hành động tâm trạng phía sau. Trạng từ '大変' bổ nghĩa cho tính từ '申し訳なく' để nhấn mạnh mức độ trước khi kết thúc bằng '思います'.",
    "part_11.csv-2": "Cấu trúc 'V-ようと思う' thể hiện ý định của người nói. Ở đây dùng dạng '～しようと思って' để nối vế chỉ ý định với hành động thực tế đang diễn ra ở vế sau. Cụm danh từ '新しいプロジェクトの' bổ nghĩa cho '企画書'. '企画書を' đóng vai trò tân ngữ đi với trợ từ 'を' cho động từ '提出しよう'. Trạng từ '早めに' bổ nghĩa cho động từ ý chí '提出しよう'. Cuối cùng, '提出しようと思って' kết nối với vế sau '準備を進めております' để giải thích lý do hành động.",
    "part_11.csv-3": "Cấu trúc '～ように思う' diễn đạt ý kiến, suy đoán mang tính chủ quan nhẹ nhàng, lịch sự trong giao tiếp công sở. Cụm '現場の' bổ nghĩa cho danh từ chỉ đối tượng '担当者'. Cấu trúc '～にとって' nghĩa là 'đối với ai đó', làm thành phần bổ ngữ cho tình trạng phía sau. '少し無理が' gồm trạng từ và trợ từ 'が' đi kèm với tự động từ 'ある'. Động từ thể từ điển 'ある' kết hợp trực tiếp với 'ように思う' để tạo thành thể suy đoán.",
    "part_11.csv-4": "Cấu trúc 'Nのことを思う' có nghĩa là 'nghĩ về N / đặt mình vào vị trí của N để suy nghĩ'. Thêm 'と' thành '思うと' tạo mối quan hệ điều kiện 'nếu nghĩ về...'. Định ngữ '取引先の' bổ nghĩa cho danh từ 'こと' để xác định đối tượng đối tác. Trợ từ 'を' chỉ đối tượng của hành động tâm lý '思う'. Cụm '今回の条件変更を' đóng vai trò tân ngữ của vế sau, dẫn dắt đến kết luận không thể chấp nhận ở phần cuối câu.",
    "part_11.csv-5": "Cấu trúc 'N1を N2(だ)と思う' dùng để biểu thị nhận thức, đánh giá của người nói về N1 là N2. 'このプロジェクトを' là đối tượng được đánh giá, đi với trợ từ 'を'. Cụm bổ ngữ chỉ nơi chốn '海外市場へ' bổ nghĩa cho động từ '進出する'. Động từ '進出する' thể thông thường đóng vai trò định ngữ bổ nghĩa cho danh từ '良い機会'. Danh từ '機会' kết hợp với 'だと思った / だと思う' để đưa ra kết luận đánh giá.",
    "part_11.csv-6": "Từ nối '思えば' đặt ở đầu câu để hồi tưởng lại quá khứ. Nó mở đầu mạch hồi tưởng, tiếp nối là cụm tân ngữ 'この事業を' đi với trợ từ 'を' để làm đối tượng cho động từ '立ち上げた'. Động từ thể quá khứ '立ち上げた' đóng vai trò định ngữ bổ nghĩa cho mốc thời gian '当初は' (khi bắt đầu). Mạch câu kết thúc bằng việc miêu tả trạng thái trong quá khứ.",
    "part_11.csv-7": "Cấu trúc '今から思えば' dùng để đưa ra đánh giá ở hiện tại về một sự việc đã qua trong quá khứ. Cụm từ này đứng đầu câu, nối tiếp là chủ ngữ phụ trong mệnh đề định ngữ 'あの時先輩が'. Động từ kính ngữ hành động bổ trợ '指摘してくださった' bổ nghĩa cho danh từ trung tâm '問題点は' để làm chủ ngữ chính của toàn câu. Vế cuối đưa ra phán đoán trạng thái.",
    "part_11.csv-8": "Cấu trúc '～と思ったら' diễn tả một sự việc xảy ra gần như ngay lập tức sau một sự việc khác, hoặc một kết quả bất ngờ trái với suy nghĩ ban đầu. Danh từ chủ ngữ 'エラーが' đi với tự động từ '解決した'. Động từ thể thông thường '解決した' kết hợp với 'と思ったら' và tạo thành cấu trúc diễn tiến 'vừa mới nghĩ là đã giải quyết xong thì...'. Cụm trạng ngữ chỉ nơi chốn '別の場所に' bổ nghĩa cho cụm động từ kết quả bất ngờ ở cuối câu.",
    "part_11.csv-9": "Liên từ 'および' dùng để nối hai danh từ có quan hệ đẳng lập trong văn phong trang trọng, công sở ('và', 'cũng như'). Danh từ thứ nhất '原本' đi sau thành phần bổ nghĩa '契約書の'. Liên từ 'および' đặt giữa hai danh từ để liên kết song hành. Danh từ thứ hai '身分証明書のコピー' tạo thành cụm danh từ hoàn chỉnh. Trợ từ 'を' ở cuối xác định toàn bộ cụm danh từ làm tân ngữ cho hành động kính ngữ 'ご提出ください'.",
    "part_11.csv-10": "Danh từ '折（おり）' tương đương với '時（とき）' nhưng mang sắc thái trang trọng, lịch sự dùng trong thương mại ('nhân dịp, khi'). Cụm kính ngữ 'お越しの' (khi đến) bổ nghĩa trực tiếp cho danh từ '折'. Trợ từ 'には' nhấn mạnh thời điểm đưa ra gợi ý. Phó từ hô ứng 'ぜひ' đi kèm cụm danh từ chỉ nơi chốn '弊社に' bổ nghĩa cho hành động ở vế sau. Dạng kính ngữ 'お＋V tâm ngữ' kết hợp cấu trúc cầu khiến tạo thành lời mời trang trọng.",
    "part_11.csv-11": "Cấu trúc 'おりから' mang ý nghĩa 'đúng vào lúc/trong bối cảnh sự việc đang diễn ra' (thường là bối cảnh kinh tế, xã hội kéo dài, dùng ở trình độ N1). Chủ ngữ của mệnh đề phụ '低迷が' đi với tự động từ '続く'. Động từ thể từ điển '続く' kết hợp trực tiếp với 'おりから' để thiết lập bối cảnh cho toàn câu. Cụm tân ngữ '予算の削減を' bổ nghĩa trực tiếp cho hành động bắt buộc ở vế sau '検討せざるを得ません'.",
    "part_11.csv-12": "Cấu trúc 'おりからの＋N' dùng để chỉ một hiện tượng xảy ra do tác động của bối cảnh đặc biệt đang diễn ra tại thời điểm đó (N1). Cụm từ hạn định bối cảnh 'おりからの' bổ nghĩa cho cụm danh từ tiếp theo '価格競争の'. Danh từ nguyên nhân '激化' kết hợp với cấu trúc chỉ nguyên nhân lý do '～により'. Cụm danh từ chủ ngữ hành động '売上目標の達成が' đóng vai trò chủ thể đi với trợ từ 'が' để dẫn tới tính từ kết quả ở phần kết câu.",
    "part_11.csv-13": "Cấu trúc 'N1か N2か' dùng ở trình độ N5 để đưa ra các lựa chọn 'hoặc là N1 hoặc là N2'. Chủ đề câu là 'お支払いは'. Danh từ thứ nhất '銀行振込か' kết hợp từ nối 'か'. Danh từ thứ hai 'クレジットカード' kết hợp với 'か' để hoàn thành cấu trúc lựa chọn song hành. Cụm 'どちらかを' đóng vai trò tân ngữ lựa chọn cho động từ '選んでください'.",
    "part_11.csv-14": "Cấu trúc 'Nか何か' ở trình độ N5 dùng để đưa ra một gợi ý nhẹ nhàng mang tính đại diện ('N hoặc thứ gì đó tương tự'). Chủ đề câu là '次回の打ち合わせは'. Danh từ gợi ý 'お電話' đi liền với trợ từ lựa chọn 'か'. Đại từ nghi vấn kết hợp trợ từ '何かに' tạo thành cụm từ chỉ phương án thay thế mơ hồ, kết hợp với cấu trúc quyết định lựa chọn '～にする'. Động từ phủ định lịch sự tạo lời mời rủ 'しませんか'.",
    "part_11.csv-15": "Cấu trúc 'V1か V2かで' biểu thị mối quan hệ nguyên nhân - kết quả dựa trên hai lựa chọn đối lập ('tùy thuộc vào việc có V hay không mà...'). Động từ hành động '参加するか' mở đầu chuỗi, dạng phủ định 'しないかで' hoàn thành cặp lựa chọn đối lập và thêm trợ từ 'で' chỉ căn cứ tạo biến đổi. Động từ '集める' làm định ngữ bổ nghĩa cho danh từ '会費'. Chủ ngữ '会費が' đi kèm tự động từ chỉ sự thay đổi ở phần kết câu.",
    "part_11.csv-16": "Cấu trúc '～かどうか' dùng để lồng một câu hỏi không có từ để hỏi vào câu lớn hơn ('có... hay không'). Chủ ngữ mệnh đề phụ 'この企画が' kết hợp với đối tượng thực hiện hành động bị động '上司に'. Động từ thể bị động '承認される' đi với trợ từ 'か' tạo nửa đầu vế nghi vấn. Đại từ 'どうか' hoàn thiện cấu trúc nghi vấn. Phó từ phủ định thời gian 'まだ' bổ nghĩa cho động từ kết thúc ở vế sau.",
    "part_11.csv-17": "Cấu trúc 'V-るか V-ないか' diễn tả hai lựa chọn hành động đối lập rõ ràng ('có làm gì hay không'). Cụm từ hành động '参加するか' đi sau thành phần chỉ mục đích nơi chốn. Động từ dạng phủ định ngắn gọn 'しないか' hoàn thành vế nghi vấn lựa chọn. Cụm trạng từ giới hạn thời gian '明日までに' bổ nghĩa cho yêu cầu thực hiện hành động phía sau. Danh từ tân ngữ '返事を' kết hợp với động từ sai khiến lịch sự.",
    "part_11.csv-18": "Cấu trúc 'V-るかV-ないかのうちに' diễn tả một sự việc diễn ra gần như ngay lập tức, đồng thời với sự việc trước đó ('vừa mới... thì đã...'). Chủ ngữ '新商品が' đi kèm động từ bị động '発売されるか'. Thể phủ định bị động tương ứng 'されないかの' kết hợp danh từ chỉ thời gian 'うちに' tạo nên trạng ngữ chỉ sự đồng thời. Phó từ mức độ 'すべて' bổ nghĩa cho trạng thái hoàn thành bất ngờ.",
    "part_11.csv-19": "Cấu trúc '疑問詞 ＋ Thể thông thường ＋ か' lồng một câu hỏi có từ để hỏi vào làm mệnh đề phụ cho động từ chính đứng sau. Từ để hỏi chỉ thời gian '何時に' đứng trước động từ hành động chủ thể '始まる'. Trợ từ nghi vấn 'か' gắn ngay sau động từ '始まる' tạo thành mệnh đề phụ bổ nghĩa cho hành động kiểm tra. Trạng từ '事前に' bổ nghĩa cho danh từ hành động '確認を'. Cụm '確認をして' kết hợp cấu trúc chuẩn bị trước '～ておく' chuyển sang thể sai khiến lịch sự.",
    "part_11.csv-20": "Cấu trúc '疑問詞＋か' ở trình độ N5 biến từ để hỏi thành đại từ bất định (ở đây '何か' nghĩa là 'cái gì đó / điều gì đó'). Cụm từ định hình phạm vi chủ đề '会議について' đứng đầu câu. Đại từ bất định '何か' đứng trước danh từ trung tâm để làm trạng ngữ bổ nghĩa. Danh từ đóng vai trò chủ đề phụ '質問は' đi kèm trợ từ 'は'. Động từ tồn tại 'あります' kết hợp trợ từ nghi vấn cuối câu 'か' để tạo thành câu hỏi hoàn chỉnh.",
    "part_12.csv-1": "'机の上に' chỉ địa điểm. '名刺が' chỉ đối tượng làm chủ ngữ. Cấu trúc số từ + か chỉ một lượng không xác định ('何枚か': vài tấm). Động từ 'あります' đi với trợ từ 'が' để chỉ sự tồn tại của đồ vật. Câu kết nối mạch lạc: 名刺が đi liền 何枚 か あり.",
    "part_12.csv-2": "Cấu trúc '～からか' biểu thị lý do không chắc chắn (có lẽ vì...). Mệnh đề '売れ行きが良い' (doanh số tốt) là lý do bổ nghĩa trực tiếp cho 'からか'. Chủ ngữ của vế sau là '社長は'. Cụm từ '機嫌が良い' (tâm trạng tốt) được chuyển sang dạng dự đoán thành '機嫌が良さそうです'. Câu dẫn dắt tự nhiên: 売れ行きが 良いから か、社長は 機嫌が.",
    "part_12.csv-3": "Trợ từ 'が' đứng sau danh từ '田中さん' để nhấn mạnh chủ thể được xác định rõ ràng trong câu. Tính từ '新しい' (mới) đứng trước để bổ nghĩa trực tiếp cho danh từ '課長' (trưởng phòng). Các thành phần kết hợp: 田中さん が 新しい 課長.",
    "part_12.csv-4": "Cấu trúc 'NがNだから' thể hiện ý nghĩa 'vì bản chất của N đã như thế/chẳng ra gì nên dẫn đến kết quả tương ứng' (thường là tiêu cực). Vế sau chỉ đối tượng chịu ảnh hưởng kèm trợ từ 'も' ('部下も'). Tính từ đuôi na '怠慢な' bổ nghĩa cho danh từ '態度'. Mạch câu phát triển: 上司が 上司だから、 部下も 怠慢な.",
    "part_12.csv-5": "Cấu trúc 'NがNだけに' mang nghĩa 'chính vì N là một đối tượng đặc biệt hoặc quan trọng nên...'. Ở đây '取引先が取引先だけに' nhấn mạnh tầm quan trọng của đối tác, dẫn đến hệ quả '些細な' (nhỏ nhặt) bổ nghĩa cho 'ミスも' (ngay cả sai sót). Câu đi từ: 取引先が 取引先だけに、 些細な ミスも.",
    "part_12.csv-6": "Cấu trúc 'NがNなら' mang nghĩa 'nếu hoàn cảnh/thời kỳ khác đi (thường là tốt hơn)'. '時期が時期なら' đưa ra giả định về thời điểm. Theo sau là chủ ngữ của vế giả định 'この新規事業計画も' và động từ thể điều kiện quá khứ mang tính tiếc nuối '承認されただろうが' (có lẽ đã được duyệt nhưng...). Câu tiếp nối: 時期が 時期なら、この 新規事業計画も 承認されただろうが、.",
    "part_12.csv-7": "Cấu trúc 'N1がN1ならN2もN2だ' dùng để phê phán cả hai đối tượng đều tệ như nhau (bên trên thế nào bên dưới thế ấy). Câu kết nối liền mạch: 社長が 社長なら 専務も 専務だ.",
    "part_12.csv-8": "Mệnh đề bắt đầu bằng chủ đề '会社は'. Tính từ '小さい' đi với đuôi 'ですが' đóng vai trò là liên từ nghịch tiếp nối hai vế tương phản (tuy nhỏ nhưng...). Phó từ 'とても' đứng trước để bổ nghĩa cho tính từ đuôi na '有名です'. Câu phát triển mượt mà: 会社は 小さい ですが、 とても.",
    "part_12.csv-9": "Cấu trúc xưng tên lịch sự trong kinh doanh là 'Danh từ + と申します'. Trợ từ 'が' trong '申しますが' dùng làm lời mào đầu để dẫn dắt sang câu hỏi phía sau. Vế sau hỏi về sự hiện diện của đối phương bằng cách đưa đối tượng lên làm chủ đề kèm trợ từ は: '木村課長は'. Câu dẫn dắt: ABC会社の 田中と 申しますが、 木村課長は.",
    "part_12.csv-10": "Định từ 'この' bổ nghĩa cho danh từ '会議室を' đóng vai trò tân ngữ. '1時間ほど' là lượng từ chỉ thời gian đứng trước động từ thể nguyện vọng '使いたい'. Vĩ tố 'んですが' ở cuối câu thể hiện sự ngập ngừng, bỏ lửng lịch sự khi đưa ra yêu cầu. Các thành phần kết nối: この 会議室を 1時間ほど 使いたい.",
    "part_12.csv-11": "Cấu trúc 'V-たかいがあって' có nghĩa là 'thật bõ công/xứng đáng làm việc gì'. Động từ thể quá khứ '交渉した' đứng trước bổ nghĩa trực tiếp cho 'かい'. Vế sau diễn tả kết quả tốt đẹp đạt được sau nỗ lực, cụm 'ついに大口の' bổ nghĩa cho danh từ '契約'. Câu diễn tiến: 粘り強く 交渉した かいがあって、 ついに大口の.",
    "part_12.csv-12": "Mệnh đề giả định/kết quả tự nhiên kết thúc bằng 'いただくと' (khi nhận được...). Ngữ pháp 'R-がい' (động từ bỏ ます + がい) chỉ giá trị của hành động, ở đây là 'やりがい' (đáng làm). Cụm 'この仕事の' bổ nghĩa cho danh từ 'やりがいを' đóng vai trò làm tân ngữ cho động từ '感じます'. Câu kết hợp: 感謝の言葉を いただくと、 この仕事の やりがいを.",
    "part_12.csv-13": "Phó từ 'かえって' mang nghĩa 'ngược lại' (kết quả trái với mong đợi). Vế đầu thể hiện hành động mang ý tốt nhưng chưa trọn vẹn '報告したのだが' (đã báo cáo ngắn gọn nhưng...), đi liền sau đó là 'かえって' dẫn đến kết quả tiêu cực cho đối tượng '上司の誤解を' (hiểu lầm của sếp). Câu phát triển: 手短に 報告したのだが、 かえって上司の 誤解を.",
    "part_12.csv-14": "Ngữ pháp 'R-かえる' (động từ bỏ ます + かえる) có nghĩa là thay đổi trạng thái hoặc làm lại việc gì đó sang cách khác. Ở đây '書きかえる' nghĩa là viết lại. Trợ từ 'に' chỉ đích đến của sự thay đổi '表現に'. Phó từ 'もっと' bổ nghĩa cho tính từ '簡潔な'. Câu đi từ: もっと 簡潔な 表現に 書き.",
    "part_12.csv-15": "Cấu trúc '数量詞 + がかりで' có nghĩa là 'với sự chung sức của từng đó người để hoàn thành việc tốn công sức'. Cụm '部署の5人がかりで' nghĩa là cả 5 người trong phòng ban cùng làm. Phó từ 'やっと' (cuối cùng thì) đứng ngay trước động từ kết quả '完成させた'. Câu nối tiếp: 部署の 5人 がかりで やっと.",
    "part_12.csv-16": "Cấu trúc 'Nがかりの' ở đây mang nghĩa phụ thuộc, dựa dẫm hoàn toàn vào N. Cụm '親会社がかりの' bổ nghĩa cho danh từ '経営'. Phó từ '未だに' (cho đến nay vẫn) đặt ở đầu vế câu. Danh từ kèm trợ từ '経営から' đi với động từ '脱却できていない' (chưa thoát khỏi). Câu dẫn dắt: 未だに 親会社 がかりの 経営から.",
    "part_12.csv-17": "Động từ '通る' bỏ ます kết hợp thành '通りがかりの' đóng vai trò như một tính từ mang nghĩa 'vô tình đi ngang qua', bổ nghĩa trực tiếp cho danh từ chỉ người '同僚が' làm chủ ngữ. Phó từ '快く' (vui vẻ, sẵn lòng) đứng trước bổ nghĩa cho động từ hành động '手伝ってくれた'. Các phần ghép lại: 通り がかりの 同僚が 快く.",
    "part_12.csv-18": "Cấu trúc 'N + がかった' mang nghĩa là 'có tính chất, mang đậm màu sắc hoặc xu hướng của N'. Ở đây '皮肉がかった' nghĩa là mang tính châm biếm, mỉa mai. Cụm '部長の皮肉がかった' bổ nghĩa hoàn toàn cho danh từ làm chủ đề '発言は'. Mạch câu tiến triển: 部長の 皮肉 がかった 発言は、.",
    "part_12.csv-19": "Cấu trúc '限りがある' có nghĩa là 'có giới hạn'. 'ため' đóng vai trò liên từ chỉ nguyên nhân (vì có giới hạn...). Từ nghi vấn 'いかに' (như thế nào/ra sao) mở đầu cho mệnh đề gián tiếp vế sau, đứng trước để bổ nghĩa cho cụm hành động 'コストを削減するか'. Câu diễn tiến: 限り がある ため、いかに コストを.",
    "part_12.csv-20": "Cấu trúc '限りなく～に近い' có nghĩa là 'vô cùng gần với/gần như là...'. Phó từ '限りなく' (vô hạn, cực kỳ) đứng trước bổ nghĩa cho tính từ '近い'. Đối tượng so sánh đi với trợ từ 'に' là '犯罪に' (gần với tội phạm). Câu nối kết: 犯罪に 限り なく 近い.",
    "part_13.csv-2": "Ngữ pháp 'Nの限り' nghĩa là 'hết mức, toàn bộ N'. Cụm '誠意の限りを尽くして' nghĩa là dốc hết toàn bộ sự thành ý. Cụm này đứng trước để thể hiện thái độ đối với hành động tiếp theo ở vế sau là '御社の課題解決にあたる' (giải quyết vấn đề của quý công ty). Cuối cùng kết thúc bằng cấu trúc khiêm nhường biểu thị quyết tâm '～所存です'.",
    "part_14.csv-1": "Ngữ pháp 'がてら' kết hợp sau danh từ hành động 'ご挨拶' để diễn tả ý nghĩa 'nhân tiện làm việc A thì đồng thời làm việc B'. Câu đi từ mục đích chính kết hợp 'がてら', tiếp theo là thành phần chỉ địa điểm bổ nghĩa '近くに', mệnh đề định ngữ '新しくできた' bổ nghĩa cho danh từ '弊社ショールームにも', và cuối cùng là động từ chính kết thúc câu '立ち寄る予定です'.",
    "part_14.csv-2": "Cấu trúc 'かというと' dùng để đặt vấn đề 'nếu nói là/liệu có phải là...'. Chủ ngữ câu phụ '新プロジェクトが' kết hợp trạng từ 'すべて順調に' và động từ '進んでいる' tạo thành vế giả định, theo sau là 'かというと' để lật lại vấn đề ở phần vế sau nhằm phủ định '決してそうではない'.",
    "part_14.csv-3": "Mẫu 'nếu hỏi tại sao là vì (なぜかというと)' dùng để giải thích lý do giải quyết thắc mắc. Thành phần chủ ngữ và vị ngữ của vế nêu kết quả '選んだのは', đi kèm từ để hỏi 'なぜ' và cấu trúc liên kết 'かと''いうと' tạo thành cụm mở đầu cho mệnh đề giải thích lý do có cấu trúc tương ứng ở đuôi câu '～からです'.",
    "part_14.csv-4": "Cấu trúc 'V-たかと思うと' diễn tả một hành động/sự việc vừa mới xảy ra thì ngay lập tức có sự việc khác xuất hiện ngoài dự kiến. Cú pháp kết nối: Chủ ngữ của vế đầu 'システムの修正作業が', động từ thể quá khứ '完了した' kết hợp với cụm 'かと''思うと' để nối tiếp mạch thời gian sang vế sau chỉ sự việc bất ngờ xảy ra 'また別の重大なエラーが発生した'.",
    "part_14.csv-5": "Mẫu '～かと思うほど' biểu thị mức độ cao của một trạng thái, đến mức ngỡ như là như vậy. Trạng từ so sánh giả định 'まるで', vị ngữ giả định '先方の社員である' đi liền với cụm từ chỉ mức độ 'かと思うほど' làm bổ ngữ nhấn mạnh mức độ cho trạng thái năng lực ở vế sau 'クライアントの業務に精通している'.",
    "part_14.csv-6": "Ngữ pháp '～かと思えば' diễn tả hai sự việc hoặc đối tượng mang tính chất trái ngược hoặc đa dạng cùng tồn tại đồng thời. Mệnh đề định ngữ bổ nghĩa 'すぐに承諾する', danh từ chủ ngữ và động từ tồn tại '取引先がある', kết hợp cụm cấu trúc chuyển ý loại trừ/tương phản 'かと''思えば' để dẫn dắt tới đối tượng tương phản ở đuôi câu '強く反対する会社もある'.",
    "part_14.csv-7": "Cấu trúc '～かと思ったら' diễn tả một dự đoán hoặc trạng thái tưởng chừng sẽ xảy ra nhưng thực tế kết quả lại diễn biến ngược lại rất nhanh. Trạng ngữ chỉ mục đích '本日の会議に', động từ trạng thái giả định suy đoán '遅れる', cụm cấu trúc gắn kết 'かと''思ったら', trạng từ thời gian thực tế '定刻の10分前に' và hành động kính ngữ hoàn thành của khách hàng ở vế kết câu '到着された'.",
    "part_14.csv-8": "Vĩ từ cuối câu 'かな' dùng để biểu thị sự tự hỏi, phân vân hoặc hoài nghi nhẹ nhàng của người nói về một sự việc. Thành phần chỉ bối cảnh hành động '午後の会議で' bổ nghĩa cho danh từ tân ngữ của mệnh đề chính '使う資料', kế tiếp là cụm từ chỉ giới hạn phương thức 'これで', phó từ lượng '全部', vị ngữ trạng thái hiện tại 'そろっている' và kết bằng từ tình thái 'かな'.",
    "part_14.csv-10": "Trạng từ 'かならず' biểu thị một nguyên tắc hoặc yêu cầu bắt buộc, cần thiết phải làm gì. Tân ngữ bổ nghĩa 'メールを' đi với động từ '送信する' bổ trợ cho danh từ mốc thời gian '前には' làm tiền đề, trạng từ nhấn mạnh 'かならず' đi trước tân ngữ trực tiếp '添付ファイルを' và kết thúc bằng mẫu câu yêu cầu lịch sự tiêu chuẩn '確認してください'.",
    "part_14.csv-11": "Cấu trúc phủ định một phần 'かならずしも～とは限らない' diễn tả ý nghĩa không phải lúc nào cũng hoặc không nhất thiết là như vậy. Mệnh đề bổ nghĩa tính chất '費用が高い' đi liền chủ ngữ 'システムが', trạng từ liên kết đi trước của cấu trúc 'かならずしも', tiếp nối bổ ngữ đối tượng hướng tới '我が社の業務に', động từ chính vế phụ '合うとは' và từ phủ định đi kèm bắt buộc ở đuôi câu '限らない'.",
    "part_14.csv-12": "Ngữ pháp '～かねない' kết hợp với động từ nhóm thể Masu (bỏ masu) biểu thị một khả năng hoặc rủi ro cao dẫn đến một kết cục xấu. Từ chỉ loại hình định ngữ 'このような', tân ngữ bị tác động '機密書類を', hành động duy trì trạng thái tiêu cực '放置しておくと' đóng vai trò vế điều kiện, tiếp theo dẫn tới hậu quả tiêu cực '情報漏洩に' và động từ nguy cơ kết thúc câu '繋がりかねない'.",
    "part_14.csv-14": "Cấu trúc '～るがはやいか' diễn đạt một hành động diễn ra gần như ngay tức khắc sau khi hành động trước vừa kết thúc. Định ngữ sở hữu của tân ngữ '新商品の', cụm tân ngữ hành động '予約受付を', động từ nguyên mẫu dạng từ điển '開始する' đi liền trợ từ ngữ pháp kết nối 'がはやいか', dẫn trực tiếp đến kết quả đột biến không lường trước ở vế sau câu '注文が殺到してサーバーがダウンした'.",
    "part_14.csv-15": "Mẫu câu phán đoán khả năng 'かもしれない' (có thể/có lẽ) dựa trên một thông tin hoặc tình huống nhất định. Thành phần trạng từ chỉ định và danh từ chủ đề '今日の進捗報告会議は', mệnh đề chỉ nguyên nhân biện lý khách quan '議題が多いので', động từ chính diễn tiến hành vi '長引く' làm gốc liên kết trực tiếp với đuôi phán đoán kết thúc câu 'かもしれない'.",
    "part_14.csv-17": "Sự kết hợp giữa điều kiện giả định tương lai '～すれば' và ước tính khả năng xảy ra 'かもしれない'. Thành phần định ngữ sở hữu sản phẩm '製品の', tân ngữ của vế điều kiện hành động 'デザインを', động từ chia thể điều kiện thuận '変更すれば', tiếp sau là cụm từ chỉ mục đích kết quả tiềm năng '新規の顧客層を', động từ khả năng '獲得できる' đi kèm đuôi ước lượng dự báo 'かもしれない'.",
    "part_14.csv-19": "Mẫu khẩu ngữ công sở hội thoại nội bộ 'かもわからない' thể hiện tính không chắc chắn tương đương với かもしれない. Mệnh đề chỉ lý do khách quan làm rào cản hành động '出張の予定が入ったため', định ngữ thời gian vị trí đích đến '明日のセミナーに', động từ chia ở thể phủ định khả năng '参加できない' liên kết cụm từ biểu thị sự mông lung hoài nghi kết thúc bằng 'わからない'.",
    "part_14.csv-20": "Cấu trúc nghi vấn gián tiếp chứa từ để hỏi 'どこ' đi kèm cấu trúc nghi vấn phủ định kết nối danh từ 'か（も）わからない' để nhấn mạnh thực trạng thiếu thông tin. Thành phần bổ nghĩa định vị phạm vi '今回の', cụm danh từ chủ thể sự cố 'トラブルの原因が', nghi vấn từ vị trí không gian 'どこに', động từ trạng thái tồn tại mang tính nghi vấn lồng ghép 'あるかも', cụm phủ định kết hợp tính từ trạng thái bổ nghĩa danh từ đúc kết cuối câu 'わからない状況です'."
}

files = ['part_11.csv', 'part_12.csv', 'part_13.csv', 'part_14.csv', 'part_15.csv']
for file in files:
    path = os.path.join(dir_path, file)
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else -1
    if exp_idx == -1: exp_idx = len(headers) - 1
    
    changed = False
    for i, row in enumerate(r):
        if i == 0: continue
        key = f"{file}-{i}"
        
        # Remove leakages globally
        if len(row) > exp_idx:
            orig = row[exp_idx]
            new = orig.replace(" Câu được chia thành các phần tương ứng để kiểm tra khả năng sắp xếp trật tự từ ngữ pháp trong tiếng Nhật một cách chính xác nhất.", "")
            new = new.replace("Câu được chia thành các phần tương ứng để kiểm tra khả năng sắp xếp trật tự từ ngữ pháp trong tiếng Nhật một cách chính xác nhất.", "")
            if orig != new:
                row[exp_idx] = new
                changed = True
        
        # Apply specific fixes
        if key in fixes:
            new_exp = fixes[key]
            del row[exp_idx:]
            row.append(new_exp)
            changed = True
            
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            writer = csv.writer(f)
            writer.writerows(r)

print("Batch 3 of set 2 updated safely!")
