import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_4_literature'

rewrites = {
    # part_2
    "Phó từ phủ định 「あまり」 đi với thể phủ định ở cuối câu là 「ありません」 để mang ý nghĩa 「không... lắm」. Từ chỉ mức độ 「まだ」 (vẫn chưa) đứng trước 「あまり」 để bổ trợ ý nghĩa. Cụm chỉ đối tượng 「世間に」 (đối với xã hội/dư luận) đứng trước tính từ đuôi na chia thể phủ định 「有名では」 để bổ nghĩa cho tính từ này. Thứ tự đúng: まだ -> あまり -> 世間に -> 有名では.": "Phó từ phủ định 「あまり」 đi với thể phủ định 「ありません」 mang ý nghĩa \"không... lắm\". Từ chỉ mức độ 「まだ」 (vẫn chưa) đứng trước 「あまり」 để bổ trợ. Cụm chỉ đối tượng 「世間に」 (đối với dư luận) đi trước tính từ đuôi na ở dạng phủ định 「有名では」. Cấu trúc câu diễn tiến từ trạng thái chưa đến mức độ, rồi dẫn tới đối tượng và kết luận.",
    "Trạng từ 「あまりにも」 (quá đỗi, cực kỳ) đứng trước bổ nghĩa cho tính từ chia thể Te chỉ nguyên nhân là 「悲しくて」. Vế kết quả phía sau có danh từ sở hữu 「読者の」 bổ nghĩa cho tân ngữ 「涙を」, đi liền trước động từ kết thúc câu 「誘った」 (lấy đi nước mắt/làm rơi nước mắt). Thứ tự logic: あまりにも -> 悲しくて -> 読者の -> 涙を.": "Trạng từ 「あまりにも」 (quá đỗi) nhấn mạnh mức độ, bổ nghĩa cho tính từ chỉ nguyên nhân 「悲しくて」. Hệ quả theo sau là sự xúc động, với cụm sở hữu 「読者の」 làm rõ cho tân ngữ 「涙を」, dẫn tới động từ kết câu 「誘った」 (lấy đi nước mắt).",
    
    # part_5
    "いかにも thường đi kèm với らしい để thể hiện tính chất điển hình (đúng nghĩa là, quả nhiên là). 真実を追い求める (đuổi theo chân lý) là mệnh đề định ngữ bổ nghĩa cho danh từ 新聞記者 (nhà báo). 新聞記者らしかった (rất ra dáng nhà báo) kết hợp với いかにも tạo thành cấu trúc hoàn chỉnh bổ nghĩa cho chủ ngữ 彼のその冷徹な眼差しは (Ánh mắt lạnh lùng đóのanh ta). Thứ tự sắp xếp logic: いかにも -> đối tượng định ngữ -> danh từ -> らしかった.": "Trạng từ 「いかにも」 kết hợp với 「らしい」 mang nghĩa \"đúng nghĩa là, quả nhiên là\". Cụm 「真実を追い求める」 (theo đuổi sự thật) đóng vai trò định ngữ cho 「新聞記者」 (nhà báo). Phần này kết hợp thành 「いかにも真実を追い求める新聞記者らしかった」 (đúng chuẩn một nhà báo theo đuổi chân lý), bổ nghĩa cho chủ thể 「彼のその冷徹な眼差しは」 (ánh mắt lạnh lùng đó của anh ta).",
    "Cấu trúc Nいかんでは mang nghĩa tùy thuộc vào N mà... Ở đây, N là 動向 (xu hướng/động thái) được bổ nghĩa bởi 世論の (của dư luận). Cụm này định hình điều kiện dẫn đến vế sau: 内閣総辞職という (được gọi là nội các từ chức tập thể) bổ nghĩa cho danh từ 最悪の事態 ở phần Suffix. Thứ tự sắp xếp: 世論の -> 動向 -> いかんでは -> 内閣総辞職という -> Suffix.": "Cấu trúc 「Nいかんでは」 mang ý \"tùy thuộc vào N mà...\". Yếu tố quyết định ở đây là 「世論の動向」 (động thái của dư luận) đi kèm 「いかんでは」. Điều kiện này dẫn tới hệ quả phía sau: cụm 「内閣総辞職という」 (việc nội các từ chức tập thể) bổ nghĩa cho 「最悪の事態」 (tình huống tồi tệ nhất).",
    "いくら đóng vai trò nghi vấn từ chỉ số tiền không xác định. Động từ 払う chia sang thể giả định 払ったら (nếu trả...) biểu thị điều kiện. Tiếp theo là tân ngữ この原稿を (bản thảo này) đi trước động từ chính 買ってくれます (mua cho tôi). Đuôi câu hỏi là か. Thứ tự đúng: いくら -> 払ったら -> この原稿を -> 買ってくれます.": "Từ để hỏi 「いくら」 (bao nhiêu) chỉ số lượng không xác định. Kèm theo động từ điều kiện 「払ったら」 (nếu trả...), vế này làm nền để đưa ra câu hỏi. Tiếp đến, tân ngữ 「この原稿を」 (bản thảo này) đi liền với hành động 「買ってくれます」 và chốt bằng trợ từ nghi vấn 「か」.",
    "「Cấu trúc いくらでも biểu thị số lượng vô hạn, không giới hạn (bao nhiêu cũng có/được). 金なら (nếu là tiền) làm chủ đề được nhấn mạnh, theo sau bởi trạng từ いくらでも và động từ tồn tại ある để chỉ sự dồi dào. Cụm trích dẫn kết thúc bằng と đi với động từ 言って. Thứ tự logic: 金なら -> いくらでも -> ある」と -> 言って.": "Cấu trúc 「いくらでも」 biểu thị mức độ vô hạn (bao nhiêu cũng được). Chủ đề 「金なら」 (nếu là tiền) đi cùng 「いくらでもある」 (có bao nhiêu cũng có) nhằm nhấn mạnh sự dồi dào. Toàn bộ câu trích dẫn này được đóng lại bằng 「と」 đi kèm hành động 「言って」.",
    "Cấu trúc いくら～といっても mang ý nghĩa cho dù nói là... đi chăng nữa. いくら mở đầu mệnh đề. Chủ ngữのmệnh đề phụ là 電子書籍が (sách điện tử). Tính từ đuôi na 便利 kết hợp với だといっても thành 便利だといっても (cho dù nói là tiện lợi). Thứ tự đúng: いくら -> 電子書籍が -> 便利だと -> いっても.": "Cấu trúc 「いくら～といっても」 mang ý nghĩa nhượng bộ (cho dù nói là...). 「いくら」 mở đầu, theo sau là chủ thể 「電子書籍が」 (sách điện tử). Vế này kết thúc bằng tính từ 「便利」 đi cùng cụm nhượng bộ 「だといっても」 (cho dù nói là tiện lợi).",
    "Cấu trúc いくら～からといって diễn tả ý cho dù lý do là... thì cũng không được làm vế sau. いくら kết hợp với mệnh đề nguyên nhân 仕事が忙しい (công việc bận rộn). Đuôi mệnh đề là からといって (dẫu nói là vì lý do...). Thứ tự logic: いくら -> 仕事が -> 忙しい -> からといって.": "Cấu trúc 「いくら～からといって」 bác bỏ việc vin vào một lý do (cho dù lý do là... thì cũng không...). 「いくら」 đi kèm lý do 「仕事が忙しい」 (công việc bận rộn), và khép lại vế đầu bằng 「からといって」 để dẫn sang vế phủ định phía sau.",
    "Cấu trúc ～でなくてはいけない đi sau danh từ để chỉ nghĩa phải là/bắt buộc phải là... Trạng từ 常に (luôn luôn) đi trước để bổ nghĩa cho trạng thái. 中立な (trung lập) là tính từ đuôi na bổ nghĩa cho danh từ 立場 (lập trường/vị thế). Thứ tự logic: 常に -> 中立な -> 立場で -> なくてはいけない.": "Cấu trúc 「～でなくてはいけない」 biểu thị sự bắt buộc (phải là...). Trạng từ 「常に」 (luôn luôn) nhấn mạnh tính liên tục của trạng thái 「中立な立場」 (lập trường trung lập). Từ đó nối với cấu trúc bắt buộc 「でなくてはいけない」 để tạo thành vế hoàn chỉnh.",
    "Danh từ 大震災 (trận động đất lớn) đi kèm chỉ thị từ あの (đó). Cấu trúc N以後 (kể từ sau N) gắn vào sau danh từ để tạo trạng ngữ chỉ thời gian. Vế sau bắt đầu bằng 政府の (của chính phủ) bổ nghĩa cho danh từ 防災対策 (biện pháp phòng chống thiên tai) ở phần Suffix. Thứ tự sắp xếp: あの -> 大震災 -> 以後、 -> 政府の.": "Cấu trúc 「N以後」 đóng vai trò trạng ngữ chỉ thời gian (kể từ sau...). Bắt đầu bằng mốc thời gian 「あの大震災」 (trận động đất lớn đó) đi kèm 「以後」. Mốc thời gian này mở ra vế sau, với định ngữ 「政府の」 (của chính phủ) bổ nghĩa cho 「防災対策」 (biện pháp phòng chống thiên tai).",
    "Trạng từ 以後 đứng đầu câu trích dẫn để chỉ mốc thời gian từ nay về sau. Cụm danh từ このような不祥事 (vụ bê bối như thế này) làm tân ngữ đi với trợ từ を. Động từ chính là 起こす (gây ra) chia sang thể cấm đoán/khuyên can mạnh mẽ 起こしてはならない (không được phép gây ra). Thứ tự đúng: 以後 -> このような -> 不祥事を -> 起こしてはならない.": "Trạng từ 「以後」 đặt ở đầu lời trích dẫn chỉ mốc thời gian (từ nay về sau). Lời cảnh báo hướng tới 「このような不祥事を」 (vụ bê bối như thế này), kết hợp với hành động mang tính cấm đoán mạnh mẽ 「起こしてはならない」 (không được phép gây ra).",
    "Trạng từ いささか (hơi/một chút, mang sắc thái trang trọng, văn viết) bổ nghĩa cho tính từ 唐突すぎる (quá đột ngột). 読者にとって (đối với độc giả) là cụm giới từ chỉ đối tượng cảm nhận. Cụm 唐突すぎる感 (cảm giác quá đột ngột) làm tân ngữ cho 否めない (không thể phủ nhận). Thứ tự logic: 読者にとって -> いささか -> 唐突すぎる -> 感が否めない.": "Trạng từ 「いささか」 (hơi, một chút) mang sắc thái trang trọng. Hướng tới đối tượng 「読者にとって」 (đối với độc giả), 「いささか」 làm dịu đi tính từ 「唐突すぎる」 (quá đột ngột). Cảm giác này kết tụ lại ở cụm 「感が否めない」 (không thể phủ nhận cảm giác đó).",
    
    # part_12
    "「今日の」 bổ nghĩa cho danh từ 「外」 (ngoài trời). 「外はとても」 (ngoài trời rất) đi kèm với tính từ 「寒いですが」 (lạnh nhưng - biểu thị quan hệ tương phản) đóng vai trò kết thúc vế thứ nhất. Vế thứ hai bắt đầu với chủ đề 「部屋の中は」 (bên trong phòng thì) đi kèm tính từ 「静かで」 (yên tĩnh và - nối tiếp trạng thái) bổ nghĩa cho vị ngữ cuối cùng ở Suffix 「暖かいです」 (ấm áp). Thứ tự đúng: 今日の (Prefix) + 外はとても+ 寒いですが、+ 部屋の中は+ 静かで+ 暖かいです。(Suffix).": "Câu sử dụng quan hệ tương phản giữa hai không gian. Vế đầu nói về thời tiết 「今日の外はとても寒いですが」 (ngoài trời hôm nay rất lạnh nhưng...). Vế sau đối lập lại, chuyển hướng sang không gian bên trong 「部屋の中は静かで」 (bên trong phòng thì yên tĩnh và...) để dẫn đến trạng thái tích cực 「暖かいです」 (ấm áp).",
    
    # part_13
    "Cấu trúc 「Nのかぎり」 biểu thị ý nghĩa 「với tất cả/ toàn bộ N」. Ở đây, 「知恵の限り」(tất cả trí khôn) đi với động từ 「尽くす」(vắt kiệt, dốc hết) chia thể Te là 「尽くして」 để nối câu. Cụm 「難解な謎に」(vào câu đố hóc búa) là đối tượng bổ nghĩa cho động từ hành động 「挑む」(thử thách, đương đầu) ở cuối câu. Thứ tự logic: 知恵の -> 限りを -> 尽くしてその -> 難解な謎に。": "Cấu trúc 「Nのかぎり」 diễn tả ý \"với tất cả N\". Mệnh đề khởi đầu bằng sự nỗ lực 「知恵の限りを尽くして」 (vắt kiệt mọi trí khôn). Nỗ lực này nhằm hướng tới một đối tượng cụ thể là 「その難解な謎に」 (vào câu đố hóc búa đó) để thực hiện hành động đương đầu ở cuối câu.",
    "Động từ phức ghép 「隠し続ける」(tiếp tục che giấu) chia sang thể 「隠し続けている」 kết hợp với 「限り」 tạo thành cấu trúc 「Vている限り」 (chừng nào còn...). Phía trước cần có tân ngữ 「この真実を」(sự thật này). Vế sau chỉ kết quả tất yếu, nơi chốn nhận trạng thái là 「私たちの心に」(đến với tâm hồn chúng ta) đi trước chủ ngữ 「平和は訪れない」(hòa bình không đến). Thứ tự logic: 隠し -> 続けている -> 限り -> 私たちの心に。": "Cấu trúc 「Vている限り」 mang nghĩa \"chừng nào còn...\". Hành động được duy trì là 「隠し続けている限り」 (chừng nào còn tiếp tục giấu giếm) áp dụng cho tân ngữ 「この真実を」. Hệ quả tất yếu kéo theo được chỉ rõ hướng tác động là 「私たちの心に」 (vào tâm hồn chúng ta), dẫn tới việc \"hòa bình không đến\".",
    "Cấu trúc 「R-かけのN」 biểu thị một hành động đang làm dở thì dừng lại, bổ nghĩa cho danh từ phía sau. Ở đây, động từ 「読む」(đọc) bỏ masu thành 「読み」 kết hợp với 「かけの」 để bổ nghĩa cho danh từ 「小説が」(cuốn tiểu thuyết). Trạng từ 「静かに」(lặng lẽ, yên tĩnh) đứng trước động từ bị động 「置かれていた」(được đặt) ở phần Suffix. Thứ tự sắp xếp: 読み -> かけの -> 小説が -> 静かに。": "Cấu trúc 「R-かけのN」 biểu thị trạng thái dang dở. Hành động \"đọc dở\" 「読みかけの」 làm định ngữ làm rõ cho 「小説が」 (cuốn tiểu thuyết). Trạng thái của cuốn sách này được miêu tả qua phó từ 「静かに」 (một cách lặng lẽ) đi liền với hành động \"được đặt\" ở cuối câu.",
    "Cấu trúc 「V-たが最後」 mang ý nghĩa 「một khi đã... thì kết cục (xấu) là không thể tránh khỏi」. Trạng từ 「一度」(một khi, một lần) đi trước động từ thể quá khứ 「迷い込んだ」(đã lạc vào). Tiếp theo là liên từ kết hợp 「が」 và danh từ 「最後」, đi kèm trạng từ phủ định 「二度と」(không bao giờ... lần thứ hai) để bổ nghĩa cho vế phủ định 「抜け出すことはできない」 ở Suffix. Thứ tự logic: 一度 -> 迷い込んだ -> が -> 最後、二度と。": "Cấu trúc 「V-たが最後」 cảnh báo hệ quả tất yếu (một khi đã...). Phó từ 「一度」 (một khi) nhấn mạnh hành động lầm lỡ 「迷い込んだが最後」 (đã lỡ lạc vào thì...). Điều này dẫn tới sự tuyệt vọng ở vế sau, mở đầu bằng cụm phủ định 「二度と」 (không bao giờ... nữa).",
    "Cấu trúc 「V-るかたわらで」 chỉ không gian vật lý bên cạnh một vật hay sự việc đang diễn ra (そば). Ở đây, chủ ngữのmệnh đề bổ ngữ là 「暖炉の」(lò sưởi - sử dụng の thay cho が trong mệnh đề định ngữ) đi trước động từ 「燃える」(cháy). Cụm này bổ nghĩa cho 「かたわらで」(ở bên cạnh). Sau đó, tính từ 「古い」(cũ kỹ) bổ nghĩa cho danh từ 「羊皮紙の書物」 ở Suffix. Thứ tự sắp xếp: 暖炉の -> 燃える -> かたわらで、 -> 古い。": "Cấu trúc không gian 「かたわらで」 (ở bên cạnh) dùng để miêu tả vị trí tương quan. Bối cảnh 「暖炉の燃える」 (lò sưởi đang cháy) làm định ngữ cho 「かたわらで」. Bên cạnh ngọn lửa đó, tính từ 「古い」 xuất hiện để bổ nghĩa cho \"cuốn sách da cừu\" ở cuối câu.",
    "Cấu trúc 「V-るかたわら」 thể hiện việc song song thực hiện một công việc phụ bên cạnh công việc chính (副次的動作). Định ngữ 「本業の」(của nghề nghiệp chính) bổ nghĩa cho tân ngữ 「会社を」(công ty). Động từ chính 「経営する」(điều hành, kinh doanh) bổ nghĩa trực tiếp cho liên từ 「かたわら」. Thứ tự đúng: 本業の -> 会社を -> 経営する -> かたわら、。": "Cấu trúc 「かたわら」 chỉ sự song hành giữa hai công việc. Công việc chính 「本業の会社を経営する」 (điều hành công ty chính) đóng vai trò nền tảng. Tiếp nối bằng 「かたわら」 (bên cạnh việc đó), tạo tiền đề cho việc giới thiệu công việc phụ ở vế sau.",
    "Cấu trúc 「R-がち/Nがち」 thể hiện xu hướng dễ xảy ra một trạng thái tiêu cực. Ở đây, định ngữ 「自分の」(của bản thân) bổ nghĩa cho danh từ phương tiện 「頭で」(bằng đầu). Cụm động từ danh từ hóa 「考えることを」(việc suy nghĩ) làm tân ngữ cho động từ 「忘れる」(quên). Động từ 「忘れる」 bỏ masu thành 「忘れ」 để kết hợp với hậu tố 「がちである」 ở phần Suffix. Thứ tự đúng: 自分の -> 頭で -> 考えることを -> 忘れ。": "Hậu tố 「がち」 chỉ một thói quen hay xu hướng dễ xảy ra. Việc 「自分の頭で考えることを」 (việc suy nghĩ bằng cái đầu của chính mình) trở thành tân ngữ của hành động quên. Động từ \"quên\" chia thành 「忘れ」 để dễ dàng kết dính với 「がちである」 (dễ quên) ở cuối.",
    "Cấu trúc 「R-がち」 dùng với động từ thể liên dụng (R-stem) chỉ xu hướng tiêu cực dễ xảy ra. Tân ngữ 「本質を」(bản chất) đi kèm với động từ phức 「見失う」(đánh mất, thất lạc) chia thể liên dụng là 「見失い」. Hậu tố 「がち」 đóng vai trò như một tính từ đuôi na, kết hợp với liên từ chỉ nguyên nhân 「なので」 để dẫn dắt đến kết luận ở phần Suffix 「注意が必要だ」(cần chú ý). Thứ tự sắp xếp: 本質を -> 見失い -> がち -> なので。": "Cấu trúc 「R-がち」 nêu bật một nguy cơ dễ mắc phải. Việc \"dễ đánh mất bản chất\" 「本質を見失いがち」 đóng vai trò như nguyên nhân, kết nối với liên từ 「なので」 (vì vậy nên). Trạng thái này đòi hỏi sự cảnh giác 「注意が必要だ」 ở phía sau.",
    "Phó từ chỉ thời gian 「かつて」(đã từng trong quá khứ) đứng đầu mệnh đề bổ ngữ định ngữ để bổ nghĩa cho động từ 「満ちていた」(đã tràn ngập). Trạng từ chỉ nơi chốn 「ここに」(ở đây) xác định không gianのtrạng thái. Động từ 「満ちていた」 bổ nghĩa cho danh từ chỉ người 「人々の」(của mọi người), từ đó tạo nên cụm chủ ngữ 「人々の歓声が」(tiếng reo hòのmọi người) cho vế sau ở phần Suffix. Thứ tự logic: かつて -> 여기에 -> 満ちていた -> 人々の。": "Phó từ 「かつて」 (đã từng) gợi nhắc bối cảnh quá khứ. Nó định hình không gian 「ここに」 (ở nơi đây) cùng trạng thái huy hoàng 「満ちていた」 (từng ngập tràn). Tất cả trở thành định ngữ bổ trợ cho hình ảnh 「人々の歓声が」 (tiếng reo hò của mọi người) ở phía cuối câu.",
    
    # part_14
    "Cấu trúc nhượng bộ 「確かに～かもしれないが」 thể hiện sự đồng ý một phần (「đúng là có thể... nhưng...」). Phó từ 「確かに」 đứng trước chủ ngữ 「効果が」 và động từ tồn tại 「ある」. Cụm động từ 「ある」 kết hợp với đuôi phán đoán kết hợp liên từ nghịch đối 「かもしれないが」 để mở đầu cho vế tương phản ở cuối câu. Thứ tự sắp xếp đúng là 1-2-3-4.": "Cấu trúc 「確かに～かもしれないが」 diễn tả sự nhượng bộ (đúng là có thể... nhưng). Mở đầu bằng sự ghi nhận 「確かに効果がある」 (đúng là có hiệu quả). Sự thừa nhận này gắn với phán đoán lấp lửng 「かもしれないが」 để tạo bước đệm cho ý phản biện ở vế sau.",

    # part_16
    "Cấu trúc 「からといって」 (nói thế không có nghĩa là) đi với phủ định 「とは限らない」 (không hẳn là) ở cuối câu. Thứ tự sắp xếp là: 「書いてある」 (được viết) bổ nghĩa cho lý do -> 「からといって」 (dẫu nói là) -> 「すべてが」 (tất cả mọi điều) làm chủ ngữ cho vế sau -> 「正しいとは」 đi với 「限らない」 để tạo thành cụm hoàn chỉnh mang nghĩa 「không hẳn là đúng」.": "Cấu trúc 「からといって」 kết hợp phủ định 「とは限らない」 để phản bác lối suy nghĩ tuyệt đối hóa. Dù có lý do 「書いてあるからといって」 (cho dù nói là có viết ra đấy), thì chủ thể 「すべてが」 (tất cả) vẫn đi tới sự dè dặt 「正しいとは限らない」 (chưa chắc đã đúng).",

    # part_18
    "「くらい」 biểu thị mức độ tối thiểu, đi sau danh từ 「真実」 (sự thật). Trình tự logic: 1. Đưa ra đối tượng tối thiểu ở đầu câu (真実くらい) -> 2. Hành động không cần thiết đối với mức độ đó (わざわざ言葉にせずとも - dù không cần cố công diễn tả thành lời) -> 3. Chủ ngữ thực hiện hành động làm sáng tỏ (彼女の澄んだ瞳が) -> 4. Vị ngữ kết thúc câu (すべてを物語っていた - đã nói lên tất cả).": "Trợ từ 「くらい」 nhấn mạnh mức độ tối thiểu (ít nhất là). Ở đây 「真実くらい」 (chí ít là sự thật) mở đầu, đi kèm sự phủ nhận nỗ lực 「わざわざ言葉にせずとも」 (dù không cần cất lời). Hình ảnh trung tâm 「彼女の澄んだ瞳が」 (đôi mắt trong veo của cô) dẫn đến nhận định 「すべてを物語っていた」 (đã nói lên tất cả).",
    "Cấu trúc 「～のは～ぐらいのものだ」 dùng để nhấn mạnh trường hợp duy nhất hoặc cực kỳ hiếm hoi. Trình tự logic: 1. Nêu sự việc hiếm hoi làm chủ ngữ danh từ hóa bằng 「のは」 (涙を流したのは) -> 2. Định ngữ bổ nghĩa cho thời điểm (あの凄惨な事件の) -> 3. Mệnh đề định ngữ chỉ hành động (遺品を整理した) -> 4. Kết cấu nhấn mạnh giới hạn thời gian (時ぐらいのものだ).": "Cấu trúc 「～のは～ぐらいのものだ」 nhấn mạnh sự hiếm hoi. Việc biểu lộ cảm xúc 「涙を流したのは」 (lần rơi nước mắt đó) bị giới hạn khắt khe. Nó chỉ thuộc về khoảnh khắc 「あの凄惨な事件の遺品を整理した時ぐらいのものだ」 (cỡ như lúc thu dọn di vật của vụ án thê thảm đó mà thôi).",
    "「Nの結果」 biểu thị kết quảのmột hành động, sự việc trước đó. Trình tự logic: 1. Tính từ bổ nghĩa cho danh từ khảo sát (綿密な) -> 2. Cụm danh từ chỉ sự việc hành động và từ kết quả (世論調査の結果、) -> 3. Cụm bổ nghĩa cho chủ ngữ (新法案に対する) -> 4. Chủ ngữ và vị ngữ chỉ kết quả thực tế xuất hiện (国民の強い反発が / 浮き彫りになった).": "Cấu trúc 「Nの結果」 trình bày hệ quả của một quá trình. Sau cuộc khảo sát 「綿密な世論調査の結果」 (kết quả của cuộc khảo sát dư luận kỹ lưỡng), một thực tế lộ rõ. Sự thật đó là 「新法案に対する国民の強い反発が」 (sự phản đối mạnh mẽ của người dân đối với dự luật) và chốt lại bằng 「浮き彫りになった」 (trở nên rõ rệt).",
    "「結局」 (kết cục, cuối cùng thì) dùng ở vị trí phó từ trước cụm hành động kết quả cuối cùngのmột chuỗi diễn biến. Trình tự logic: 1. Chủ ngữ và trạng huống dẫn dắt (容疑者は厳しい取り調べの末に) -> 2. Phó từ chỉ kết cục (結局) -> 3. Tân ngữのhành động tự thú (すべての罪を) -> 4. Kết quả chung cuộc diễn ra ngoài ý muốn (自白することになった).": "Phó từ 「結局」 (kết cục) báo trước một đoạn kết cuối cùng. Quá trình 「容疑者は厳しい取り調べの末に」 (nghi phạm sau quá trình tra hỏi gắt gao) đi đến 「結局」. Kết cục không thể đảo ngược là 「すべての罪を自白することになった」 (cuối cùng đã phải thú nhận mọi tội lỗi).",
    "「決して～ない」 cấu trúc phủ định mạnh mẽ (quyết không/tuyệt đối không). Trình tự logic: 1. Cụm danh từ tân ngữ được định ngữ hóa (あの凄惨な戦場の記憶を) -> 2. Chủ ngữ kèm phó từ phủ định đi trước (私たちは決して) -> 3. Trạng ngữ chỉ đối tượng hướng tới (後世に) -> 4. Vị ngữ phủ định bắt buộc tương thích với 「決して」 (忘れてはならない).": "Cấu trúc 「決して～ない」 mang thái độ phủ định dứt khoát. Tân ngữ 「あの凄惨な戦場の記憶を」 (ký ức thảm khốc của chiến trường đó) là đối tượng cần lưu giữ. Bằng ý chí kiên định 「私たちは決して後世に」 (chúng ta tuyệt đối đối với thế hệ sau...), câu chốt bằng lệnh cấm 「忘れてはならない」 (không được phép lãng quên).",
    "「けど」 đặt ở đầu câu thứ hai làm liên từ biểu thị quan hệ nghịch đối mang tính văn nói/bình dân, chuyển ý giữa hai câu độc lập. Trình tự logic: 1. Phát biểu câu đầu (結末が悲しすぎる。) -> 2. Liên từ nối ý nghịch (けど、) -> 3. Chủ ngữ bổ nghĩaのcâu sau (それが人生の) -> 4. Tân ngữ và vị ngữ phản biện (真実を / 描いているとも言える).": "Liên từ 「けど」 (nhưng mà) tạo nhịp chuyển ý tương phản trong văn nói. Sau đánh giá 「結末が悲しすぎる」 (kết cục buồn quá), 「けど」 mở ra sự thông cảm. Thực tế phũ phàng 「それが人生の真実を描いている」 (nó vẽ lên sự thật của đời người) được thừa nhận bằng 「とも言える」.",
    "「～けど」 nối hai mệnh đề đối lập trong cùng một câu. Mệnh đề 1 là nhận định ban đầu mang tính thừa nhận, mệnh đề 2 đưa ra nghi vấn. Trình tự logic: 1. Chủ đề câu (この記事は) -> 2. Nội dung mệnh đề thứ nhất (真実を伝えていると) -> 3. Động từ nhận định đi kèm trợ từ nối nghịch 「けど」 (思うけど、) -> 4. Ý kiến phản biện ngược lại ở vế sau (少し偏見が / 混ざっている気もする).": "Trợ từ 「けど」 nối hai quan điểm đối nghịch. Dù thừa nhận 「この記事は真実を伝えていると思うけど」 (tôi nghĩ bài báo này nói đúng sự thật đấy, nhưng...), người nói vẫn gợn chút nghi ngờ. Phần sau 「少し偏見が混ざっている気もする」 (có cảm giác xen lẫn chút định kiến) phơi bày sự hoài nghi đó.",
    "「けれど」 đóng vai trò liên từ nối hai câu có nghĩa trái ngược, trang trọng hơn 「けど」. Trình tự logic: 1. Phát biểu câu thứ nhất về lời hứa (政府は財政再建を公約した。) -> 2. Liên từ nghịch đảo đầu câu sau (けれど、) -> 3. Định từ bổ nghĩa cho danh từ sau (具体的な) -> 4. Đối tượng và hành động phủ định thực tế trái ngược (増税案は / 提示しなかった).": "Liên từ 「けれど」 tạo bước ngoặt có phần trang trọng hơn 「けど」. Dù lời hứa 「政府は財政再建を公約した」 (chính phủ đã cam kết tái thiết tài chính) có vẻ vĩ mô. Tuy nhiên 「けれど」 lật lại vấn đề: thực tế 「具体的な増税案は提示しなかった」 (chưa hề đưa ra dự luật tăng thuế cụ thể).",
    "「けれども」 là liên từ nghịch đối mang tính trang trọng, văn viết cao hơn 「けれど」. Trình tự logic: 1. Kết quả tích cực ban đầu ở câu 1 (大きな反響を呼んだ。) -> 2. Liên từ chỉ sự đối lập ở đầu câu 2 (けれども、) -> 3. Cụm danh từ định hướng địa điểm (被災地の) -> 4. Vị ngữ chỉ kết quả thực tế không mong muốn ở câu 2 (真の救済には / 繋がらなかった).": "Liên từ 「けれども」 thể hiện sự nghịch lý ở mức độ trang trọng nhất. Mặc dù 「大きな反響を呼んだ」 (đã gây tiếng vang lớn), thì 「けれども」 đưa về thực tế đắng cay. Đó là 「被災地の真の救済には繋がらなかった」 (lại chẳng dẫn tới sự cứu viện thực sự cho vùng thiên tai).",
    "「現在」 đóng vai trò danh từ chỉ mốc thời gian/bối cảnh hiện tại sau một định ngữ dài. Trình tự logic: 1. Chủ ngữのmệnh đề định nghĩa (インターネットが) -> 2. Mệnh đề trạng thái hoàn thành định nghĩa cho bối cảnh (社会インフラとなった) -> 3. Mốc thời gian bối cảnh (現在、) -> 4. Chủ thể và vấn đề đang được đặt ra ở hiện tại (新聞メディアの果たすべき / 役割が問い直されている).": "Danh từ 「現在」 xác định bối cảnh thời gian. Trong bối cảnh 「インターネットが社会インフラとなった現在」 (hiện nay, khi internet đã trở thành hạ tầng xã hội), vai trò của một thế lực cũ được khơi lại. Cụm 「新聞メディアの果たすべき役割が」 (vai trò báo giấy cần gánh vác) đi kèm 「問い直されている」 (đang bị đặt dấu hỏi).",
    "「Nごし」 chỉ không gian trung gian qua đó hành động được thực hiện (qua gương một chiều). Trình tự logic: 1. Chủ ngữ và vị trí trung gian (老刑事は取調室の) -> 2. Phương tiện không gian thực hiện hành động (マジックミラーごしに、) -> 3. Cụm từ định ngữ chỉ đối tượng bị quan sát (無表情な容疑者の) -> 4. Tân ngữ và vị ngữ chỉ hành động quan sát chi tiết (様子を / じっと観察していた).": "Hậu tố 「ごし」 diễn tả việc vượt qua một màn chắn. Việc quan sát 「老刑事は取調室のマジックミラーごしに」 (lão cảnh sát nhìn qua tấm gương một chiều của phòng hỏi cung) cho thấy sự âm thầm. Mục tiêu là 「無表情な容疑者の様子を」 (bộ dạng vô cảm của nghi phạm) với động tác 「じっと観察していた」 (chăm chú quan sát).",
    "「Nごし」 chỉ khoảng thời gian kéo dài liên tục để thực hiện một việc. Trình tự logic: 1. Chủ ngữ (作家は) -> 2. Trạng từ thời gian kéo dài bổ nghĩa cho danh từ sau (十数年ごしの) -> 3. Danh từ hành động và quá trình tích lũy (執筆活動を経て、) -> 4. Trạng từ thời gian kết quả và tân ngữ vĩ ngữ chính kết thúc câu (ついに生涯の傑作となる / 大河小説を書き上げた).": "Hậu tố 「ごし」 diễn tả độ dài và sự bền bỉ của thời gian. Nỗ lực 「作家は十数年ごしの執筆活動を経て」 (nhà văn trải qua hoạt động sáng tác suốt hơn chục năm trời) cuối cùng cũng hái quả ngọt. Kết tinh là 「ついに生涯の傑作となる大河小説を書き上げた」 (cuối cùng đã hoàn thành bộ trường thiên tiểu thuyết, kiệt tác để đời).",
    "「こそ」 nhấn mạnh vào danh từ chỉ địa điểm/bối cảnh (現代社会に) nhằm khẳng định đây chính là nơi cần thiết nhất. Trình tự logic: 1. Định ngữ chỉ trạng tháiのbối cảnh (この混迷を極める) -> 2. Danh từ chỉ bối cảnh kèm trợ từ nhấn mạnh (現代社会にこそ、) -> 3. Chủ ngữ mệnh đề phụ (文学が持つ) -> 4. Chủ ngữ chính và vị ngữ thể hiện nhu cầu thiết yếu (想像力の価値が / 求められている).": "Trợ từ 「こそ」 được dùng để nhấn mạnh tính duy nhất. Môi trường 「この混迷を極める現代社会にこそ」 (chính trong xã hội hiện đại cực kỳ nhiễu nhương này), một thứ tưởng như vô hình lại được tôn vinh. Đó là 「文学が持つ想像力の価値が求められている」 (giá trị sức tưởng tượng của văn học đang được đòi hỏi).",
    "「Nでこそあれ」 biểu thị cấu trúc nhượng bộ/khẳng định cực đoan: 「chỉ có thể là A chứ quyết không thể là B」. Trình tự logic: 1. Chủ đề phát biểu (彼の告発は、) -> 2. Thừa nhận bản chất duy nhất đúng bằng cấu trúc nhượng bộ (真実の追求でこそあれ、) -> 3. Phó từ phủ định đi trước (決して) -> 4. Loại trừ khả năng đối lập ở vế sau (個人的な恨みによる / ものではない).": "Cấu trúc 「Nでこそあれ」 thừa nhận bản chất thực sự và loại bỏ suy đoán lệch lạc. Lời cáo buộc 「彼の告発は、真実の追求でこそあれ」 (lời tố cáo của anh ấy chính là sự theo đuổi chân lý) phủ định đanh thép ác ý. Nó chặn đứng nghi ngờ bằng 「決して個人的な恨みによるものではない」 (tuyệt đối không phải do tư thù cá nhân).",
    "「Nこそ～が」 thể hiện sự nhượng bộ đối lập: 「tuy cái này thì... nhưng...」. Trình tự logic: 1. Chủ đề câu (この記事は、) -> 2. Điểm hạn chế được đưa ra nhượng bộ bằng cấu trúc nhấn mạnh (文体こそ硬いのだが、) -> 3. Tân ngữ chínhのmệnh đề khen ngợi phía sau (事件の本質を) -> 4. Trạng từ bổ nghĩa và vị ngữ thể hiện giá trị cốt lõi thực sự (見事に / 穿っている).": "Cấu trúc 「Nこそ～が」 vạch ra khiếm khuyết nhỏ để tôn lên ưu điểm lớn. Bài báo 「この記事は、文体こそ硬いのだが」 (bài báo này, văn phong có phần cứng nhắc thật đấy nhưng...) lại tỏa sáng nhờ chất lượng nội dung. Yếu tố cốt lõi 「事件の本質を見事に穿っている」 (đã nhìn thấu xuất sắc bản chất sự việc) làm lu mờ đi nhược điểm kia."
}

for i in range(2, 19):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 4 Batch 1.1 (parts 2-18) manually reviewed and rewritten successfully!")
