import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_4_literature'

rewrites = {
    # part_53
    "Cấu trúc ngữ pháp N2 「と考えられる」 thể hiện sự suy đoán hoặc đánh giá mang tính khách quanのngười viết (thường dùng trong văn viết và báo chí). Thứ tự sắp xếp như sau: 1. Danh từ chủ thể hành động 「立ち上げ」 đi với trợ từ 「は」 làm chủ ngữ cho vế phụ. 2. Phó từ chỉ mức độ 「極めて」 (cực kỳ) đứng trước để bổ nghĩa cho tính từ 「困難である」. 3. Thể khẳng định trang trọng 「困難である」 kết hợp trực tiếp với cấu trúc phán đoán 「と考えられ」 để tạo tính liên kết với vế sau.": "Cấu trúc 「と考えられる」 diễn đạt suy đoán mang tính khách quan, thường gặp trong báo chí. Chủ đề 「立ち上げは」 (việc khởi động thì) mở đầu câu. Mức độ 「極めて」 (cực kỳ) đi kèm với nhận định 「困難である」 (là khó khăn). Nhận định này kết hợp trực tiếp với 「と考えられ」 (được cho là) để nối sang vế tiếp theo.",
    "Cấu trúc N1 「〜ものと考えられる」 biểu thị sự suy đoán, kết luận mang tính logic và khách quan dựa trên chứng cứ cụ thể (thường dùng trong văn phong báo cáo điều tra). Thứ tự sắp xếp câu: 1. Danh từ bổ nghĩa 「内部」 liên kết với danh từ 「事情」 qua trợ từ 「の」. 2. Cụm danh từ chỉ tính chất 「事情に詳しい」 đứng liền trước để bổ nghĩa trực tiếp cho danh từ chỉ người 「人物」. 3. Thể khẳng định trang trọng 「である」 kết hợp trực tiếp danh từ 「人物」 với cấu trúc phán đoán logic 「ものと考えられる」.": "Cấu trúc 「ものと考えられる」 là kết luận logic dựa trên chứng cứ khách quan. Định ngữ 「内部の」 (thuộc về nội bộ) đi cùng 「事情に詳しい」 (am hiểu tình hình) để làm rõ cho 「人物」 (nhân vật). Trạng thái 「人物である」 (là nhân vật) gắn với 「ものと考えられる」 (được giới điều tra suy đoán là) để hoàn thiện câu.",
    "Cấu trúc ngữ pháp N4 「Nのとき」 chỉ thời điểm diễn ra một trạng thái trong quá khứ. Thứ tự sắp xếp: 1. Danh từ chủ thể 「子供」 kết hợp với trợ từ sở hữu/định ngữ 「の」 để bổ nghĩa cho danh từ chỉ thời gian 「とき」. 2. Vế chỉ mốc thời gian 「子供のとき」 đứng ngay sau chủ ngữ phụ 「私が」. 3. Danh từ 「この川」 đi kèm trợ từ đề tài 「は」 làm chủ ngữ chính cho mệnh đề mô tả cảnh vật phía sau.": "Cấu trúc 「Nのとき」 xác định mốc thời gian xảy ra sự việc. Chủ thể 「私が」 (tôi) gắn liền với thời điểm 「子供のとき」 (hồi còn là những đứa trẻ). Bối cảnh này dẫn vào chủ đề chính của câu tả cảnh: 「この川は」 (con sông này thì).",
    "Cấu trúc N1 「Nときたひには」 (văn nói cổ, thường xuất hiện trong tiểu thuyết để phê phán, than phiền về một đối tượng). Thứ tự sắp xếp câu: 1. Từ chỉ định 「あの」 bổ nghĩa cho đối tượng bị phàn nàn 「大作家」. 2. Đối tượng 「大作家」 liên kết trực tiếp với cụm nhấn mạnh 「ときたひには」. 3. Trạng ngữ thời gian 「締め切り直前に」 đi trước cấu trúc điều kiện phủ định 「ならないと」 (nếu không... thì không).": "Cấu trúc phàn nàn 「ときたひには」 (nhắc tới... thì thôi rồi) mang âm hưởng văn nói cổ. Đối tượng bị nhắm đến là 「あの大作家」 (vị đại văn hào đó) đi liền với 「ときたひには」. Mệnh đề sau nêu tật xấu: 「締め切り直前にならないと」 (hễ chưa sát nút hạn chót là không...).",
    "Cấu trúc N2 「Nときたら」 dùng để lôi một đối tượng quen thuộc ra phàn nàn, bất mãn. Thứ tự sắp xếp câu: 1. Từ hạn định 「最近の」 bổ nghĩa cho danh từ chủ thể bị phàn nàn 「若手記者」. 2. Đối tượng 「若手記者」 liên kết trực tiếp với quán ngữ 「ときたら」. 3. Trạng từ chỉ địa điểm 「現場に」 đứng trước động từ thể liên dụng phủ định 「足を運ばず」 (không chịu đến tận nơi).": "Cấu trúc 「ときたら」 biểu lộ sự bất mãn khi nhắc đến một đối tượng. Chủ thể bị chê trách 「最近の若手記者」 (phóng viên trẻ dạo này) đi kèm 「ときたら」. Sau đó là chuỗi hành động tiêu cực: 「現場に足を運ばず」 (chẳng chịu lết thân đến hiện trường).",
    "Cấu trúc N1 「〜ときているから」 dùng để đưa ra một hoặc nhiều lý do thuyết phục, hiển nhiên dẫn đến một kết quả tất yếu. Thứ tự sắp xếp câu: 1. Chủ ngữのmệnh đề phụ 「内容が」 đứng trước phó từ chỉ mức độ 「非常に」. 2. Tính từ đuôi i 「面白い」 kết hợp với trợ từ liên kết 「と」 và phần đuôi ngữ pháp chỉ nguyên nhân 「きているから」.": "Cấu trúc 「ときているから」 nhấn mạnh một lý do hiển nhiên dẫn đến kết quả tất yếu. Nguyên nhân 「内容が非常に面白い」 (nội dung vô cùng thú vị) được khẳng định bằng 「ときているから」 (đã vậy lại còn...). Từ đó tạo đà cho một hệ quả rực rỡ ở phía sau.",
    "Cấu trúc N2 「時として」 (đôi khi, thỉnh thoảng) dùng để chỉ một sự kiện hiếm khi xảy ra nhưng thỉnh thoảng vẫn xuất hiện. Thứ tự sắp xếp câu: 1. Trạng từ chỉ tần suất 「時として」 đứng đầu mệnh đề mới để bổ nghĩa cho toàn bộ hành động phía sau. 2. Danh từ làm chủ thể hành động 「激しい嵐が」 đi kèm trợ từ 「が」 đứng trước tân ngữ 「木々を」. 3. Động từ tác động 「揺らす」 bổ nghĩa cho danh từ hóa biểu thị tần suất 「ことがある」.": "Trạng từ 「時として」 (đôi khi, thi thoảng) báo hiệu một hiện tượng không thường trực. Hiện tượng 「激しい嵐が」 (cơn bão dữ dội) tác động lên 「木々を」 (những tán cây). Hành động 「揺らす」 (rung lắc) kết hợp với 「ことがある」 (thỉnh thoảng có việc) để chốt lại ý nghĩa.",
    "Cấu trúc 「時として〜ない」 biểu thị việc trong những bối cảnh đặc thù, một trạng thái phủ định hoàn toàn sẽ diễn ra. Thứ tự sắp xếp: 1. Trạng từ 「時として」 đứng làm trạng ngữ bổ trợ cho mệnh đề phủ định. 2. Cụm bổ nghĩa 「一瞬の」 đứng trước danh từ chủ đề 「油断も」 (ngay cả một sự lơ là). 3. Động từ bị động phủ định 「許されない」 đóng vai trò kết thúc câu để nhấn mạnh mức độ nghiêm trọng.": "Cấu trúc 「時として〜ない」 nhấn mạnh tính khốc liệt trong những khoảnh khắc đặc thù. Trạng từ 「時として」 (đôi khi) mở đầu cho một giới hạn: 「一瞬の油断も」 (dẫu chỉ một giây lơ là). Ranh giới đó bị cấm tiệt bằng 「許されない」 (cũng không được phép dung thứ).",
    "Cấu trúc N3 「時に」 đóng vai trò liên từ đứng đầu câu dùng để chuyển đổi đề tài một cách đột ngột. Thứ tự sắp xếp câu: 1. Mệnh đề chủ ngữ phụ 「あなたが」 đi trước động từ bổ nghĩa 「探している」. 2. Định ngữ 「探している」 bổ nghĩa trực tiếp cho danh từ 「あの古い絵」. 3. Cụm danh từ chỉ đối tượng 「あの古い絵の行方」 đi kèm cấu trúc giới từ chỉ chủ đề 「について」 để làm tiền đề cho câu hỏi ở suffix.": "Liên từ 「時に」 (nhân tiện, à này) dùng để bẻ lái câu chuyện. Chủ đề mới được khơi ra là 「あなたが探している」 (thứ mà bạn đang tìm kiếm). Nó định ngữ cho 「あの古い絵の行方について」 (về tung tích của bức tranh cổ đó) để mồi cho câu hỏi phía sau.",
    "Cấu trúc N4 「時には」 (thỉnh thoảng, có lúc) chỉ một hành động hoặc trạng thái diễn ra không thường xuyên. Thứ tự sắp xếp câu: 1. Trạng ngữ thời gian 「時には」 đứng ở đầu mệnh đề mới để tạo bối cảnh đặc biệt. 2. Tân ngữ 「自分の意見を」 đứng trước phó từ chỉ trạng thái 「はっきりと」. 3. Phó từ bổ nghĩa cho động từ hành động 「主張する」, đi liền với cấu trúc tần suất thỉnh thoảng 「こともある」.": "Trạng từ 「時には」 (thỉnh thoảng, cũng có lúc) nêu lên những ngoại lệ. Trong những lúc ấy, tân ngữ 「自分の意見を」 (ý kiến của bản thân) được yêu cầu phải 「はっきりと主張する」 (bảo vệ một cách rõ ràng). Hành động này đi kèm với cụm 「こともある」 (có lúc cũng cần) để kết thúc vế.",
    "Cấu trúc N4 「どこか(が)」 dùng để chỉ điểm nghi vấn hoặc bộ phận không xác định cụ thể (ở đâu đó, phần nào đó). Thứ tự sắp xếp câu: 1. Đại từ chỉ nơi chốn/điểm mơ hồ 「どこかが」 đóng vai trò chủ ngữ mệnh đề phụ. 2. Trạng từ chỉ cách thức 「意図的に」 đứng trước động từ thể bị động tiếp diễn 「書き換えられている」 để bổ nghĩa. 3. Động từ đi liền với trợ động từ so sánh phán đoán 「ような」 để bổ nghĩa trực tiếp cho danh từ cảm xúc ở suffix.": "Đại từ 「どこかが」 (có chỗ nào đó) chỉ một điểm bất thường không xác định. Hành động 「意図的に」 (một cách có chủ đích) đi cùng 「書き換えられているような」 (có vẻ như đang bị viết lại). Sự hoài nghi này bổ nghĩa cho cảm giác kỳ lạ ở cuối câu.",
    "Cấu trúc N3 「どこか」 đóng vai trò phó từ biểu thị sự mơ hồ, không rõ ràng (có cái gì đó, có vẻ). Thứ tự sắp xếp: 1. Phó từ 「どこか」 đứng trước để bổ nghĩa cho tính từ miêu tả trạng thái tâm lý 「寂しげな」. 2. Tính từ 「寂しげな」 bổ nghĩa trực tiếp cho danh từ chủ ngữ 「影が」. 3. Cụm danh từ chủ ngữ đi liền động từ trạng thái 「漂っている」 trước cấu trúc phán đoán ngoại quan 「ように見えた」.": "Phó từ 「どこか」 (có chút gì đó) phủ một lớp màn mơ hồ lên cảm quan. Nó bổ trợ cho vẻ 「寂しげな影が」 (hình bóng đượm vẻ cô liêu). Hình bóng đó 「漂っているように見えた」 (trông như đang vất vưởng trôi dạt) trong bối cảnh miêu tả.",
    "Cấu trúc N2 「どことなく」 mang nghĩa là không hiểu sao, một cách mơ hồ không rõ lý do. Thứ tự sắp xếp câu: 1. Trạng từ 「どことなく」 đứng trước tính từ biểu cảm 「物悲しい」 để bổ nghĩa cho sắc thái mơ hồ. 2. Tính từ 「物悲しい」 bổ nghĩa trực tiếp cho danh từ chủ ngữ 「雰囲気」. 3. Cụm danh từ chủ ngữ đi liền động từ miêu tả trạng thái 「漂っていた」 để kết thúc cảnh tả.": "Trạng từ 「どことなく」 (không hiểu sao, mơ hồ cảm thấy) dùng trong văn miêu tả tâm lý. Nó bổ nghĩa cho 「物悲しい雰囲気が」 (một bầu không khí buồn man mác). Bầu không khí ấy 「漂っていた」 (đang lan tỏa, phảng phất) trong không gian.",
    "Cấu trúc N3 「現在のところ」 mang nghĩa cho đến thời điểm hiện tại, tạm thời là. Thứ tự sắp xếp câu: 1. Danh từ chỉ thời gian 「現在」 bổ nghĩa cho danh từ 「ところ」 qua trợ từ liên kết 「の」. 2. Cụm định ngữ dài 「事件に関与した」 bổ nghĩa trực tiếp cho danh từ 「疑い」. 3. Cụm chủ đề 「疑いのある人物は」 đi trước động từ phủ định ở suffix.": "Cụm từ 「現在のところ」 (tính đến thời điểm hiện tại) vạch ra giới hạn thời gian cho một nhận định. Đối tượng là 「事件に関与した疑いのある人物は」 (kẻ có hiềm nghi dính líu đến vụ án). Tình trạng của đối tượng này sẽ được kết luận bằng cụm phủ định ở đuôi câu.",
    "Cấu trúc N1 「V-るところとなる」 là cách biểu đạt trang trọng trong văn viết, báo chí mang nghĩa 「trở thành đối tượngのhành động V」 hoặc 「dẫn tới kết cục V」. Thứ tự sắp xếp: 1. Định ngữ 「多くの」 bổ nghĩa cho danh từ làm chủ ngữ mệnh đề phụ 「市民」. 2. Chủ ngữ phụ 「市民が」 đi trước động từ dạng từ điển 「反対する」. 3. Động từ 「反対する」 liên kết trực tiếp với cấu trúc trang trọng 「ところとなる」 trước trợ động từ phán đoán 「だろう」 ở suffix.": "Cấu trúc 「V-るところとなる」 mang sắc thái trang trọng, báo hiệu một hệ quả. Nhóm đối tượng 「多くの市民が」 (đông đảo người dân) tham gia vào hành động 「反対する」 (sự phản đối). Hệ quả 「反対するところとなるだろう」 (có lẽ sẽ vấp phải sự phản đối) khép lại dự báo.",
    
    # part_56
    "～ものとする dùng trong văn bản quy định hoặc luật lệ. Trình tự logic: Chủ ngữ -> Trạng ngữ chỉ thời điểm -> Tân ngữ -> Động từ chính + ngữ pháp.": "Cấu trúc 「～ものとする」 đóng đinh một điều khoản mang tính pháp lý hoặc quy định (được xem là, bắt buộc phải). Trình tự đi từ chủ thể, thời điểm áp dụng, đối tượng chịu tác động, cho đến hành động cốt lõi mang tính chế tài.",
    "Nとすれば thường dùng để bày tỏ quan điểm từ vị trí/lập trườngのngười đó. Thứ tự logic: [Chủ ngữ/Lập trường] + とすれば + [Nhận định].": "Cấu trúc giả định 「とすれば」 (nếu giả sử là...) đặt người nói vào một lập trường cụ thể. Từ bối cảnh giả định đó, nó dẫn dắt đến những suy luận hoặc đánh giá logic ở phần sau.",

    # part_64
    "Cấu trúc 「何か」 chỉ một vật gì đó không xác định rõ. Thứ tự sắp xếp tuân theo cú pháp cơ bảnのtiếng Nhật: Tính từ 「古い」 bổ nghĩa cho danh từ 「箱": "Đại từ 「何か」 (cái gì đó) khơi gợi sự tò mò về một vật thể chưa xác định. Khối vật thể ấy mang thuộc tính 「古い」 (cũ kỹ), bổ nghĩa trực tiếp cho danh từ 「箱」 (chiếc hộp) nằm ngay phía sau.",

    # part_67
    "Cụm danh từ 「木の葉」 (lá cây) được bổ nghĩa bởi 「公園 của」. Chủ ngữ 「葉が」 đi với tính từ đuôi i đổi sang dạng liên kết 「赤く」 (đỏ) kết hợp với động từ 「なります」 (trở nên) để biểu thị sự thay đổi trạng thái. Thứ tự logic: 1-2-3-4.": "Sự chuyển biến cảnh sắc bắt đầu từ cụm 「公園の木の葉が」 (những chiếc lá cây trong công viên). Trạng thái chuyển đổi được mô tả bằng tính từ 「赤く」 (thành màu đỏ), kết hợp với động từ 「なります」 (trở nên) để vẽ nên bức tranh mùa thu.",
    "Cụm trạng ngữ 「この町から」 (từ thị trấn này) đi kèm tính từ/động từ 「遠く離れた」 (xa xôi) bổ nghĩa cho danh từ 「支店」 (chi nhánh). Cụm 「支店で働く」 (làm việc ở chi nhánh) làm định ngữ cho 「こと」 tạo cấu trúc 「ことになる」 biểu thị một kế hoạch đã được quyết định. Thứ tự đúng: 1-2-3-4.": "Sự dịch chuyển được đánh dấu bằng mốc 「この町から」 (từ thị trấn này) và khoảng cách 「遠く離れた」 (cách biệt xa xôi). Đích đến là 「支店で」 (tại chi nhánh), gắn với việc 「働くことになる」 (việc làm việc đã được ấn định).",
    "Động từ 「使う」 đưa về dạng Masu-stem 「使い」 kết hợp với 「なれた」 (thể quá khứの「なれる」) tạo cụm định ngữ 「使いなれた」 (quen dùng). Cụm này bổ nghĩa cho danh từ 「古い万年筆を」. Cụm tân ngữ này làm bổ ngữ cho hành động 「手に取った」 (cầm lấy). Thứ tự logic: 1-2-3-4.": "Động từ ghép 「使いなれた」 (đã quen tay dùng) đóng vai trò định ngữ miêu tả sự gắn bó. Vật gắn bó là 「古い万年筆を」 (cây bút máy cũ). Cây bút ấy trở thành tân ngữ cho hành động dứt khoát 「手に取った」 (đã cầm lên).",
    
    # part_69 & part_70
    "Mẫu câu cảm thán 「なんという + Danh từ + だ」 biểu thị sự ngạc nhiên lớn đối với danh từ 「原稿」 (bản thảo). Thứ tự sắp xếp: mở ngoặc kép -> phó từ cảm thán 「なんという」 đứng trước danh từ -> danh từ 「原稿」 -> đuôi cảm thán 「だ」 kèm trợ từ trích dẫn 「と」 -> bổ ngữ 「ため息を」 cho động từ chính 「ついた」。": "Cấu trúc cảm thán 「なんという...だ」 (thật là một... làm sao) thốt lên sự kinh ngạc tột độ. Lời thốt 「なんという原稿だ」 (thật là một bản thảo chấn động) được trích dẫn bằng 「と」. Nó kéo theo phản ứng cơ thể 「ため息をついた」 (đã buông một tiếng thở dài).",
    "Cụm từ 「なんということもない」 có nghĩa là 「không có gì đặc biệt, bình thường」. Cụm này bổ nghĩa cho danh từ 「日常」 qua trợ từ 「の」. Thứ tự sắp xếp tự nhiên: 「なんという」 -> 「こともない」 tạo thành tính từ -> bổ nghĩa cho 「日常の」 -> danh từ 「一部に」 -> cụm giới hạn 「過ぎなかった」 (chỉ là).": "Cụm từ 「なんということもない」 (chẳng có gì to tát) làm dịu đi sự kịch tính. Nó đóng vai trò định ngữ cho 「日常の一部に」 (một phần của nhịp sống thường nhật). Nhịp sống đó bị giới hạn bởi 「過ぎなかった」 (chẳng qua chỉ là).",
    "「なんとかして」 thể hiện ý chí quyết tâm thực hiện hành động bằng mọi giá. Nó đứng trước để bổ nghĩa cho toàn bộ vế hành động phía sau. Thứ tự sắp xếp: phó từ ý chí 「なんとかして」 -> đối tượng tương tác 「内部告発者と」 -> tân ngữ 「接触を」 -> động từ thể ý định 「試みようと」 đi kèm 「した」.": "Phó từ 「なんとかして」 (bằng mọi giá phải) nung nấu một quyết tâm mãnh liệt. Mục tiêu là 「内部告発者と接触を」 (việc tiếp xúc với người tố giác nội bộ). Ý chí đó chuyển hóa thành nỗ lực 「試みようとした」 (đã gắng sức thử nghiệm).",
    "「なんとか」 mang nghĩa là 「bằng cách nào đó, cuối cùng cũng xoay xở được」 (kết quả khách quan mang lại). Thứ tự sắp xếp: trạng từ khách quan 「なんとか」 -> tân ngữ 「倒産を」 -> động từ thể khả năng 「免れることが」 -> trợ động từ hoàn thành 「できた」。": "Trạng từ 「なんとか」 (kiểu gì rồi cũng qua) thể hiện sự thoát hiểm ngoạn mục. Nạn kiếp 「倒産を」 (nguy cơ phá sản) đã được hóa giải bằng 「免れることが」 (việc tránh khỏi). Toàn câu chốt lại bằng kết quả an tâm 「できた」 (đã có thể làm được).",
    "Cụm từ 「なんとかなる」 mang nghĩa 「rồi mọi chuyện sẽ ổn thôi」. Đi kèm trợ từ trích dẫn 「と」 để làm tân ngữ cho động từ 「信じていた」. Thứ tự logic: nội dung trích dẫn 「なんとかなると」 -> chủ ngữのhành động tin tưởng 「主人公は」 -> trạng từ bổ nghĩa 「強く」 -> động từ chính ở dạng tiếp diễn 「信じていた」.": "Niềm tin mù quáng 「なんとかなる」 (kiểu gì rồi cũng ổn) được neo chặt bằng trợ từ 「と」. Người bám víu vào nó là 「主人公は」 (nhân vật chính). Niềm tin ấy được khắc sâu bởi 「強く信じていた」 (đã luôn tin tưởng mãnh liệt).",
    "「何とか言って」 có nghĩa là 「hãy nói điều gì đó để giải quyết vấn đề」. Thứ tự sắp xếp hành động: chủ thể phát ngôn 「著者から」 -> hành động nói 「何とか言って」 -> đối tượng nhận tác động 「彼らを」 -> động từ sai khiến chỉ trạng thái 「安心させて」 -> biểu thị mong muốn 「ほしい」.": "Lời cầu cứu 「何とか言って」 (xin hãy nói điều gì đó đi) gởi gắm một trọng trách. Trách nhiệm đó xuất phát 「著者から」 (từ phía tác giả) hướng về đối tượng 「彼らを」 (họ). Mục đích tối hậu là 「安心させてほしい」 (muốn làm cho họ yên lòng).",
    "「何とかいう」 đóng vai trò bổ nghĩa cho danh từ 「村」 mang nghĩa 「ngôi làng tên là gì đó không rõ」. Thứ tự sắp xếp: vùng địa lý 「東北地方の」 -> cụm từ mơ hồ 「何とかいう」 -> danh từ chỉ nơi chốn 「村に」 -> thuộc tính 「その事件の」 -> chủ ngữ 「目撃者が」 -> động từ phỏng đoán sự tồn tại 「いるらしい」.": "Cụm từ 「何とかいう」 (tên là gì đó không rõ) phủ sự bí ẩn lên địa danh. Khu vực 「東北地方の何とかいう村に」 (ở một ngôi làng nào đó vùng Tohoku). Nơi đó che giấu 「その事件の目撃者がいるらしい」 (hình như có nhân chứng của vụ án đó).",
    "Cấu trúc 「N + とかなんとかいう + N」 dùng khi không nhớ rõ hoặc nói một cách đại khái về tên danh từ. Thứ tự sắp xếp: danh từ cụ thể trong ngoặc kép 「悲劇」とか」 -> cụm từ mơ hồ 「なんとかいう」 -> danh từ chính 「小説が」 -> động từ chỉ xu hướng 「流行しているそうだ」.": "Cách nói lấp lửng 「とかなんとかいう」 (nghe phong phanh là...) thể hiện thái độ bàng quan. Tác phẩm 「『悲劇』とかなんとかいう小説が」 (cuốn tiểu thuyết tên là \"Bi kịch\" hay gì gì đó) đang được đồn thổi là 「流行しているそうだ」 (nghe đồn là đang thịnh hành).",
    "Cấu trúc 「～とかなんとか言って」 dùng để trích dẫn một lý do mơ hồ, có ý mỉa mai hoặc hoài nghi. Thứ tự logic: chủ ngữ 「その政治家は」 -> lý do viện cớ 「体調が悪い」 -> cụm từ trích dẫn đại khái 「とかなんとか」 -> hành động nói 「言って」 -> hành động đột ngột cắt đứt cuộc họp báo 「突然会見を打ち切った」.": "Cụm từ mỉa mai 「とかなんとか言って」 (viện cái cớ gì gì đó) bóc mẽ sự thoái thác. Lời ngụy biện 「体調が悪いとかなんとか言って」 (cứ bảo là sức khỏe kém hay đại loại thế) từ 「その政治家は」 (vị chính trị gia đó). Cuối cùng dẫn đến hành vi 「突然会見を打ち切った」 (đột ngột cắt ngang cuộc họp báo).",
    "Trạng từ 「なんとしても」 nhấn mạnh quyết tâm cao độ 「bằng mọi giá/dù thế nào đi nữa」. Thứ tự logic: chủ ngữ 「生き残った若者は」 -> trạng từ ý chí 「なんとしても」 -> bổ nghĩa 「故郷の」 cho danh từ chỉ đối tượng 「家族に」 -> nguyện vọng kèm trích dẫn 「会いたいと」 -> động từ chính 「強く願った」.": "Lời thề thốt 「なんとしても」 (dù có phải trả giá đắt) cháy lên mãnh liệt. Khát khao của 「生き残った若者は」 (những người trẻ sống sót) là 「故郷の家族に会いたいと」 (muốn gặp lại gia đình ở quê nhà). Ước nguyện đó được chốt bằng 「強く願った」 (đã cầu mong tha thiết).",
    "Trạng từ 「なんとなく」 biểu thị cảm giác mơ hồ, không rõ nguyên nhân. Thứ tự sắp xếp: trạng từ chỉ cảm giác 「なんとなく」 -> tác nhân gây ra hành động bị động 「誰かに」 -> động từ thể bị động 「見られている」 -> kết cấu tạo cảm giác 「ような気がした」.": "Cảm giác bất an 「なんとなく」 (chẳng hiểu sao) ngự trị tâm trí. Sự ám ảnh 「誰かに見られているような」 (như thể đang bị ai đó dòm ngó) dẫn tới kết luận đầy hồ nghi 「気がした」 (đã có linh cảm như vậy).",
    "Trạng từ văn học 「なんとはなしに」 chỉ hành động diễn ra một cách vô thức, không mục đích rõ ràng. Thứ tự logic: chủ ngữ 「作家は」 -> trạng từ chỉ tâm trạng 「なんとはなしに」 -> bổ ngữ sở hữu 「窓の」 -> tân ngữ chính 「外の雨を」 -> trạng từ bổ trợ 「ぼんやりと」 -> động từ chính 「眺めていた」.": "Trạng từ 「なんとはなしに」 (một cách vô thức, bâng quơ) mang đậm chất văn học. Nhân vật 「作家は」 (nhà văn) thả hồn mình vào 「窓の外の雨を」 (cơn mưa bên ngoài cửa sổ). Trạng thái thả trôi ấy kết đọng trong 「ぼんやりと眺めていた」 (đang mải miết ngắm nhìn).",
    "Trạng từ 「なんとも」 dùng để nhấn mạnh mức độ cảm xúc cực kỳ cao. Thứ tự logic: chủ ngữ 「老人は」 -> trạng từ mức độ 「なんとも」 -> tính từ chỉ cảm xúc buồn bã 「切ない」 bổ nghĩa cho danh từ tân ngữ 「表情を」 -> nơi chốn xuất hiện biểu cảm 「顔に」 -> động từ biểu hiện 「浮かべた」.": "Trạng từ 「なんとも」 (thật là, vô cùng) nhấn mạnh sự ngậm ngùi. Nhân vật 「老人は」 (ông lão) bộc lộ sự đau đáu qua 「なんとも切ない表情を」 (một nét mặt sầu thảm khôn tả). Nét mặt ấy 「顔に浮かべた」 (đã hiện hữu trên gương mặt).",
    "Cấu trúc 「なんとも + V-がたい」 (thể khó khăn) diễn tả việc hoàn toàn không thể đưa ra phán đoán rõ ràng nào. Thứ tự sắp xếp: trạng từ thời gian 「現段階では」 -> trạng từ phủ định nhẹ 「なんとも」 -> động từ căn bản 「判断し」 đi kèm đuôi biểu thị sự khó khăn và trợ từ trích dẫn 「がたいと」 -> động từ tuyên bố 「発表した」.": "Cấu trúc bế tắc 「なんとも判断しがたい」 (thật khó lòng mà phán đoán) thể hiện sự thận trọng. Đứng trước 「現段階では」 (ở giai đoạn hiện tại), giới chức đành 「判断しがたいと発表した」 (công bố rằng chưa thể đưa ra nhận định).",
    "Cấu trúc 「なんとも + V-ようがない」 biểu thị sự bất lực hoàn toàn, không có cách nào thực hiện hành động. Thứ tự logic: phương thức diễn tả 「言葉では」 -> trạng từ 「なんとも」 -> danh động từ 「表現」 đi kèm đuôi cấu trúc mức độ 「しようがないほど」 -> tính từ kết thúc 「悲惨だった」.": "Sự bất lực ngôn từ thể hiện qua 「なんとも表現しようがない」 (chẳng biết diễn đạt thế nào cho phải). Giới hạn 「言葉では」 (bằng lời nói) bị đập tan trước mức độ 「しようがないほど悲惨だった」 (đã thảm khốc đến độ vô phương cứu chữa).",
    "Cụm từ 「なんとも思っていない」 có nghĩa là 「không bận tâm/chẳng nghĩ ngợi gì」. Thứ tự sắp xếp: trạng từ phủ định 「なんとも」 -> động từ suy nghĩ thể phủ định 「思っていない」 -> bổ nghĩa 「ような」 -> danh từ tân ngữ 「態度を」 -> động từ kết thúc 「崩さなかった」.": "Trạng thái vô cảm 「なんとも思っていない」 (coi như không có chuyện gì) phơi bày sự tàn nhẫn. Thái độ dửng dưng 「思っていないような態度を」 (cái thái độ coi trời bằng vung đó) vẫn cứ trơ ra, được miêu tả bằng 「崩さなかった」 (đã không hề suy suyển).",
    "Cấu trúc phủ định tuyệt đốiのtính từ đuôi i: 「Tính từ -くも何ともない」 (không... một chút nào). Thứ tự logic: cụm bổ nghĩa mức độ 「この程度の」 -> chủ ngữ chính 「挫折は」 -> liên từ trạng tháiのtính từ 「痛くも」 -> cụm từ nhấn mạnh và phủ định 「何とも」 + 「ない」.": "Phủ định tuyệt đối 「痛くも何ともない」 (chẳng hề hấn gì sất) thể hiện sự ngoan cường. Đứng trước 「この程度の挫折は」 (chút vấp ngáp cỏn con này), nhân vật gạt phăng đi bằng 「痛くも何ともない」 (chẳng xi nhê gì).",
    "Trạng từ liên kết 「なんにしても」 mang nghĩa 「dù sao đi nữa/trong bất kỳ trường hợp nào」. Thứ tự sắp xếp: liên từ đứng đầu vế kết luận 「なんにしても」 -> bổ ngữ sở hữu 「社会の」 -> danh từ chủ ngữ 「変革は」 -> động từ phủ định khả năng 「避けられない」 -> phỏng đoán 「だろう」.": "Liên từ 「なんにしても」 (dù có thế nào đi nữa) dọn đường cho một định mệnh tất yếu. Việc 「社会の変革は」 (sự đổi thay của thời cuộc) mang trên mình bản án 「避けられないだろう」 (chắc chắn là không thể cản nổi).",
    "Cấu trúc nhượng bộ 「N + はなんにしろ」 nghĩa là 「bất kể N có là gì đi nữa」. Thứ tự logic: thuộc tính sở hữu 「犯行の」 -> danh từ chủ ngữ 「動機は」 -> cụm từ nhượng bộ 「なんにしろ、」 -> cụm tính từ bổ nghĩa liên hoàn 「罪のない」 -> 「市民を巻き込む」 -> bổ nghĩa cho chủ ngữ chính 「テロ行為は決して許されない」.": "Cấu trúc nhượng bộ 「なんにしろ」 (bất luận là vì cái gì) đập tan mọi lý lẽ biện minh. Việc 「犯行の動機はなんにしろ」 (động cơ gây án có là gì mặc lòng), thì tội ác 「罪のない市民を巻き込むテロ行為は」 (hành vi khủng bố liên lụy bách tính vô tội) vẫn bị kết án 「決して許されない」 (tuyệt đối không dung tha).",

    # part_84
    "Cấu trúc 「V-た + 範囲で」 biểu thị trong phạm vi/giới hạnのhành động V. Động từ 「調査した」 bổ nghĩa cho danh từ 「範囲」. Chủ ngữのhành động điều tra là 「私たちが」 đứng trước động từ. Sau 「範囲で」 (trong phạm vi) là tân ngữ 「真実を」 bổ nghĩa cho động từ kết thúc câu 「報道します」. Thứ tự logic: 「私たちが」 -> 「調査した」 -> 「範囲で」 -> 「真実を」.": "Cấu trúc 「V-た範囲で」 (trong phạm vi đã...) vạch ra một giới hạn trách nhiệm. Trong vùng an toàn 「私たちが調査した範囲で」 (những gì chúng tôi đã điều tra được), hành động tiếp theo là phơi bày 「真実を報道します」 (sẽ đưa tin về sự thật).",
    "Cấu trúc 「〜とは反対に」 có nghĩa là 「ngược lại với...」. Ở đây, danh từ 「予想」 (dự báo) đi với trợ từ 「とは」 để kết hợp với 「反対に」 tạo thành cụm trạng ngữ tương phản. 「事前の」 (trước đó) bổ nghĩa cho 「予想」. 「物価は」 (giá cả) làm chủ ngữ cho hành động vế sau. Thứ tự đúng: 「事前の」 -> 「予想とは」 -> 「反対に、」 -> 「物価は」.": "Cấu trúc 「～とは反対に」 (trái ngược với...) tạo ra sự đảo chiều ngoạn mục. Phá vỡ 「事前の予想とは反対に」 (ngược với dự tính ban đầu), chủ thể thực sự 「物価は」 (vật giá thì) lại diễn biến theo một quỹ đạo khác.",
    "Cấu trúc 「N1 を N2 に控えて」 (với N2 là thời gian) diễn tả sự việc N1 sắp sửa diễn ra vào thời gian N2 (cận kề, sắp tới). Ở đây, N1 là 「大統領選挙」 đi với trợ từ 「を」, N2 là 「来月」 đi với trợ từ 「に」, tiếp sau là động từ liên kết 「控えて」. Danh từ 「首都の」 (của thủ đô) bổ nghĩa cho chủ ngữ 「警備」 ở vế sau. Thứ tự đúng: 「大統領選挙を」 -> 「来月に」 -> 「控えて、」 -> 「首都の」.": "Cấu trúc 「～を～に控えて」 (đứng trước thềm...) đẩy sự kiện lên cao trào. Trong bối cảnh 「大統領選挙を来月に控えて」 (sắp tới kỳ bầu cử tổng thống vào tháng sau), không khí căng thẳng lan đến 「首都の警備」 (công tác an ninh thủ đô).",
    "Phó từ mức độ 「非常に」 (rất, cực kỳ) bổ nghĩa cho tính từ 「強い」 (mạnh). Tính từ 「強い」 bổ nghĩa cho danh từ 「風」 (gió). Chủ ngữ 「風が」 đi với động từ kết thúc 「吹いています」. Trạng ngữ chỉ thời gian 「現在は」 đứng đầu cụm để xác định mốc thời gian. Thứ tự đúng: 「現在は」 -> 「非常に」 -> 「強い」 -> 「風が」.": "Phó từ 「非常に」 (vô cùng) đẩy cường độ lên mức khốc liệt. Tại thời điểm 「現在は」 (lúc này), trạng thái 「非常に強い風が」 (một trận cuồng phong) đang hoành hành, được chốt bằng 「吹いています」 (đang thổi bạo).",
    "Cấu trúc nhấn mạnh phủ định 「N一つない / V-ない」 nghĩa là 「không một...」. Ở đây, cụm trạng ngữ chỉ địa điểm 「深い森の中では」 (trong khu rừng sâu) xác định bối cảnh. Tính từ 「深い」 bổ nghĩa cho danh từ 「森」. 「物音」 (tiếng động) đi liền với 「一つ」 và động từ thể phủ định khả năng 「聞こえなかった」 để tạo ý nghĩa 「không nghe thấy một tiếng động nào」. Thứ tự đúng: 「深い」 -> 「森の中では、」 -> 「物音」 -> 「一つ」.": "Cấu trúc nhấn mạnh phủ định 「N一つない」 (dẫu chỉ một... cũng không). Giữa màn đêm tĩnh mịch 「深い森の中では」 (trong chốn rừng sâu), vạn vật câm nín đến nỗi 「物音一つ聞こえなかった」 (chẳng hề nghe thấy một tiếng động nào).",
    "Cấu trúc 「Nひとつ + V-できない / phủ định」 dùng để chỉ ra một ví dụ cực đoan, nhấn mạnh việc ngay cả một điều cơ bản như N cũng không thể làm được. Ở đây, 「記者たちの」 (của các nhà báo) và tính từ 「単純な」 (đơn giản) bổ nghĩa cho danh từ 「質問ひとつ」 (ngay cả một câu hỏi). Trạng từ 「満足に」 (một cách thỏa đáng/hài lòng) đứng trước động từ khả năng phủ định 「答えられなかった」 để bổ nghĩa cho hành động trả lời. Thứ tự đúng: 「記者たちの」 -> 「単純な」 -> 「質問ひとつ」 -> 「満足に」.": "Mẫu câu chỉ sự cực đoan 「Nひとつ...ない」 (ngay cả một... cũng chẳng xong). Dù chỉ là 「記者たちの単純な質問ひとつ」 (chỉ một câu hỏi vặt vãnh của phóng viên), nhân vật cũng bó tay, 「満足に答えられなかった」 (đã không thể đưa ra một câu trả lời cho ra hồn).",
    "Phó từ 「ひとつ」 ở đầu câu biểu thị lời đề nghị, khẩn cầu hoặc thử làm một việc gì đó (thử, xin hãy). Tiếp theo là đối tượng thực hiện hành động 「私に」 (cho tôi). Cụm tân ngữ 「独自の調査を」 (cuộc điều tra độc lập) làm bổ ngữ cho động từ thể sai khiến 「させて」. Động từ này kết hợp với 「ください」 ở phần đuôi tạo thành câu cầu khiến. Thứ tự đúng: 「ひとつ、」 -> 「私に」 -> 「独自の調査を」 -> 「させて」.": "Lời khẩn cầu mở màn bằng 「ひとつ」 (xin hãy, thử một phen). Đứng ra gánh vác trách nhiệm là 「私に独自の調査を」 (cho tôi tự mình đi điều tra), đúc kết bằng khao khát 「させてください」 (xin hãy trao quyền cho tôi làm việc đó).",
    "Cấu trúc 「ひとつ間違えば」 nghĩa là 「nếu chỉ sai một ly」, 「sơ sẩy một chút là」. Danh từ bổ nghĩa 「外交上の」 (về mặt ngoại giao) bổ nghĩa cho 「判断を」 (quyết định). Cụm 「ひとつ間違えば」 đi sau tân ngữ để tạo thành điều kiện giả định phủ định. Tính từ 「重大な」 (trọng đại, nghiêm trọng) đứng cuối để bổ nghĩa trực tiếp cho danh từ 「衝突」 (xung đột) ở phần đuôi câu. Thứ tự logic: 「外交上の」 -> 「判断を」 -> 「ひとつ間違えば」 -> 「重大な」.": "Cấu trúc cảnh báo 「ひとつ間違えば」 (chỉ cần lỡ bước một ly). Vấn đề mang tầm quốc gia 「外交上の判断を」 (các quyết sách ngoại giao) nếu mắc phải sai lầm 「ひとつ間違えば」, sẽ lập tức châm ngòi cho 「重大な衝突」 (những xung đột tàn khốc).",
    "Cấu trúc 「一通りの + N」 nghĩa là 「N ở mức độ cơ bản/thông thường」. Cụm tính từ bổ nghĩa 「業務に必要な」 (cần thiết cho công việc) đứng trước để bổ nghĩa cho toàn bộ cụm danh từ phía sau. 「一通りの」 bổ nghĩa cho danh từ chỉ cách thức 「取材方法を」 (phương pháp lấy tin). Đối tượng thực hiện hành động dạy là 「先輩から」 (từ tiền bối) đứng trước động từ thể bị động 「教え込まれた」 (được dạy dỗ/rèn luyện kịch liệt). Thứ tự logic: 「業務に必要な」 -> 「一通りの」 -> 「取材方法を」 -> 「先輩から」.": "Cụm từ 「一通りの」 (một loạt các... cơ bản). Những gì thuộc về 「業務に必要な一通りの取材方法を」 (tất tần tật các kỹ năng lấy tin nghiệp vụ), đều đã bị 「先輩から教え込まれた」 (nhồi nhét một cách khắc nghiệt từ các bậc tiền bối)."
}

for i in range(53, 85):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 4 Batch 2 (parts 53-84) manually reviewed and rewritten successfully!")
