import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_5_jlpt_exam'

rewrites = {
    # part_55
    "Ngữ pháp 「V-たところで～ない」 mang nghĩa 「cho dù/dẫu có làm V đi chăng nữa thì cũng không...」. Thứ tự đúng: Trạng từ 「今さら」 (đến lúc này thì đã muộn) đứng đầu câu -> Mệnh đề giả định 「政府が釈明した」 (chính phủ giải thích) kết hợp trực tiếp với 「ところで」 để tạo vế nhượng bộ -> Tiếp theo là tân ngữのvế sau 「国民の信頼を」 (lòng tinのnhân dân) bổ nghĩa cho cụm danh từ làm chủ đề 「取り戻すことは」 (việc lấy lại) -> Kết thúc bằng phủ định 「できない」 (không thể) để hoàn thiện cấu trúc.": "Cấu trúc vô ích 「V-たところで～ない」 (dẫu có... đi chăng nữa thì cũng vô ích thôi). Sự muộn màng 「今さら政府が釈明したところで」 (đến tận lúc này rồi chính phủ dẫu có đứng ra thanh minh thanh nga đi chăng nữa). Thì cái thứ gọi là 「国民の信頼を取り戻すことは」 (việc vớt vát lại niềm tin của người dân). Cũng trở thành chuyện 「できない」 (hoàn toàn bất khả thi).",
    "もし彼が仕掛けた罠だとしたら、私たちはすでに敵の術中にはまっていることになる。 [CẦN FIX GIẢI THÍCH] Cấu trúc 「～とされている」 dùng để nêu lên một sự thật, định nghĩa hoặc nhận định chung được xã hội/học thuật công nhận (「được coi là 」). Thứ tự: Chủ từ câu 「この遺跡で発見された土器は」 (đồ gốm được phát hiện ở di tích này) -> Cụm trạng ngữのmệnh đề định ngữ 「古代の儀式で」 (trong các nghi lễ cổ đại) -> Động từ thể bị động bổ nghĩa cho danh từ 「使われた」 (được sử dụng) -> Danh từ trung tâm 「重要な道具」 (dụng cụ quan trọng) -> Đi kèm với trợ từ chỉ nội dung đánh giá 「とされている」 ở cuối câu.": "Cấu trúc định danh học thuật 「～とされている」 (được người ta cho rằng, được giới chuyên môn nhìn nhận là). Cổ vật 「この遺跡で発見された土器は」 (những món đồ gốm được khai quật tại khu di tích này). Người ta tin rằng chúng từng là 「古代の儀式で使われた重要な道具」 (những pháp khí quan trọng được dùng trong các nghi lễ thời cổ đại). Nhận định đó được chốt lại bằng 「とされている」 (hiện đang được công nhận như vậy).",
    "Cấu trúc 「だとしたら」 đứng đầu câu phản hồi để đưa ra giả định dựa trên thông tin vừa nghe từ đối phương (「Nếu vậy thì...」). Thứ tự: Câu thoại gốc làm bối cảnh -> Từ nối giả định được băm thành 「だ」 -> Tiếp theo là phần liên kết 「としたら、」 -> Chủ từ và đối tượng vế kết luận 「私たちは誰も」 (chúng ta ai cũng...) -> Động từ khả năng phủ định 「信用できない」 (không thể tin tưởng) -> Kết thúc bằng kết luận logic 「ということになるな」 (sẽ đồng nghĩa với việc... nhỉ).": "Cấu trúc lật ngược tình thế 「～だとしたら」 (nếu quả thực sự tình là như vậy thì...). Lấy thông tin vừa nghe làm bàn đạp 「だとしたら」 (nếu đúng là như lời anh nói). Thì một hệ lụy khủng khiếp mở ra 「私たちは誰も信用できない」 (không một ai trong số chúng ta có thể đặt niềm tin được nữa). Hệ lụy đó được bồi thêm bằng 「ということになるな」 (sẽ trở thành một cơn cớ như vậy đó).",
    "開発チームとしても、この深刻なバグを放置するわけにはいかない。 [CẦN FIX GIẢI THÍCH] Ngữ pháp 「Nとして」 dùng để chỉ tư cách, vai trò, lập trường (「với tư cách là 」). Thứ tự: Chủ ngữ chính 「彼は」 (anh ấy) -> Lượng từ bổ nghĩa 「一人の」 (một...) -> Danh từ chỉ nghề nghiệp/tư cách 「小説家」 (tiểu thuyết gia) -> Trợ từ cấu trúc 「として」 -> Đối tượng tác độngのhành động sau 「人間の心の闇を」 (bóng tối trong tâm hồn con người) -> Cụm động từ kết thúc câu biểu thị quyết tâm 「描き続けると誓った」 (đã thề sẽ tiếp tục phác họa).": "Cấu trúc định danh tư cách 「Nとして」 (đứng trên lập trường, với tư cách là). Khoác lên mình danh xưng 「彼の一人の小説家として」 (với tư cách là một người cầm bút viết tiểu thuyết). Sứ mệnh mà anh ta theo đuổi là 「人間の心の闇を」 (những mảng tối tăm sâu thẳm trong tâm hồn con người). Anh ta đã 「描き続けると誓った」 (thề độc rằng sẽ tiếp tục khắc họa chúng).",
    "金銭的な損失はいいとしても、奪われた名誉を取り戻すのは容易ではない。 Đây là một cấu trúc ngữ pháp quan trọng cần ghi nhớ để nắm vững ý nghĩa câu. Cấu trúc 「Vとしても」 dùng để biểu thị một giả định mang tính nhượng bộ (「ngay cả trong trường hợp... đi chăng nữa」). Thứ tự: Trạng từ giả định 「仮に」 (giả sử) đi kèm với chủ từのmệnh đề phụ 「その計画が」 (kế hoạch đó) -> Động từ chia thể từ điển 「失敗する」 (thất bại) -> Kết hợp trực tiếp với 「としても」 -> Cụm trạng từ và tân ngữのvế sau 「今ここで挑戦を」 (thử thách ngay tại đây) -> Kết cấu biểu thị ý chí quyết tâm mạnh mẽ 「諦めるつもりはない」 (không có ý định từ bỏ).": "Cấu trúc bảo lưu ý chí kiên định 「～としても」 (cho dẫu hoàn cảnh tồi tệ nhất có xảy ra đi chăng nữa). Đặt ra một viễn cảnh xấu 「仮にその計画が失敗するとしても」 (cứ cho là cái kế hoạch đó có đổ sông đổ bể đi chăng nữa). Ý chí vẫn không hề suy suyển 「今ここで挑戦を」 (việc đương đầu với thử thách ngay tại phút giây này). Sự quyết tâm ngút ngàn 「諦めるつもりはない」 (tôi hoàn toàn không có ý định ném đá giấu tay mà từ bỏ đâu).",

    # part_56
    "Thứ tự sắp xếp hợp lý dựa trên cấu trúc ngữ nghĩaのcâu: (1) 「初版を」 đóng vai trò tân ngữ cho hành động in ấn ở , (2) 「5000部」 là lượng từ bổ nghĩa chỉ số lượng in, (3) 「刷るとして」 sử dụng mẫu ngữ pháp 「V-るとして」 (giả sử là...), (4) 「宣伝費には」 giới thiệu chủ thể thảo luận ở vế sau. Do đó, ta có trình tự tự nhiên: 初版を -> 5000部 -> 刷るとして -> 宣伝費には.": "Cấu trúc giả định tình huống 「V-るとして」 (giả dụ bây giờ thực hiện việc... thì). Đặt bài toán lên bàn cân 「初版を5000部刷るとして」 (nếu giả sử ván này ta cho in thẳng 5000 cuốn ấn bản đầu tay). Chuyển trọng tâm sang chi phí 「宣伝費には」 (riêng khoản ngân sách cho truyền thông thì). Sẽ cần một con số cụ thể ra sao.",
    "「荒れ果てた」 là định ngữ bổ nghĩa cho danh từ tân ngữ 「戦場を」 (chiến trường hoang tàn). Trạng từ 「赤く」 (màu đỏ) bổ nghĩa cho hành động 「染めようとする」 (định nhuộm/sắp nhuộm). Mẫu ngữ pháp chỉ hành động sắp sửa xảy ra 「V-ようとしている」 được chia thành 「染めようと」 và tiếp nối bằng 「している」 ở phần Suffix. Thứ tự sắp xếp: 荒れ果てた -> 戦場を -> 赤く -> 染めようと.": "Cấu trúc đe dọa chực chờ 「V-ようとしている」 (đang nhăm nhe, chực chờ sửa soạn...). Bức tranh thảm khốc 「荒れ果てた戦場を」 (một bãi chiến trường hoang tàn đổ nát). Màu máu bao trùm 「赤く染めようと」 (đang toan tính nhuộm thắm một màu đỏ ối). Và cái sự rùng rợn đó được nhấn mạnh qua 「している」 (đang diễn ra, đang ập đến).",
    "Áp dụng cấu trúc 「N1をN2とする」 (coi N1 là N2) với 「復興を」 là N1 và 「最優先課題」 là N2, đi kèm với 「とする」. Cụm 「最優先課題とする」 đóng vai trò định ngữ bổ nghĩa cho danh từ sở hữu 「政府の」 (của chính phủ), tiếp tục liên kết với danh từ trung tâm ở phần Suffix. Trình tự logic: 復興を -> 最優先課題 -> とする -> 政府の.": "Cấu trúc xem trọng mục tiêu 「N1をN2とする」 (đặt N1 lên làm N2). Trọng trách cấp bách 「復興を最優先課題とする」 (quyết định đưa công cuộc tái thiết lên làm bài toán sinh tử ưu tiên số 1). Kim chỉ nam đó là của 「政府の」 (chính phủ).",
    "Danh từ 「報道記者」 (nhà báo) đi với cấu trúc 「とすれば」 biểu thị góc độ, cương vị (đứng trên lập trường của...). Vế sau bắt đầu bằng danh từ sở hữu 「取材源の」 (của nguồn tin) bổ nghĩa cho chủ ngữ 「秘匿は」 (việc giữ kín). Cụm so sánh 「命よりも」 (hơn cả sinh mạng) bổ nghĩa cho tính từ 「重い」 ở Suffix. Trình tự logic: とすれば -> 取材源の -> 秘匿は -> 命よりも.": "Cấu trúc đặt mình vào góc nhìn người khác 「～とすれば」 (nếu đứng trên cương vị của... mà xét). Thấu cảm với đạo nghề 「報道記者とすれば」 (với tư cách và trách nhiệm của một cây bút điều tra). Trách nhiệm giữ mồm giữ miệng 「取材源の秘匿は」 (việc sống để bụng chết mang theo danh tính nguồn tin). Nó mang sức nặng 「命よりも」 (đáng giá hơn cả mạng sống).",
    "Sau chủ ngữ 「彼は」 ở Prefix, phó từ 「途端に」 (đột nhiên/ngay lập tức) được đưa vào để nhấn mạnh tính phản xạ tức thì. 「顔色を」 là tân ngữのđộng từ liên kết 「変えて」 (thay đổi sắc mặt). Trạng từ 「激しく」 (mãnh liệt) bổ nghĩa cho hành động 「立ち上がった」 ở Suffix. Thứ tự sắp xếp: 途端に -> 顔色を -> 変えて -> 激しく.": "Cấu trúc phản ứng chớp nhoáng 「～途端に」 (vừa mới... thì ngay tắp lự). Mồi lửa vừa bén 「彼は途端に」 (ngay khoảnh khắc đó, anh ta tức thì). Sự biến đổi diện mạo 「顔色を変えて」 (biến sắc mặt, tái nhợt đi). Và phản ứng cơ thể bùng nổ 「激しく立ち上がった」 (bật phắt dậy một cách dữ dội).",
    "Danh từ 「前政権」 đi liền với cấu trúc so sánh đối lập 「とは違って」 (khác hẳn với...). Ở vế sau, 「現首相は」 là chủ ngữ chính, 「世論の」 (của dư luận) bổ nghĩa cho danh từ 「動向に」 (đối với xu hướng) làm bổ ngữ cho trạng từ và tính từ ở Suffix. Trình tự logic: とは違って -> 現首相は -> 世論の -> 動向に.": "Cấu trúc vạch rõ ranh giới 「～とは違って」 (đoạn tuyệt hoàn toàn với...). Phủ nhận quá khứ 「前政権とは違って」 (trái ngược một trời một vực với chính quyền tiền nhiệm). Gương mặt mới 「現首相は」 (ngài thủ tướng đương nhiệm). Thái độ của ông đối với 「世論の動向に」 (những cơn sóng ngầm của dư luận). Vô cùng tinh nhạy.",
    "「事件を」 là tân ngữのđộng từ hành động 「捜査する」 (điều tra). Động từ này làm định ngữ bổ nghĩa cho danh từ 「途中」 + trợ từ 「に」 để chỉ thời gian hành động khác bất ngờ xen vào. 「警察は」 là chủ ngữ chính vế sau, 「新たな」 bổ nghĩa cho danh từ ở Suffix. Thứ tự logic: 捜査する -> 途中に -> 警察は -> 新たな.": "Cấu trúc sự kiện ngáng đường 「～途中に」 (đang giữa chừng... thì lại). Đang trong mạch công việc 「事件を捜査する途中に」 (đang dở dang giữa vòng xoáy phá án). Bất ngờ 「警察は」 (phía cảnh sát). Phát hiện ra 「新たな」 (một điểm mới mẻ).",

    # part_63
    "Cấu trúc 「でなけりゃ」 là dạng văn nóiの「でなければ」 (nếu không phải là). Trong bối cảnh báo chí điều tra, danh từ 「敏腕記者」 (nhà báo nhạy bén/sắc sảo) đi với 「でなけりゃ」 đóng vai trò là điều kiện tiên quyết. Theo sau là tân ngữのvế sau 「この汚職事件の真相は」 (chân tướngのvụ tham nhũng này) và kết thúc bằng động từ phủ định phỏng đoán 「暴けまい」 (có lẽ không thể vạch trần). Thứ tự logic: Điều kiện giả định 「でなけりゃ」 -> Đối tượng tác động 「真相は」 -> Hành động phủ định tương ứng 「暴けまい」。": "Cấu trúc điều kiện tiên quyết bằng văn nói 「～でなけりゃ...ない」 (nếu không phải cỡ... thì có mướt mùa cũng chẳng). Khẳng định đẳng cấp 「敏腕記者でなけりゃ」 (nếu không phải tầm cỡ phóng viên điều tra lão luyện). Thì cái mớ bòng bong 「この汚職事件の真相は」 (chân tướng đen tối của cái vụ hối lộ này). Khẳng định luôn là 「暴けまい」 (đố ai mà lột trần được).",
    "Cấu trúc 「V-なければ〜ない」 (nếu không V1 thì không thể V2). Động từ nhóm 3 「協調する」 (hợp tác/hiệp lực) chuyển thành 「協調し」 để kết hợp với đuôi giả định phủ định 「なければ」. Thứ tự sắp xếp từ trái qua phải theo đúng logic cú pháp tiếng Nhật: Đối tượng hợp tác 「他国と」 -> Động từ hành động 「協調し」 -> Điều kiện giả định 「なければ」 -> Kết quả phủ định ở vế sau 「生き残れない」 (không thể sống sót/tồn tại).": "Cấu trúc mệnh lệnh sống còn 「V-なければ...ない」 (nếu không chịu... thì chỉ có nước tàn đời). Bài học ngoại giao 「他国と協調しなければ」 (nếu không biết bắt tay hợp lực cùng lân bang). Thì tự chuốc lấy án tử 「生き残れない」 (sẽ chẳng có cửa nào để mà sinh tồn).",
    "Cấu trúc 「Nなしでは〜ない」 (nếu không có N thì không thể...). Trong bối cảnh văn học, danh từ 「体験」 (trải nghiệm) kết hợp trực tiếp với 「なし」 và trợ từ 「では」 tạo thành cụm điều kiện 「体験なしでは」 (nếu không có trải nghiệm). Thứ tự sắp xếp: Danh từ trung tâmのđiều kiện 「体験なし」 -> Trợ từ xác định điều kiện giả định phủ định 「では」 -> Chủ ngữのvế sau 「彼の代表作は」 (tác phẩm tiêu biểuのông ấy) -> Động từ khả năng phủ định ở quá khứ 「生まれ得なかった」 (đã không thể ra đời).": "Cấu trúc triệt tiêu nền tảng 「Nなしでは...ない」 (nếu thiếu đi... thì coi như bỏ). Chìa khóa thành công 「体験なしでは」 (nếu không nếm trải tận da tận thịt những phong ba đó). Thì tuyệt tác 「彼の代表作は」 (tác phẩm để đời của ông ấy). Đã vĩnh viễn 「生まれ得なかった」 (không có cửa để được thai nghén và chào đời).",
    "Phó từ 「なぜか」 (không hiểu sao/vì lý do nào đó chưa rõ) dùng để diễn tả một sự việc xảy ra ngoài dự đoán hoặc không rõ nguyên nhân. Trong câu tin tức/phóng sự này, 「なぜか」 bổ nghĩa cho toàn bộ hành động tự thú phía sau. Thứ tự logic: Chủ ngữ 「あの事件の犯人は」 (hung thủのvụ án đó) -> Trạng từ chỉ sự mơ hồ 「なぜか」 -> Trạng từ nhấn mạnh chủ thể hành động 「自ら」 (tự mình) -> Giới từ chỉ hướng 「警察に」 -> Động từ chính 「出頭してきた」 (đã ra đầu thú).": "Phó từ khơi gợi góc khuất 「なぜか」 (không hiểu ma xui quỷ khiến thế nào mà). Bí ẩn chưa lời giải 「あの事件の犯人はなぜか」 (tên sát nhân trong vụ thảm án đó, tự dưng không biết vì lý do gì). Lại dở chứng 「自ら警察に」 (đích thân lết xác đến đồn cảnh sát). Để mà 「出頭してきた」 (tự chui đầu vào rọ).",
    "Cấu trúc liệt kê hành động tiêu biểu 「V-るなどして/などする」 (làm những việc như là V...). Động từ hành động 「録音する」 (ghi âm) giữ nguyên thể từ điển kết hợp với 「などの」 để bổ nghĩa cho danh từ 「対策」 (biện pháp) tạo thành cụm từ chỉ phương thức. Thứ tự logic: Động từ hành động đại diện 「録音する」 -> Trợ từ liệt kê 「などの」 -> Danh từ mục tiêu 「対策を」 -> Động từ kết nối chỉ cách thức 「して」 dẫn tới mục đích phía sau.": "Cấu trúc liệt kê đại diện 「～などする」 (phải làm dăm ba cái trò như là...). Phương án đối phó 「録音するなどの」 (đưa ra dăm ba cái hạ sách kiểu như ghi âm lại). Đẩy thành hành động phòng thủ 「対策をして」 (giăng ra sẵn mấy cái rào chắn phòng hờ đó). Rồi tính tiếp.",

    # part_64
    "Bối cảnh phóng sự về thiên tai. Thứ tự đúng là 1-2-3-4. Đầu tiên, tính từ 「美しい」 bổ nghĩa cho danh từ 「街並みは」 để tạo thành cụm danh từ làm chủ ngữ cho vế sau. Tiếp theo, phó từ phủ định 「なにひとつ」 đi kèm với động từ thể bị động ở dạng lửng 「残されて」 và kết hợp với phần đuôi 「いなかった」(Suffix) để tạo thành cấu trúc phủ định hoàn toàn 「なにひとつ〜ない」(không còn lại một chút gì). Thứ tự kết hợp logic: 美しい (1) -> 街並みは (2) -> なにひとつ (3) -> 残されて (4).": "Cấu trúc san bằng mọi thứ 「なにひとつ～ない」 (sạch bách, tuyệt nhiên chẳng chừa lại một mống nào). Sự tàn phá vô tình 「美しい街並みは」 (từng dãy phố đẹp tựa tranh vẽ ấy). Giờ đây 「なにひとつ残されていなかった」 (đã bị càn quét không còn sót lại lấy một viên gạch).",
    "Bối cảnh tiểu thuyết trinh thám. Thứ tự đúng là 1-2-3-4. Tính từ 「暗い」 bổ nghĩa cho danh từ 「部屋の」 để chỉ không gian. Danh từ 「奥で」 đi sau cụm trước để xác định vị trí cụ thể (phía sâu trong phòng). Từ nghi vấn 「なにか」 chỉ vật gì đó không rõ ràng, đứng trước động từ chỉ khả năng cảm nhận ở đuôi 「見えましたか」(Suffix) để hoàn thành câu hỏi. Thứ tự kết hợp logic: 暗い (1) -> 部屋の (2) -> 奥で (3) -> なにか (4).": "Đại từ phiếm chỉ trong không gian rùng rợn 「なにか」 (cái thứ gì đó). Gợi sự tò mò 「暗い部屋の奥でなにか」 (đâu đó lấp ló dưới góc khuất của căn phòng tối tăm kia, liệu có một dị vật nào). Mà cậu 「見えましたか」 (đã vô tình liếc thấy không).",
    "Bối cảnh tiểu thuyết tâm lý. Thứ tự đúng là 1-2-3-4. Cụm sở hữu cách 「彼女の」 kết hợp với danh từ thời gian 「今日の」 để bổ nghĩa cho danh từ chủ ngữ 「話し方は」 nhằm chỉ 「cách nói chuyện hôm nayのcô ấy」. Phó từ 「なにか」 mang nghĩa 「có cái gì đó」 đứng trước tính từ kết câu 「おかしい」(Suffix) để biểu thị cảm giác không bình thường. Thứ tự tự nhiên: 彼女の (1) -> 今日の (2) -> 話し方は (3) -> なにか (4).": "Phó từ bóc trần sự giả tạo 「なにか」 (gờn gợn, có mùi gì đó). Bắt mạch điểm bất thường 「彼女の今日の話し方はなにか」 (cái điệu bộ mồm mép của ả ta ngày hôm nay toát ra một thứ mùi gì đó). Rất chi là 「おかしい」 (đậm chất lươn lẹo, kỳ quặc).",
    "Bối cảnh tiểu thuyết tự sự. Thứ tự đúng là 1-2-3-4. Trạng ngữ chỉ nơi chốn 「部屋で」 bổ nghĩa cho hành động phía sau. Danh từ 「小説か」 kết hợp với đại từ phiếm chỉ và trợ từ 「なにかを」 tạo thành cấu trúc 「Nか何かを」(tiểu thuyết hay thứ gì đó tương tự). Động từ 「読んで」 ở thể Te liên kết với vế kết câu 「過ごすのが好きだ」(Suffix). Thứ tự logic: 部屋で (1) -> 小説か (2) -> なにかを (3) -> 読んで (4).": "Cấu trúc tìm thú tiêu khiển 「Nか何か」 (cái N hay ba cái đồ quỷ gì đó đại loại thế). Sự lười biếng tận hưởng 「部屋で小説かなにかを読んで」 (chui rúc trong phòng, vớ lấy cuốn tiểu thuyết hay ba thứ vớ vẩn nào đó đọc giết thời gian). Đó là thú vui 「過ごすのが好きだ」 (tôi rất ưng cái kiểu sống mòn như vậy).",
    "Bối cảnh tiểu thuyết đời thường. Thứ tự đúng là 1-2-3-4. Tính từ 「怖い」 bổ nghĩa cho danh từ liên kết 「夢や」 . Cấu trúc 「夢やなにかを」 đóng vai trò tân ngữ chỉ đối tượng tương tự (cơn ác mộng hay thứ gì đó đáng sợ). Động từ 「見て」 ở thể Te chỉ nguyên nhân dẫn đến trạng thái ở vế sau 「泣き出したようだ」(Suffix). Thứ tự liên kết: 怖い (1) -> 夢や (2) -> なにかを (3) -> 見て (4).": "Cấu trúc ám ảnh tâm lý 「Nや何か」 (kiểu như N hay ma quỷ gì đó). Nguyên nhân kích động 「怖い夢やなにかを見て」 (chắc mẩm là thấy ác mộng hay trúng tà gì đó rồi). Nên mới hoảng loạn 「泣き出したようだ」 (bỗng dưng khóc ré lên như thế).",
    "Bối cảnh tiểu thuyết trinh thám. Thứ tự đúng là 1-2-3-4. Từ nối chỉ điều kiện tương phản 「それなら」 dẫn dắt câu hỏi tu từ mang tính chất chất vấn 「なにか、」 với ý nghĩa 「Ý cậu là... sao?」. Tiếp theo, đại từ nhân xưng 「君は」 làm chủ ngữ cho mệnh đề phụ, và danh từ chỉ bằng chứng ngoại phạm 「アリバイが」 đi liền trước cụm kết câu 「ないと言うのだね」(Suffix). Thứ tự sắp xếp logic: それなら (1) -> なにか (2) -> 君は (3) -> アリバイが (4).": "Phó từ dồn ép vào chân tường 「なにか」 (thế ý anh là... à). Màn chất vấn căng thẳng 「それならなにか、君は」 (nói như vậy thì hóa ra, anh đang muốn bảo là anh). Không hề có 「アリバイがないと言うのだね」 (một mảnh bằng chứng ngoại phạm nào vắt vai ư).",
    "Bối cảnh tiểu thuyết kỳ bí. Thứ tự đúng là 1-2-3-4. Cụm danh từ 「人々を」 làm tân ngữ cho động từ định ngữ 「引きつける」 . Cụm định ngữ này bổ nghĩa cho danh từ trung tâm ở phía sau. Tiếp theo, quán ngữ mang tính mơ hồ 「なにかしらの」 - một cái gì đó) bổ nghĩa cho tính từ 「不思議な」 để tạo thành cụm tính từ-danh từ kết hợp với phần đuôi câu 「力があるようだ」(Suffix). Thứ tự sắp xếp hợp lý: 人々を (1) -> 引きつける (2) -> なにかしらの (3) -> 不思議な (4).": "Cụm từ bao trùm sự bí ẩn 「なにかしらの」 (một thứ quỷ mị gì đó). Ma lực khó cưỡng 「人々を引きつけるなにかしらの」 (một loại năng lực tà đạo nào đó có thể bỏ bùa mê thuốc lú để thu hút dân tình). Nó tỏa ra một thứ 「不思議な力があるようだ」 (như thể mang một quyền năng thần bí vậy).",
    "Bối cảnh báo chí đời sống. Thứ tự đúng là 1-2-3-4. Mệnh đề trạng ngữ chỉ thời gian 「始めるときは、」 đặt ở đầu vế câu. Tiếp theo, cụm từ chỉ nguyên nhân 「手続きなどで」 làm rõ lý do. Phó từ chỉ sự đa dạng, phức tạp nhiều mặt 「なにかと」 bổ nghĩa cho tính từ 「面倒な」 . Tính từ này tiếp tục bổ nghĩa cho cụm kết câu 「ことが多い」(Suffix). Thứ tự logic: 始めるときは、 (1) -> 手続きなどで (2) -> なにかと (3) -> 面倒な (4).": "Phó từ khơi mào sự phiền phức 「なにかと」 (kiểu gì cũng vướng đủ đường). Giai đoạn chông gai 「始めるときは、手続きなどでなにかと」 (cái lúc mới chân ướt chân ráo vào việc, dăm ba cái khâu thủ tục giấy tờ này nọ kiểu gì chả). Đẩy người ta vào thế 「面倒なことが多い」 (chuốc lấy hàng đống rắc rối bực mình).",
    "Bối cảnh xã hội/báo chí. Thứ tự đúng là 1-2-3-4. Định ngữ chỉ mức độ nhỏ 「少しの」 bổ nghĩa cho danh từ thời gian 「隙間時間が」 . Cụm động từ chỉ điều kiện kết hợp quán ngữ 「できたらなにかというと」 biểu thị ý nghĩa 「hễ có cơ hội là cứ động một tí là...」. Danh từ chỉ vật dụng 「スマートフォンを」 đóng vai trò tân ngữ trực tiếp cho động từ kết câu 「操作している」(Suffix). Thứ tự liên kết: 少しの (1) -> 隙間時間が (2) -> できたらなにかというと (3) -> スマートフォンを (4).": "Cấu trúc bóc trần thói hư tật xấu 「なにかというと」 (hễ động tí là lại...). Triệu chứng nghiện ngập 「少しの隙間ができたらなにかというと」 (chỉ rảnh rỗi được chút thời gian là y như rằng ngựa quen đường cũ). Mắt cắm chặt vào 「スマートフォンを操作している」 (vuốt ve bấm chọt cái điện thoại cùi bắp).",
    "Bối cảnh phóng sự thể thao. Thứ tự đúng là 1-2-3-4. Tính từ chỉ thời gian tương lai 「次の」 bổ nghĩa cho danh từ nhấn mạnh 「決戦だけは」 nhằm xác định trận đấu quyết định tiếp theo. Phó từ chỉ quyết tâm sắt đá 「なにがなんでも」 - bằng bất cứ giá nào) bổ nghĩa cho động từ chí hướng 「勝ち抜くと」 để tạo thành mệnh đề gián tiếp bổ nghĩa cho động từ kết câu 「強く誓った」(Suffix). Thứ tự sắp xếp hợp lý: 次の (1) -> 決戦だけは (2) -> なにがなんでも (3) -> 勝ち抜くと (4).": "Phó từ thề độc 「なにがなんでも」 (sống mái bằng mọi giá). Áp lực ngàn cân 「次の決戦だけはなにがなんでも」 (riêng cái trận tử chiến tiếp theo này, dù có phải bán mạng cũng). Quyết tâm 「勝ち抜くと強く誓った」 (đã thề thốt một cách đanh thép rằng sẽ phải giành lấy chiến thắng).",
    "Bối cảnh xã luận chính trị. Thứ tự đúng là 1-2-3-4. Sở hữu cách 「政府の」 bổ nghĩa cho danh từ chủ ngữ 「新たな法案は、」 . Phó từ 「なにがなんでも」 mang sắc thái phê phán cực lực (「dù thế nào đi nữa cũng quá...」). Nó bổ nghĩa cho tính từ mang tính tiêu cực 「強引」 - cưỡng ép, áp đặt). Từ này đi kèm với cụm kết câu chỉ mức độ quá đà 「すぎると批判されている」(Suffix). Thứ tự sắp xếp logic: 政府の (1) -> 新たな法案は、 (2) -> なにがなんでも (3) -> 強引 (4).": "Phó từ vạch mặt sự ngang ngược 「なにがなんでも」 (bất chấp luân thường đạo lý). Bóc phốt sự lộng quyền 「政府の新たな法案は、なにがなんでも」 (cái dự luật mới của chính quyền, bất chấp dư luận can ngăn). Đã bộc lộ sự 「強引すぎると批判されている」 (đang bị lên án gay gắt vì thói độc tài áp đặt trắng trợn).",
    "Bối cảnh tiểu thuyết tự sự. Thứ tự đúng là 1-2-3-4. Chủ ngữ 「彼は」 được đặt ở đầu để làm rõ đối tượng thực hiện hành động. Liên từ chỉ sự liên đới, nhân cơ hội 「なにかにつけて」 - hễ có dịp gì) bổ nghĩa cho hành động hồi tưởng ở vế sau. Cụm danh từ sở hữu 「故郷の」 bổ nghĩa cho danh từ tân ngữ 「美しい海を」 kết hợp với động từ kết câu 「思い出している」(Suffix). Thứ tự sắp xếp tự nhiên: 彼は (1) -> なにかにつけて (2) -> 故郷の (3) -> 美しい海を (4).": "Phó từ lặp đi lặp lại 「なにかにつけて」 (hễ có dính líu đến cái gì là lại). Triệu chứng nhớ nhung 「彼はなにかにつけて故郷の」 (anh ta cứ hễ có dịp gì đó khơi gợi là y như rằng lại). Lục tìm hình bóng 「美しい海を思い出している」 (hồi tưởng về vùng biển quê hương đẹp miên man).",
    "Bối cảnh tiểu thuyết tự sự. Thứ tự đúng là 1-2-3-4. Cụm định ngữ chỉ sở hữu 「老人の」 kết hợp với tính từ 「なにげない」 - tình cờ, vô tình) để bổ nghĩa cho danh từ chủ ngữ 「一言が」 - một lời nói). Cụm danh từ tân ngữ 「私の人生を」 bổ nghĩa cho động từ kết câu 「大きく変えた」(Suffix) để hoàn thành ý nghĩa. Thứ tự kết hợp logic: 老人の (1) -> なにげない (2) -> 一言が (3) -> 私の人生を (4).": "Tính từ vô hình vô ảnh 「なにげない」 (nhẹ như không, bâng quơ). Sức nặng của sự buông thả 「老人のなにげない一言が」 (chỉ một câu nói bâng quơ buông thõng của ông lão). Ấy vậy mà 「私の人生を大きく変えた」 (đã giáng một đòn chí mạng thay đổi toàn bộ số phận đời tôi).",
    "Bối cảnh tiểu thuyết trinh thám. Thứ tự đúng là 1-2-3-4. Phó từ nhấn mạnh nguyên nhân 「なにしろ」 - dẫu sao thì, vì...) đứng đầu mệnh đề chỉ nguyên nhân. Tiếp theo, danh từ chủ ngữのmệnh đề nguyên nhân 「手がかりが」 kết hợp với cụm phủ định chỉ lý do 「まったくないので」 tạo thành vế câu 「vì hoàn toàn không có manh mối nào」. Cụm trạng từ chỉ giới hạn thời gian 「解決までに」 dẫn dắt đến kết luận ở phần đuôi câu 「長い時間がかかりそうだ」(Suffix). Thứ tự liên kết: なにしろ (1) -> 手がかりが (2) -> まったくないので (3) -> 解決までに (4).": "Phó từ chống chế 「なにしろ」 (bởi vì, dẫu sao thì). Nại ra một cái cớ hoàn hảo 「なにしろ手がかりがまったくないので」 (dẫu sao thì giờ bằng chứng cũng bốc hơi sạch bách rồi, nên là). Đành buông xuôi 「解決までに長い時間がかかりそうだ」 (chắc phải ốm đòn mới mong phá giải được kỳ án này).",
    "Bối cảnh báo chí xã luận. Thứ tự đúng là 1-2-3-4. Định ngữ sở hữu 「被災者の」 bổ nghĩa cho danh từ chủ đề 「安全確保が」 - việc đảm bảo an toàn). Quán ngữ so sánh hơn tất cả 「なににもまして」 - hơn bất cứ thứ gì khác/trên hết) đóng vai trò trạng từ bổ nghĩa cho danh từ trạng thái 「最優先」 . Cụm này kết hợp với phần đuôi câu 「されるべきだ」(Suffix) để hoàn thành câu. Thứ tự kết hợp: 被災者の (1) -> 安全確保が (2) -> なににもまして (3) -> 最優先 (4).": "Quán ngữ đội lên đầu 「なににもまして」 (trên hết mọi thứ, vô tiền khoáng hậu). Chân lý sống còn 「被災者の安全確保がなににもまして」 (cái mạng sống và sự an toàn của những nạn nhân vùng thảm họa, gạt tất cả sang một bên thì nó). Phải được 「最優先されるべきだ」 (đưa lên ngai vàng ưu tiên tuyệt đối).",
    "Bối cảnh văn học tự sự. Thứ tự đúng là 1-2-3-4. Tính từ quá khứ định ngữ 「美しかった」 bổ nghĩa cho danh từ chỉ địa điểm 「庭には」 . Đại từ phủ định hoàn toàn 「なにも」 - không cái gì cả) đi kèm với động từ thể Te 「残って」 và kết hợp với đuôi câu phủ định 「いなかった」(Suffix) để biểu thị trạng thái trống rỗng. Thứ tự sắp xếp logic: 美しかった (1) -> 庭には (2) -> なにも (3) -> 残って (4).": "Đại từ tàn sát 「なにも」 (chẳng còn lại cái thá gì). Tiếc nuối dĩ vãng 「美しかった庭にはなにも」 (ở cái nơi từng là một khu vườn tuyệt sắc đó, giờ đây nhẵn thín không còn một cọng cỏ). Sự tuyệt diệt 「残っていなかった」 (đã bị xóa sổ đến mức trắng tay).",
    "Bối cảnh tiểu thuyết tâm lý. Thứ tự đúng là 1-2-3-4. Phó từ 「なにも」 đứng đầu vế câu để mở đầu cho cấu trúc phủ định mang tính can ngăn 「không cần thiết phải...」. Cụm chỉ mức độ 「そこまで」 và danh từ tân ngữ 「自分を」 bổ nghĩa cho động từ hành động 「責める」 - dằn vặt, trách móc). Động từ này đi trước cụm kết câu phủ định 「ことはない」(Suffix). Thứ tự liên kết: なにも (1) -> そこまで (2) -> 自分を (3) -> 責める (4).": "Phó từ cởi trói tâm lý 「なにも～ない」 (đâu đến mức phải hèn mọn như thế). Kéo người ta khỏi vũng lầy 「なにもそこまで自分を責めることはない」 (đâu có tội tình gì mà phải tự lấy dây trói mình, tự đay nghiến bản thân đến cái nước nhục nhã như vậy chứ).",
    "巨大な津波は、 [CẦN FIX GIẢI THÍCH] Đây là một cấu trúc ngữ pháp quan trọng cần ghi nhớ để nắm vững ý nghĩa câu. Bối cảnh tiểu thuyết luận thuyết. Thứ tự đúng là 1-2-3-4. Phó từ 「なにも」 mở đầu mệnh đề để chuẩn bị cho cấu trúc phủ định một phần ở cuối câu. Cụm định ngữ chỉ sở hữu 「彼の」 bổ nghĩa cho danh từ tân ngữ 「提案をすべて」 . Tân ngữ này làm đối tượng cho động từ phủ nhận 「否定する」 . Động từ này đứng liền trước cụm ngữ pháp phủ định lý do 「わけではない」(Suffix). Thứ tự kết hợp logic: なにも (1) -> 彼の (2) -> 提案をすべて (3) -> 否定する (4).": "Cấu trúc chừa lại đường lui 「なにも～わけではない」 (chẳng qua không có nghĩa là vùi dập tất cả). Lời xoa dịu 「なにも彼の提案をすべて否定する」 (bảo vậy thôi chứ có ai hơi đâu mà đi tạt gáo nước lạnh, bác bỏ sạch trơn mọi tâm huyết của anh ta đâu). Cứu vớt bằng 「わけではない」 (làm gì có chuyện tàn nhẫn như vậy).",

    # part_67
    "Cấu trúc 「Nともなると」 diễn tả ý 「khi đã đạt đến vị thế/giai đoạn N (thường là cao, đặc biệt) thì...」. Danh từ ở đây là 「首相」 (Thủ tướng), được bổ nghĩa bởi 「一国の」 (của một quốc gia). Vế sau có chủ ngữ 「その言動が」 (hành vi ngôn từのngười đó) làm chủ thể cho hành động bị động tiếp theo. Thứ tự logic: 「一国の」 bổ nghĩa cho 「首相とも」 -> 「なると、」 -> 「その言動が」.": "Cấu trúc vươn tới đỉnh cao quyền lực 「Nともなると」 (một khi đã chễm chệ ở cái ghế... thì). Cái giá của vương miện 「一国の首相ともなると」 (một khi đã ngồi lên ghế thủ tướng của cả một quốc gia). Thì mọi thứ phơi bày 「その言動が」 (từng lời ăn tiếng nói, từng cử chỉ hành động). Đều bị soi xét.",
    "Cấu trúc 「Nになると」 diễn tả thời điểm/điều kiện tự nhiên 「khi bước sang/đến N」. Ở đây N là 「深夜」 (đêm khuya) -> 「深夜になると」. Khi đêm muộn đến thì có sự biến đổi: 「人通りが」 (người qua lại/lượng lưu thông người) -> 「途絶えて」 (bị gián đoạn/ngắt quãng, là thể ての「途絶える」 để nối với động từ chính phía sau). Thứ tự logic là 「深夜」 -> 「になると」 -> 「人通りが」 -> 「途絶えて」.": "Cấu trúc lật qua trang mới 「Nになると」 (hễ cứ bước sang giai đoạn... là lại). Sự chuyển mình của thời gian 「深夜になると」 (cứ hễ đồng hồ điểm sang khung giờ đêm vắng). Mọi sức sống bị rút cạn 「人通りが途絶えて」 (bóng người thưa thớt rồi tắt lịm).",
    "「なるほど」 là phó từ thể hiện sự đồng tình, tâm đắc (「quả nhiên là」, 「hóa ra là vậy」). Nó đứng trước để nhấn mạnh trạng thái thấu hiểu 「納得がいった」 (đã hiểu ra/đã được thuyết phục). Cụm 「納得がいった」 kết hợp với 「という」 để định nghĩa/bổ nghĩa trực tiếp cho danh từ 「表情」 (biểu cảm gương mặt) làm tân ngữのđộng từ 「浮かべる」 (lộ ra). Thứ tự logic là 「なるほど」 -> 「納得が」 -> 「いったという」 -> 「表情を」.": "Phó từ vỡ lẽ 「なるほど」 (à thì ra là cái ngữ đó). Sự khai sáng được bộc lộ 「なるほど納得がいったという表情を」 (khắc họa một cái vẻ mặt đắc ý, kiểu như ồ ra là thế, tôi đã nhìn thấu mọi tâm can rồi).",
    "Ở đây 「なんか」 diễn tả một cảm giác, trạng thái mơ hồ xuất hiện trong tâm trí (「không hiểu sao/như có cái gì đó」). Nó đứng đầu cụm vị ngữ để bổ nghĩa cho toàn bộ trạng thái cảm nhận. Tính từ 「恐ろしい」 (đáng sợ) bổ nghĩa cho danh từ 「予感」 (điềm báo/sự dự cảm). Cụm danh từ này kết hợp với động từ 「する」 (trong cấu trúc 「予感がする」: có dự cảm) chia ở thể て là 「して」 để đi với phụ động từ chỉ xu hướng phát triển 「きた」. Thứ tự logic là 「なんか」 -> 「恐ろしい」 -> 「予感が」 -> 「して」.": "Trợ từ gieo rắc sự ám ảnh 「なんか」 (sao tự dưng lại thấy...). Dự cảm chẳng lành xộc tới 「なんか恐ろしい予感がして」 (không hiểu ma xui quỷ khiến thế nào, tự dưng trong lòng lại dấy lên một linh cảm cực kỳ rợn tóc gáy).",

    # part_68
    "Danh từ 「言い訳」 (biện hộ) kết hợp với trợ từ 「なんか」 để thể hiện sự xem nhẹ lời biện hộ. Tiếp theo là động từ phủ định 「聞いていない」 tạo thành vế 「không thèm nghe biện hộ」. Vế sau bắt đầu bằng tân ngữ 「真実が」 kết hợp với tính từ mong muốn 「知りたいのだ」 (muốn biết sự thật). Thứ tự đúng biểu thị sự dứt khoát: 「Không nghe biện hộ gì hết, tôi chỉ muốn biết sự thật」.": "Trợ từ đạp đổ sĩ diện 「なんか」 (cái ngữ như, ba cái trò). Gạt phăng mớ ngôn từ giẻ rách 「言い訳なんか聞いていない」 (chẳng ai rảnh mà vểnh tai nghe dăm ba cái lời ngụy biện thối nát đó đâu). Khát vọng duy nhất 「真実が知りたいのだ」 (điều tôi cần moi ra chính là sự thật).",
    "Trợ từ phụ thuộc 「なんか」 đứng sau cụm danh từ làm đối tượng phủ định 「甘い言葉」 (lời ngọt ngào) để thể hiện sự coi thường. Theo sau là chủ ngữ 「私は」 và trạng từ nhấn mạnh phủ định 「絶対に」 (tuyệt đối). Cuối cùng là động từ phủ định 「信じない」 để hoàn thành cấu trúc phủ định 「なんか～ない」. Thứ tự logic: 「Mấy lời ngọt ngàoのgã đàn ông đó, tôi tuyệt đối không tin」.": "Trợ từ nhổ toẹt vào sự dối trá 「なんか」 (dăm ba cái). Đóng sập cánh cửa tin tưởng 「甘い言葉なんか、私は絶対に信じない」 (mấy cái lời chót lưỡi đầu môi dỗ ngọt ấy à, tôi đây có chết cũng đéo bao giờ thèm tin đâu).",
    "Trạng từ 「なんだか」 (không hiểu sao/mơ hồ) đứng đầu để diễn tả cảm giác không rõ nguyên nhân. Theo sau là tính từ 「懐かしい」 (hoài niệm) bổ nghĩa trực tiếp cho danh từ chỉ đối tượng cảm nhận 「紙の香りが」 (mùi hươngのgiấy). Động từ miêu tả sự lan tỏa 「漂ってきた」 đứng cuối để hoàn thành vế câu tả cảnh. Thứ tự đúng tạo nên một câu văn tả cảnh mang tính gợi cảm xúc hoài niệm trong văn học.": "Trạng từ gọi về những thứ vô hình 「なんだか」 (không hiểu sao, mơ hồ). Cảm giác miên man ập đến 「なんだか懐かしい紙の香りが漂ってきた」 (chẳng hiểu cớ sự gì, nhưng bỗng dưng đâu đây phảng phất một thứ mùi giấy cũ kỹ gợi nhớ cả một miền ký ức xa xăm).",
    "Mẫu ngữ pháp 「～なんて」 đứng sau câu mệnh lệnh trích dẫn 「諦めるな」 (đừng bỏ cuộc) biểu thị thái độ mỉa mai, bất mãnのngười nói đối với câu nói đó. Theo sau là trạng từ chỉ đối tượng hướng đến 「当事者でもない人間に」 (đối với người không phải trong cuộc) và cụm bày tỏ mong muốn phủ định 「簡単に言ってほしくない」 (không muốn bị nói một cách dễ dàng). Thứ tự đúng tạo nên sự tức giận dồn nénのnhân vật.": "Cấu trúc hất hủi 「なんて」 (ba cái đồ, cái loại). Phản pháo lại một lời động viên sáo rỗng 「諦めるななんて、当事者でもない人間に簡単に言ってほしくない」 (không ở trong chăn thì sao biết chăn có rận, đừng có mà đứng ngoài há miệng chờ sung rồi buông dăm ba cái lời khuyên kiểu đừng bỏ cuộc dễ nghe như vậy).",

    # part_70
    "「なんら」 kết hợp với thể phủ định 「いない」 để nhấn mạnh ý nghĩa 「hoàn toàn không」. Thứ tự sắp xếp tự nhiên là: Chủ ngữ 「警察は」 -> Phó từ phủ định 「なんら」 -> Tân ngữ 「手がかりを」 -> Động từ chính chia thể Te 「掴んで」 kết hợp với trợ động từ phủ định ở Suffix 「いないそうだ」 để tạo thành cấu trúc 「なんら～ない」 (hoàn toàn không nắm được manh mối nào).": "Phó từ phủ nhận sạch trơn 「なんら～ない」 (tuyệt nhiên chẳng có lấy một). Bộ mặt bất lực của giới chức trách 「警察はなんら手がかりを掴んでいないそうだ」 (có vẻ như lũ cớm ngoài kia hoàn toàn mù tịt, chả nắm thóp được lấy một mảnh manh mối nào cả).",
    "「なんらのNも」 đi kèm thể phủ định ở cuối để nhấn mạnh 「hoàn toàn không có một N nào」. Thứ tự đúng là: Định ngữ bổ nghĩa 「事件のsự thật liên quan」 bổ nghĩa cho danh từ phía sau -> Cấu trúc nhấn mạnh 「なんらの」 bổ nghĩa trực tiếp cho danh từ 「説明も」 -> Động từ bị động 「なされ」 đi với phủ định quá khứ 「なかったのは」 ở Suffix.": "Cấu trúc tẩy trắng sự tồn tại 「なんらのNも...ない」 (ngay cả một cái N cũng chả có). Sự phẫn nộ trước thái độ trốn tránh 「なんらの説明もなされなかったのは」 (cái việc mà chúng nó im như thóc, đéo thèm nhả ra lấy nửa lời giải thích nào). Thật sự quá khốn nạn.",
    "Cấu trúc 「引くに引けない」 (V-るにV-れない) thể hiện ý muốn thực hiện hành động nhưng không thể vì hoàn cảnh ràng buộc. Thứ tự logic: Mục đích 「雇用を守るため」 -> Cụm từ chỉ trạng thái tiến thoái lưỡng nan 「引くに引けない」 bổ nghĩa cho danh từ chỉ hoàn cảnh 「状況に」 -> Động từ kết thúc câu ở Suffix 「状況に陥っている」.": "Cấu trúc kẹp giữa gọng kìm 「V-るにV-れない」 (muốn V cũng đéo xong mà không V cũng chết). Tình thế ngàn cân treo sợi tóc 「引くに引けない状況に陥っている」 (chính thức bước một chân xuống mồ, rơi vào cái thế kẹt cứng, đâm lao phải theo lao, tiến thoái lưỡng nan rồi).",

    # part_73
    "「専門家」 (Danh từ: chuyên gia) kết hợp trực tiếp với 「にしても」 mang ý nghĩa 「ngay cả đối với... thì cũng」. Thứ tự sắp xếp logic: Đưa ra chủ đề 「この未知のウイルスについては」 -> đối tượng 「専門家」 -> ngữ pháp 「にしても」 -> nội dung đánh giá 「感染経路の特定は」 -> kết luận 「困難を極める。」": "Cấu trúc khiêu chiến năng lực 「～にしても」 (ngay cả cỡ... thì cũng). Nâng tầm độ khó lên cực hạn 「専門家にしても感染経路の特定は困難を極める」 (bài toán này quá tởm lợm, cỡ như các vị giáo sư tiến sĩ đầu ngành cũng phải vò đầu bứt tai, bó tay toàn tập trong việc truy vết ổ dịch)."
}

for i in range(51, 76):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 5 Batch 3 (parts 51-75) manually reviewed and rewritten successfully!")
