import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_4_literature'

rewrites = {
    # part_86
    "Mẫu ngữ pháp 「V-るべきだ」 dùng để thể hiện nghĩa vụ hoặc một lời khuyên mạnh mẽ mang tính chủ quan 「nên làm gì」. Ở đây, động từ 「対応する」 chuyển thành dạng văn viết trang trọng 「対応すべき」 và kết hợp với đuôi khẳng định 「だ」. Thứ tự sắp xếp logic: cụm trạng ngữ mục đích 「復興に向けて」 -> phó từ bổ nghĩa mức độ 「より」 -> tính từ đuôi na chia dạng trạng từ 「迅速に」 -> cụm động từ mang ý nghĩa khuyên nhủ 「対応すべき」 đứng trước trợ từ trích dẫn 「だ」.": "Cấu trúc 「V-るべきだ」 đưa ra một lời khuyên mạnh mẽ hoặc một nghĩa vụ thiết yếu. Mục tiêu là 「復興に向けて」 (hướng tới việc tái thiết). Trạng thái hành động được yêu cầu là 「より迅速に」 (một cách nhanh chóng hơn), dẫn tới kết luận đanh thép 「対応すべきだ」 (cần phải ứng phó).",
    "Mẫu ngữ pháp 「V-ておくべきだった」 biểu thị sự hối hận sâu sắc về một hành động đáng lẽ nên chuẩn bị hoặc làm sẵn trong quá khứ nhưng bản thân đã bỏ lỡ. Thứ tự sắp xếp tự nhiên: trạng ngữ chỉ thời gian quá khứ 「あの時」 -> phó từ mức độ bổ nghĩa 「もっと」 -> trạng từ cách thức 「真剣に」 bổ nghĩa trực tiếp cho cụm động từ chuẩn bị kèm ngữ pháp 「話し合っておくべき」 -> đuôi khẳng định quá khứ 「だった」 nối với trợ từ trích dẫn 「と」.": "Cấu trúc 「V-ておくべきだった」 bộc lộ sự nuối tiếc về một việc đã không làm. Nghĩ về thời điểm 「あの時」 (lúc đó), nhân vật hối hận vì đã không 「もっと真剣に」 (nghiêm túc hơn nữa) trong việc 「話し合っておくべきだった」 (đáng lẽ ra nên thảo luận trước).",
    "Mẫu ngữ pháp trang trọng 「V-るべくもない」 mang nghĩa phủ định tuyệt đối 「hoàn toàn không thể V / không cách nào làm V」. Ở đây cụm động từ 「取り戻す」 (khôi phục/lấy lại) kết hợp trực tiếp với ngữ pháp này. Thứ tự sắp xếp: định ngữ sở hữu thời gian 「かつての」 -> tân ngữ bị tác động 「栄光を」 -> động từ thể từ điển 「取り戻す」 -> mẫu phủ định 「べくもない」 làm vị ngữ kết câu trước trợ từ trích dẫn 「と」.": "Cấu trúc trang trọng 「V-るべくもない」 mang nghĩa phủ định tuyệt đối (hoàn toàn vô phương). Niềm vinh quang 「かつての栄光を」 (hào quang thuở nào) nay đã trở nên xa vời, bị đóng đinh bằng kết luận phũ phàng 「取り戻すべくもない」 (hoàn toàn không có cách nào lấy lại được).",
    "Tính từ đuôi na 「へた（下手）」 dùng để biểu thị sự kém cỏi, vụng về trong một lĩnh vực. Cấu trúc cơ bản là 「[Ai đó] は [Lĩnh vực] がへただ」. Thứ tự sắp xếp tự nhiên: chủ đề câu 「私は」 -> đối tượng yếu kém 「歌が」 -> tính từ và liên từ nguyên nhân 「へたですから」 -> cụm chỉ vị trí không gian bổ nghĩa 「みんなの前で」 đứng trước mệnh đề kết luận.": "Tính từ 「へた」 (kém cỏi, dở) dùng để nói về điểm yếu của bản thân. Từ chủ đề 「私は」 (tôi thì), câu chuyển sang nguyên nhân 「歌がへたですから」 (vì hát dở). Điểm yếu này dẫn tới sự e ngại trong bối cảnh 「みんなの前で」 (ở trước mặt mọi người).",
    "Cấu trúc 「V-るのがへただ」 dùng để diễn đạt việc vụng về hoặc kém trong việc thực hiện một hành động cụ thể nào đó (đã được danh từ hóa bằng 「の」). Thứ tự sắp xếp: chủ từ 「兄は」 -> tân ngữのhành động 「絵を」 -> động từ chính hành động 「描く」 -> trợ từ danh từ hóa 「のが」 -> tính từ chỉ sự vụng về và liên từ nghịch đối 「へたですが」.": "Cấu trúc 「V-るのがへただ」 chỉ sự vụng về trong một thao tác. Chủ ngữ 「兄は」 (anh trai tôi) gắn với tân ngữ 「絵を」 (bức tranh). Toàn bộ hành động được danh từ hóa thành 「描くのがへたですが」 (vẽ tranh dở nhưng mà...) để làm bước đệm cho vế tương phản phía sau.",
    "Trạng từ 「へたに」 mang nghĩa 「lóng ngóng, dại dột thực hiện hành động khi chưa có kỹ năng」. Nó dùng để bổ nghĩa cho hành động ở vế sau. Thứ tự logic: trạng từ 「へたに」 khởi đầu mệnh đề -> chủ thể tự thực hiện hành động 「自分で」 -> động từ thể ý chí hành động 「修理しよう」 -> cấu trúc giả định bắt đầu hành động 「とすると」 để dẫn tới kết quả tiêu cực.": "Trạng từ 「へたに」 (dại dột, lóng ngóng) mang tính chất cảnh báo. Nếu 「へたに」 (không biết mà cứ cố) tự mình 「自分で」 (đích thân) thực hiện hành động 「修理しようとすると」 (định sửa chữa), thì chắc chắn sẽ dẫn đến hậu quả tai hại.",
    "Trạng từ 「べつだん（別段）」 luôn đi kèm với thể phủ định ở cuối câu để tạo cấu trúc mang nghĩa 「không có gì đặc biệt / không hẳn là...」. Thứ tự sắp xếp các thành phần: trạng từ phủ định 「べつだん」 đặt đầu mệnh đề phủ định -> tính từ bổ nghĩa cho danh từ 「怪しい」 -> danh từ chủ từ phụ 「証拠は」 -> động từ chia thể phủ định tách rời 「見つから」 trước đuôi phủ định 「なかった」.": "Cấu trúc 「べつだん...ない」 (hoàn toàn không có gì đặc biệt) dùng để xua tan nghi ngờ. Mở đầu bằng 「べつだん」 (chẳng có gì gọi là), tiếp đến là 「怪しい証拠は」 (bằng chứng khả nghi). Sự hoài nghi ấy bị xóa bỏ hoàn toàn bởi 「見つからなかった」 (đã không được tìm thấy).",
    "Cụm từ trang trọng 「別段のN」 dùng nhiều trong văn phong hành chính, chính trị hoặc báo chí, mang ý nghĩa 「danh từ đặc biệt/riêng biệt nào khác」. Ở đây bổ nghĩa cho 「cuộc điều tra」. Thứ tự sắp xếp: cụm từ bổ nghĩa mức độ 「これ以上の」 -> định ngữ trạng từ 「別段の」 -> tân ngữ chịu tác động 「調査を」 -> động từ thể từ điển định ngữ hóa 「行う」 đứng ngay trước danh từ đích 「予定」.": "Cụm từ hành chính 「別段の」 (đặc biệt khác) dùng để giới hạn phạm vi. Mức độ 「これ以上の」 (hơn thế này nữa) đi kèm với 「別段の調査を」 (một cuộc điều tra đặc biệt nào khác). Hành động đó được tuyên bố là không có trong 「行う予定」 (dự định tiến hành).",
    "Cấu trúc 「N là 別として」 mang ý nghĩa loại trừ 「ngoại trừ N ra / chưa bàn tới N」. Ở đây, 「các khu đô thị lớn」 (大都市圏) bị loại trừ để tập trung phân tích vùng nông thôn. Thứ tự sắp xếp tự nhiên: mệnh đề loại trừ đầu câu 「大都市圏は別として」 -> trạng ngữ chỉ phạm vi thảo luận 「地方の町では」 -> danh từ nguyên nhân 「高齢化に」 -> động từ liên kết ý nghĩa kéo theo 「伴う」 -> danh từ sở hữu chỉ đối tượng cốt lõi 「公共交通機関の」.": "Cấu trúc 「...は別として」 (khoan bàn đến, ngoại trừ) dùng để gạt bỏ một yếu tố khỏi phạm vi thảo luận. Yếu tố bị loại trừ là 「大都市圏は別として」 (chưa bàn tới các đô thị lớn). Vấn đề thực sự nằm ở 「地方の町では」 (tại các thị trấn nông thôn), nơi phải đối mặt với hệ lụy từ 「高齢化に伴う公共交通機関の」 (giao thông công cộng đi kèm với già hóa dân số).",
    "Mẫu câu nghi vấn loại trừ 「...かどうかは別として」 có nghĩa 「việc có... hay không chưa bàn tới / là một chuyện hoàn toàn khác」. Trình tự logic: chủ ngữのmệnh đề phụ 「その計画が」 -> tính từ đuôi na làm vị ngữ chia thể trang trọng văn viết 「現実的である」 -> liên từ nghi vấn lựa chọn 「かどうかは」 -> cụm từ loại trừ 「別として、」 -> tân ngữのmệnh đề chính phía sau 「新しい視点を」.": "Cấu trúc 「...かどうかは別として」 (việc... hay không lại là chuyện khác) thể hiện sự phân tách rạch ròi. Vấn đề 「その計画が現実的であるかどうかは別として」 (việc kế hoạch đó có khả thi hay không tạm gác lại). Trọng tâm được dồn vào giá trị cốt lõi phía sau là 「新しい視点を」 (một góc nhìn mới).",
    "Mẫu câu phủ định nhẹ nhàng 「別に～ない」 biểu thị ý nghĩa 「không có gì đặc biệt / không hẳn là...」 nhằm giảm nhẹ mức độ. Thứ tự sắp xếp tự nhiên: đối tượng cảm xúc 「私には」 -> trạng từ nhấn mạnh phủ định 「別に」 -> định ngữ bổ nghĩa cho danh từ 「驚くような」 -> danh từ làm chủ ngữ phụ đi kèm từ phủ định phủ quát 「ことは何も」 -> vị ngữ phủ định quá khứ 「なかった」.": "Cấu trúc phủ định nhẹ nhàng 「別に...ない」 (cũng không có gì đáng nói) thể hiện sự bình thản. Đối với 「私には」 (bản thân tôi), thì 「別に」 (chẳng có), tiếp nối bằng 「驚くようなことは何も」 (bất cứ điều gì đáng để ngạc nhiên). Trạng thái đó được xác nhận qua vị ngữ 「なかった」 (đã không có).",
    "Hậu tố 「~っぽい」 mang tính khẩu ngữ dùng để diễn tả xu hướng, tính chất 「dễ bị / có vẻ đầy...」 (động từ bỏ ます hoặc danh từ + っぽい). Động từ 「怒る」 bỏ ます kết hợp thành tính từ đuôi i 「怒りっぽい」 (dễ nổi giận), chuyển sang dạng liên kết trạng từ biến đổi là 「怒りっぽく」 đi kèm 「なる」. Thứ tự sắp xếp: trạng ngữ chỉ thời gian 「最近は」 -> phó từ bổ nghĩa mức độ 「少し」 -> tính từ trạng từ hóa 「怒りっぽく」 -> động từ biến đổi chia quá khứ và trợ từ trích dẫn liên kết 「なったと」.": "Hậu tố 「～っぽい」 (có khuynh hướng, hay bị) khắc họa tính cách. Sự thay đổi thời gian 「最近は」 (dạo gần đây) đi kèm với mức độ 「少し」 (một chút). Tính khí trở nên 「怒りっぽくなったと」 (dễ cáu bẳn hơn), báo hiệu một trạng thái tâm lý bất ổn.",

    # part_89
    "Mẫu 「N đềあるまい」 mang ý nghĩa 「cũng không phải là N (nên không thể đối xử/hành xử như thế được)」. Ở đây, 「素人 (người nghiệp dư)」 kết hợp với trợ từ 「đề」 và động từ 「あるまい」 (phủ định phỏng đoánのである) để tạo thành mệnh đề giả định phủ định. Trình tự logic: Chủ ngữ (nhà báo chuyên nghiệp) thì 「không phải là kẻ nghiệp dư」 (素人でもあるまい), do đó vế sau đưa ra kết luận đương nhiên là 「không thể lơ là việc xác nhận nguồn tin」 (情報源の確認を怠るはずがない).": "Cấu trúc 「Nではあるまいし」 (có phải là... đâu cơ chứ) đưa ra một lời phản biện gay gắt. Với tư cách là một chuyên gia, thì 「素人でもあるまいし」 (đâu phải là kẻ nghiệp dư), nên việc 「情報源の確認を怠るはずがない」 (lẽ nào lại chểnh mảng việc kiểm chứng nguồn tin).",
    "Mẫu 「N đềあるまいし」 mang ý nghĩa 「vì không phải là N nên... (vế sau thường là chỉ trích hoặc phủ định mạnh mẽ)」. 「独裁国家 (quốc gia độc tài)」 đi với 「でもあるまいし」 tạo thành lý do bác bỏ tính hợp lýのhành động ở vế sau. Thứ tự logic: 「独裁国家」 + 「で」 (trợ từ chỉ trạng thái) + 「あるまい」 (phủ định phỏng đoánのある) + 「し」 (phân tách câu chỉ lý do), kết nối tự nhiên với vế sau phản đối việc đàn áp tự do ngôn luận.": "Cấu trúc 「Nでもあるまいし」 (cũng chẳng phải là...) được dùng để chỉ trích sự phi lý. Lời mỉa mai 「独裁国家でもあるまいし」 (có phải là quốc gia độc tài đâu) làm tiền đề. Nó bác bỏ thẳng thừng hành vi đàn áp ở vế sau, cho thấy sự bất bình của người nói.",

    # part_92
    "Thứ tự sắp xếp đúng theo mạch câu báo chí: 「まもなく」 (phó từ chỉ thời gian sắp sửa diễn ra) bổ nghĩa trực tiếp cho hành động phía sau. Tiếp theo là định ngữ 「厳重な警備の」 (sự canh phòng nghiêm ngặt) bổ nghĩa cho danh từ chỉ địa điểm 「滑走路に」 (đường băng). Cuối cùng là động từ chính 「着陸する」 kết hợp với Suffix để tạo thành mệnh đề gián tiếp.": "Trạng từ 「まもなく」 (chẳng bao lâu nữa, sắp sửa) tạo ra sự hồi hộp về thời gian. Hướng tới mục tiêu là 「厳重な警備の」 (đang được canh phòng nghiêm ngặt) tại 「滑走路に」 (trên đường băng). Sự kiện sắp diễn ra chính là việc hạ cánh 「着陸する」 (sẽ đáp xuống).",
    "Cách dùng trừu tượngの「見える」 mang ý nghĩa 「bộc lộ, xuất hiện dấu hiệu」. Ở đây, 「兆しが見える」 nghĩa là 「nhìn thấy điềm báo/dấu hiệu」. Trình tự logic: bối cảnh 「不況の末に」 (sau thời kỳ suy thoái kéo dài) -> phó từ 「ようやく」 (cuối cùng thì) -> danh từ bổ nghĩa 「経済回復の」 (của sự phục hồi kinh tế) -> cụm từ trung tâm 「兆しが見える」.": "Động từ 「見える」 (nhìn thấy, lộ ra) diễn tả một trạng thái dần hé lộ. Bối cảnh 「不況の末に」 (sau hồi suy thoái) được củng cố bằng sự nhẹ nhõm 「ようやく」 (cuối cùng thì). Điều lộ diện chính là 「経済回復の兆しが見える」 (dấu hiệu của sự phục hồi kinh tế đang dần hiện rõ).",
    "Cấu trúc 「V-plain + ように見える」 (trông có vẻ như làm gì đó / dường như là...). Thứ tự sắp xếp: tân ngữのhành động 「国民の負担を」 (gánh nặngのngười dân) -> động từ bổ nghĩa trạng thái 「減らすように」 (như thể làm giảm) -> vị ngữ 「見えるが」 (nhìn có vẻ... nhưng) để liên kết tương phản với vế thực tế ở Suffix.": "Cấu trúc 「～ように見える」 (trông có vẻ như) thường mang hàm ý đánh lừa thị giác hoặc nhận thức. Mục tiêu bề mặt là 「国民の負担を」 (gánh nặng của người dân), đi kèm hành động giả tạo 「減らすように見えるが」 (trông có vẻ như đang giảm đi, nhưng thực ra...). Vế sau sẽ lật tẩy bản chất thực sự của sự việc.",
    "Cụm từ chỉ sự phán đoán sai lầm 「見込み違いだった」 (đã tính toán sai/lầm lẫn). Thứ tự câu: mệnh đề nhượng bộ 「だったが」 (đã là kế hoạch vạn toàn nhưng...) -> hành động sai lầm được danh từ hóa 「相手の能力を侮ったのは」 (việc coi thường năng lực đối thủ) -> vị ngữ kết luận 「見込み違いだった」 (là một sự tính toán sai lầm).": "Cụm từ 「見込み違いだった」 (đã đánh giá sai lầm) bộc lộ sự tính toán trật lất. Sai lầm cốt lõi 「相手の能力を侮ったのは」 (việc khinh thường năng lực của đối thủ) chính là nguyên nhân dẫn đến thất bại, được chốt bằng kết luận cay đắng 「見込み違いだった」 (đó là một sự tính toán hoàn toàn sai lầm).",

    # part_93
    "Cụm động từ bổ nghĩa định ngữ 吸い込まれそうな (như thể bị hút vào) đứng trước bổ nghĩa cho danh từ 人形 (búp bê). Danh từ 人形 kết hợp với từ so sánh みたいな (giống như) để tạo thành một cụm tính từ bổ nghĩa cho danh từ tiếp theo là 瞳で (bằng đôi mắt). Cụm này làm trạng ngữ chỉ phương thức cho hành động ở phần suffix. Thứ tự logic: 吸い込まれそうな -> 人形 -> みたいな -> 瞳で.": "Cấu trúc ví von 「Nみたいな」 (giống như...) tô đậm vẻ đẹp siêu thực. Sức hút mê hồn 「吸い込まれそうな」 (cảm giác như bị hút hồn vào trong) được gán cho 「人形みたいな」 (giống như một búp bê). Cuối cùng hội tụ ánh nhìn ở 「瞳で」 (bằng đôi mắt ấy).",
    "Trạng từ so sánh まるで (như thể là) đứng đầu để nhấn mạnh ý so sánh. Cụm danh từ sở hữu 真夏の (giữa mùa hè) bổ nghĩa cho danh từ 台風 (bão). Danh từ 台風 liên kết trực tiếp với đuôi phán đoán so sánh みたいだ (giống như) tạo thành vị ngữ hoàn chỉnh cho câu gián tiếp, đứng trước trợ từ trích dẫn と ở phần suffix. Thứ tự logic: まるで -> 真夏の -> 台風 -> みたいだ.": "Trạng từ so sánh 「まるで」 (cứ y như thể là) đẩy liên tưởng lên mức tối đa. Hình ảnh 「真夏の」 (của giữa mùa hè) gắn liền với 「台風みたいだ」 (giống như một cơn cuồng phong). Sự so sánh này nhấn mạnh sự tàn phá khủng khiếp của đối tượng.",
    "Mệnh đề chủ ngữ bắt đầu bằng cụm bổ ngữ 海外旅行に (du lịch nước ngoài) kết hợp động từ danh từ hóa 行くのは (việc đi). Tiếp theo là vế so sánh gồm tân ngữ 贅沢品を (hàng xa xỉ) và động từ 買う (mua). Động từ thể từ điển 買う liên kết trực tiếp với biểu thức みたいなものだ (gần như là/chẳng khác nào) để hoàn thành vị ngữ câu. Thứ tự logic: 海外旅行に -> 行くのは -> 贅沢品を -> 買う.": "Cấu trúc so sánh 「～みたいなものだ」 (chẳng khác nào...) dùng để quy đổi giá trị. Việc xa xỉ 「海外旅行に行くのは」 (chuyện đi du lịch nước ngoài) được mang lên bàn cân. Nó được đánh giá là tốn kém ngang ngửa với việc 「贅沢品を買う」 (mua sắm các món hàng xa xỉ).",
    "Tính từ đuôi な bổ nghĩa 新たな (mới) đi trước để bổ nghĩa cho danh từ chủ ngữ 衝突が (xung đột). Động từ thể quá khứ 起きた (đã xảy ra) làm vị ngữ cho mệnh đề phụ, liên kết trực tiếp với đuôi phỏng đoán みたいだ (hình như là/có vẻ như). Toàn bộ mệnh đề này đứng trước trợ từ trích dẫn と ở phần suffix. Thứ tự logic: 新たな -> 衝突が -> 起きた -> みたいだ.": "Cấu trúc phỏng đoán 「～みたいだ」 (hình như, có vẻ như) thể hiện một dự cảm chẳng lành. Sự rạn nứt bắt đầu từ 「新たな」 (một cái gì đó mới mẻ). Đó chính là 「衝突が起きたみたいだ」 (có vẻ như một cuộc xung đột mới vừa nổ ra), báo hiệu những sóng gió sắp tới.",
    "Danh từ chỉ người 彼 (anh ấy) kết hợp với cấu trúc chỉ ví dụ みたいな (như là) để bổ nghĩa cho danh từ phía sau. Tiếp theo, tính từ đuôi な 情熱的な (nhiệt huyết) bổ nghĩa trực tiếp cho danh từ chỉ nghề nghiệp 作家 (nhà văn) để làm tân ngữ đích cho cụm động từ chuyển đổi trạng thái になりたい (muốn trở thành) ở phần suffix. Thứ tự logic: 彼 -> みたいな -> 情熱的な -> 作家.": "Cấu trúc 「Nみたいな」 (như là...) đưa ra một hình mẫu lý tưởng. Hình tượng 「彼みたいな」 (người như anh ấy) được bồi đắp thêm bởi tính từ 「情熱的な」 (đầy nhiệt huyết). Mẫu người đó chính là 「作家」 (nhà văn) mà nhân vật luôn khao khát vươn tới.",
    "Chỉ thị từ この (này) bổ nghĩa cho danh từ chỉ địa điểm 区域内に (trong khu vực). Phó từみだりに (tự tiện/vô cớ) đứng trước để bổ nghĩa cho động từ hành vi 立ち入る (xâm nhập). Động từ này đứng trước trợ từ danh từ hóa ことは ở phần suffix để làm chủ ngữ cho câu bị động nghiêm cấm. Thứ tự logic: この -> 区域内に -> みだりに -> 立ち入る.": "Việc xâm phạm được xác định bởi địa giới 「この区域内に」 (vào trong khu vực này). Trạng từ cấm đoán 「みだりに」 (một cách tự tiện, vô cớ) đi đôi với hành vi 「立ち入る」 (tiến vào). Cụm này làm chủ ngữ cho quy định cấm ngặt ở phía sau.",
    "Cụm trạng ngữ chỉ địa điểm 海で (ở biển) đứng trước để chỉ nơi chốn xảy ra hành động. Tính từ きれいな (đẹp) bổ nghĩa trực tiếp cho danh từ tân ngữ 夕日を (hoàng hôn). Động từ chỉ hành vi 見る kết hợp với cụm danh từ hóa のが (việc xem...) để làm chủ ngữ cho tính từ biểu thị sở thích 好きだ (thích) ở phần suffix. Thứ tự logic: 海で -> きれいな -> 夕日を -> 見るのが.": "Bối cảnh không gian 「海で」 (tại bãi biển) mở ra một khung cảnh lãng mạn. Khung cảnh đó là 「きれいな夕日を」 (áng hoàng hôn tuyệt đẹp). Việc chiêm ngưỡng nó được danh từ hóa thành 「見るのが」 (việc ngắm nhìn...) để bày tỏ sở thích của người nói.",
    "Cụm danh từ sở hữu 市場の (của thị trường) bổ nghĩa cho danh từ 回復には (đối với sự phục hồi). Cụm phó từ và danh từ まだ時間が (vẫn cần thời gian) đi kèm động từ và trợ từ liên kết かかると (cho rằng mất/tốn...) để làm mệnh đề nội dung nhận định cho động từ phán đoán みている (đang nhìn nhận/cho rằng) ở phần suffix. Thứ tự logic: 市場の-> 回復には -> まだ時間が -> かかると.": "Đối tượng nhận định là 「市場の回復には」 (đối với việc phục hồi của thị trường). Nhận định đó mang tính bi quan 「まだ時間がかかると」 (chắc hẳn sẽ còn phải mất nhiều thời gian). Cụm này đóng vai trò làm nội dung cho quan điểm đánh giá.",
    "Cụm giới từ 世論調査に (trong khảo sát dư luận) kết hợp động từ định ngữ みる (nhìn thấy ở...) bổ nghĩa cho cụm phía sau. Tiếp theo, danh từ sở hữu 政治不信の (sự bất tín nhiệm chính trị) bổ nghĩa cho danh từ làm chủ ngữ chính 広がりは (sự lan rộng). Toàn bộ cụm này đi với tính từ vị ngữ 極めて深刻だ (cực kỳ nghiêm trọng) ở phần suffix. Thứ tự logic: 世論調査に -> みる -> 政治不信の -> 広がりは.": "Động từ 「みる」 (nhìn thấy) đóng vai trò định ngữ chỉ nguồn gốc. Từ những con số 「世論調査にみる」 (thấy được qua các cuộc thăm dò dư luận), hiện trạng 「政治不信の広がりは」 (sự lan rộng của nỗi bất tín nhiệm chính trị) đang phơi bày một thực tại tồi tệ.",
    "Trạng từ 一斉に (đồng loạt) đứng trước bổ nghĩa cho động từ thể quá khứ 消えた (đã tắt). Động từ này làm định ngữ bổ nghĩa cho danh từ liên kết ところを kết hợp với みると, tạo thành cấu trúc chỉ căn cứ phán đoán ところをみると (nhìn từ việc.../nhìn vào chỗ...). Mệnh đề này dẫn tới phán đoán ở phần suffix. Thứ tự logic: 一斉に -> 消えた -> ところを -> みると、.": "Cấu trúc 「～ところをみると」 (cứ nhìn vào cái cách mà...) chỉ ra một căn cứ phán đoán. Sự kiện bất thường 「一斉に消えた」 (tất cả vụt tắt đồng loạt) đi kèm với 「ところをみると」. Từ hiện tượng đó, người quan sát rút ra kết luận mang tính quy nạp.",
    "Phó từ 見るからに (nhìn qua đã thấy/trông có vẻ) đứng trước bổ nghĩa cho tính từ đuôi な 重厚な (sang trọng/uy nghiêm). Tiếp theo, cụm danh từ chất liệu 革張りの (bằng da) bổ nghĩa cho danh từ chủ ngữ ソファが (chiếc sofa). Danh từ này đi với vị ngữ chỉ trạng thái tồn tại 置かれていた (đang được đặt) ở phần suffix. Thứ tự logic: 見るからに -> 重厚な -> 革張りの -> ソファが.": "Phó từ 「見るからに」 (nhìn qua cũng đủ thấy) phác họa ấn tượng thị giác áp đảo. Ấn tượng đó là 「重厚な」 (sự bề thế, uy nghi), đính kèm chất liệu 「革張りの」 (bọc da cao cấp). Tổ hợp này tôn lên vẻ sang trọng của 「ソファが」 (chiếc ghế sô-pha).",
    "Danh từ chỉ phương hướng 東 (phía Đông) kết hợp với hậu tố chỉ hướng 向きの để bổ nghĩa cho danh từ chỉ địa điểm 部屋には (trong căn phòng). Cụm phó từ và tính từ 毎朝まばゆい (mỗi sáng rực rỡ) đứng trước bổ nghĩa trực tiếp cho danh từ chủ ngữ 光が (ánh sáng) đi kèm động từ 差し込んだ (chiếu vào) ở phần suffix. Thứ tự logic: 東 -> 向きの -> 部屋には -> 毎朝まばゆい.": "Hậu tố 「～向きの」 (hướng về phía) xác định vị trí không gian. Tại không gian 「東向きの部屋には」 (trong căn phòng quay mặt về hướng Đông). Nó hứng trọn 「毎朝まばゆい」 (sự chói lòa mỗi sớm mai) của ánh mặt trời hắt vào.",
    "Danh từ chỉ đối tượng 初心者 (người mới bắt đầu) đi với hậu tố 向きに (phù hợp với/dành cho) đóng vai trò trạng ngữ bổ nghĩa phương thức. Tiếp theo, danh từ chủ ngữ phụ 操作が (thao tác) đi kèm danh từ chỉ hành động 簡略化 (giản lược hóa) để kết hợp với động từ bị động trạng thái されている ở phần suffix. Thứ tự logic: 初心者 -> 向きに -> 操作が -> 簡略化.": "Hậu tố 「～向きに」 (dành cho, hướng tới đối tượng) xác định tệp người dùng. Để thiết kế sao cho 「初心者向きに」 (phù hợp với những người mới chập chững). Các bước 「操作が簡略化」 (thao tác đã được đơn giản hóa) đến mức tối đa.",
    "Cụm tính động từ chỉ nhận định 時期尚早 (chưa đúng thời điểm/quá sớm) kết hợp hệ từ và trợ từ liên kết だと đứng trước bổ nghĩa cho động từ 批判する (phê phán). Động từ này làm định ngữ bổ nghĩa cho danh từ 向きも (phía/bộ phận người/giới). Toàn bộ cụm này đi với động từ tồn tại ある ở phần suffix để tạo thành nghĩa 「cũng có những ý kiến phê phán rằng...」. Thứ tự logic: 時期尚早 -> だと -> 批判する -> 向きも.": "Cụm danh từ 「向きも」 (cũng có luồng ý kiến) chỉ một phe phái quan điểm. Lập luận của phe này là 「時期尚早だと」 (vẫn còn quá sớm để thực hiện). Từ đó dẫn đến hành động 「批判する向きも」 (có cả một bộ phận lớn tiếng chỉ trích).",

    # part_97
    "Phó từ もしかしたら dùng để diễn tả sự nghi ngờ, liên kết với trợ từ nghi vấn 「か」 ở cuối câu. Thứ tự sắp xếp các thành phần: Cụm định ngữ 「あの事件の」bổ nghĩa cho chủ ngữ 「真犯人は」 . Tiếp theo là thành phần chỉ nơi chốn 「彼の身内に」bổ nghĩa cho động từ tồn tại chỉ phỏng đoán 「いるのだろう」 , kết thúc bằng trợ từ nghi vấn 「か」 ở Suffix.": "Phó từ 「もしかしたら」 (biết đâu đấy, nhỡ đâu) gieo rắc sự hoài nghi. Nghi vấn hướng về 「あの事件の真犯人は」 (hung thủ thực sự của vụ án đó). Hắn ta có khi lại lẩn khuất ngay trong 「彼の身内に」 (những người ruột thịt của gã) cũng nên.",
    "Liên từ もしくは kết nối hai danh từ song song 「XもしくはY」 (hoặc X hoặc Y) mang tính trang trọng. Trình tự logic: Danh từ thứ nhất 「避難所」-> Liên từ 「もしくは」-> Danh từ thứ hai được định ngữ hóa 「最寄りの役所」đi với trợ từ chỉ địa điểm hành động 「で」để bổ nghĩa cho động từ chính ở phần Suffix.": "Liên từ 「もしくは」 (hoặc là) đưa ra sự lựa chọn tương đương mang tính trang trọng. Lựa chọn đầu tiên là 「避難所」 (khu lánh nạn), được nối bởi 「もしくは」. Lựa chọn thay thế là 「最寄りの役所で」 (tại ủy ban hành chính gần nhất).",
    "Phó từ もしも diễn tả giả định cực kỳ giả thuyết, thường đi kèm với thể điều kiện 「～たら」 ở cuối vế. Thứ tự sắp xếp tự nhiên: Trạng từ chỉ thời gian 「あの時」-> Định ngữ 「彼の」bổ nghĩa cho tân ngữ 「手を」-> Động từ giả định phủ định quá khứ 「離さなかったら」dẫn nhập vào kết quả ở phần Suffix.": "Phó từ giả định 「もしも」 (giá như mà) vẽ ra một thực tại vô hình. Nghĩ về khoảnh khắc định mệnh 「あの時」 (vào cái lúc ấy). Giá như bản thân 「彼の手を離さなかったら」 (đã không buông tay anh ấy ra), thì mọi chuyện giờ đây đã khác.",
    "Cụm danh từ 「もしものN」 mang ý nghĩa 「trong trường hợp khẩn cấp/có sự cố xảy ra」. Ở đây N là 「時」 (khi). Trình tự logic: Cụm ngữ pháp 「もしもの」bổ nghĩa cho danh từ 「時」 kèm trợ từ 「の」để tạo thành cụm chỉ mục đích/chuẩn bị 「ために」 . Cụm này bổ nghĩa cho trạng ngữ chỉ nơi chốn 「日記の最後に」 , rồi kết thúc bằng hành động chính ở Suffix.": "Cụm từ phòng bị 「もしもの時のために」 (phòng khi có chuyện bất trắc xảy ra). Để chuẩn bị cho tình huống xấu nhất ấy, một bí mật đã được cất giấu 「日記の最後に」 (ở ngay phần cuối của cuốn nhật ký).",
    "Phó từ もっと dùng để biểu thị mức độ hơn nữa. Trình tự logic: Phó từ 「もっと」bổ nghĩa cho trạng từ chỉ cự ly 「近くに」 kết hợp định ngữ 「私の」 , 3) -> Động từ liên kết thể Te 「寄って」bổ nghĩa cho hành động chính 「歩いてください」 ở Suffix.": "Phó từ 「もっと」 (hơn nữa, thêm nữa) đòi hỏi sự gia tăng về mức độ. Mong muốn thu hẹp khoảng cách 「もっと近くに」 (đến gần hơn chút nữa). Sự xích lại đó là 「私の寄って」 (hãy nép sát vào tôi), tạo nên một cử chỉ gắn kết.",
    "Mẫu 「もっとも～が」 dùng để đưa ra lời giải thích bổ sung làm giảm bớt mức độ hoặc đưa ra giới hạn cho câu khẳng định trước đó. Trình tự logic: Liên từ đưa thông tin đính chính 「もっとも、」-> Trạng từ chỉ tình trạng chưa hoàn thành 「まだ」-> Cụm danh từ chỉ số lượng hạn chế 「数ページ」kết hợp với trợ từ giới hạn chỉ mức độ 「だけだ」trước khi kết thúc bằng trợ từ nghịch đối 「が」 ở Suffix.": "Liên từ 「もっとも」 (tuy nhiên, có điều là) dùng để đính chính, vớt vát lại phát ngôn trước đó. Thực tế phũ phàng 「まだ数ページ」 (vẫn chỉ mới vài trang giấy) được nhấn mạnh bằng giới hạn 「だけだが」 (mà thôi).",
    "Phó từ もともと chỉ bản chất ban đầu hoặc nguồn gốc vốn cóのsự vật (「vốn dĩ/ban đầu」). Thứ tự sắp xếp logic: Phó từ trạng thái 「もともと」-> Tính từ bổ nghĩa 「小さな」bổ nghĩa cho danh từ 「漁村に」đi cùng cấu trúc giới hạn 「すぎな」trước khi kết thúc bằng đuôi phủ định quá khứ ở Suffix.": "Phó từ 「もともと」 (vốn dĩ từ đầu) truy nguyên cội rễ của vấn đề. Bản chất nguyên sơ của nơi ấy chỉ là 「小さな漁村に」 (một ngôi làng chài nhỏ bé). Sự nghèo nàn đó được chốt hạ bằng cụm 「すぎなかった」 (cũng chẳng qua chỉ là).",

    # part_102
    "Cấu trúc 「V-ようとする」 diễn tả nỗ lực, cố gắng thực hiện hành động. Trình tự logic: Chủ ngữ 「野生のシカは」 + tân ngữ hành động bổ trợ 「雪を」 + hành động bổ trợ 「掘って、」 + tân ngữ hành động chính 「草を」 + động từ hành động chính thể ý chí 「食べようと」 + đuôi cấu trúc 「している」.": "Cấu trúc 「V-ようとする」 (cố gắng, nỗ lực làm gì đó) cho thấy một sự tranh đấu sinh tồn. Nhân vật 「野生のシカは」 (những chú hươu hoang dã) đang chật vật 「雪を掘って」 (bới tung lớp tuyết). Mục đích sống còn của chúng là 「草を食べようと」 (cố gắng tìm ăn những ngọn cỏ).",
    "Cấu trúc 「V-ようにもV-れない」 biểu thị muốn làm gì đó nhưng không thể làm được. Trình tự logic: Nguyên nhân khách quan 「猛吹雪で」 + trạng thái cản trở 「前が」 + 「見えず、」 + điểm xuất phát hành động 「家から」 + động từ chính thể ý chí 「出ようにも」 + động từ khả năng dạng phủ định 「出られない」.": "Cấu trúc bất lực 「V-ようにも...ない」 (dù có muốn... cũng vô phương). Cơn thịnh nộ của thiên nhiên 「猛吹雪で前が見えず」 (bão tuyết mù mịt không thấy đường đi). Nó nhốt chặt con người, khiến họ 「家から出ようにも」 (dẫu có muốn bước chân ra khỏi nhà) cũng đành chôn chân tại chỗ.",
    "Cụm từ 「要するに」 dùng để tóm tắt vấn đề ở đầu câu. Trình tự logic: Trạng từ đúc kết 「要するに、」 + chủ đề chínhのcâu 「この政策 là」 + sở hữu định ngữ 「国民の」 + tân ngữ chịu tác động 「生活を」 + cụm tính từ bổ nghĩa cho danh từ kết câu 「豊かにするための」 + danh từ hình thức kết luận kết câu 「ものだ」.": "Liên từ 「要するに」 (tóm lại là, tóm gọn thì) tung ra đòn chốt hạ vấn đề. Trọng tâm tranh luận 「この政策は」 (chính sách này thì), quy cho cùng chỉ là vỏ bọc. Thực chất cốt lõi là việc 「国民の生活を豊かにするための」 (nhằm mục đích làm giàu đẹp thêm đời sống nhân dân).",
    "Cấu trúc 「V-た かのように」 biểu thị trạng thái cứ như thể là. Trình tự logic: Vế liên kết nguyên nhân/bối cảnh 「激しい嵐が去り、」 + chủ ngữ chính vế sau 「街は」 + chủ ngữのvế ví von 「時が」 + động từ chia thể quá khứ nghi vấn tự nhiên 「止まったか」 + liên từ so sánh ví von 「のように」 + động từ miêu tả trạng thái tĩnh lặng 「静まり返っていた」.": "Cấu trúc ví von 「～かのように」 (cứ y như thể là...) tạo ảo giác siêu thực. Sau cơn cuồng nộ 「激しい嵐が去り」 (cơn bão dữ dội vừa đi qua), không gian 「街は時が」 (cả thành phố tựa hồ như thời gian). Mọi thứ chìm vào hư không 「止まったかのように」 (cứ như thể đang ngừng trôi).",
    "Cấu trúc 「Nのように」 dùng để nêu ví dụ điển hình. Trình tự logic: Danh từ ví dụ điển hình 「ポートランドの」 + từ chỉ ví dụ 「ように」 + trạng ngữ chỉ khía cạnh 「環境に」 + tính từ bổ nghĩa danh từ chính 「優しい」 + danh từ chính làm chủ ngữ 「都市が、」 + vế chỉ nguyện vọng hướng tới tương lai 「日本にも増えてほしい」.": "Cấu trúc 「Nのように」 (như là...) nêu bật một hình mẫu chuẩn mực. Tấm gương 「ポートランドのように」 (giống như thành phố Portland). Nó đại diện cho tiêu chuẩn 「環境に優しい都市が」 (một hình mẫu đô thị thân thiện với môi trường) đang được mong chờ.",
    "Cấu trúc 「Nのような N」 dùng để ví von bổ nghĩa danh từ. Trình tự logic: Trạng từ chỉ địa điểm bối cảnh 「この部屋には、」 + tính từ bổ nghĩa cho danh từ ví von 「古い」 + danh từ ví von 「図書館の」 + liên từ cấu trúc 「ような」 + tính từ bổ nghĩa tiếp theo 「独特な」 + cụm chủ vị kết thúc câu 「匂いが漂っている」.": "Cấu trúc miêu tả 「Nのような」 (như là...) đánh thức khứu giác. Trong không gian 「この部屋には」 (tại căn phòng này), có sự hiện diện của 「古い図書館のような」 (hệt như một thư viện cũ kỹ). Nó tỏa ra một 「独特な」 (thứ mùi hương đặc trưng) đầy hoài niệm.",
    "Cấu trúc 「V-たようだ」 thể hiện phán đoán, suy luận dựa trên thông tin có sẵn. Trình tự logic: Cụm chỉ bối cảnh/bằng chứng khách quan 「机の上の」 + 「手紙を見ると、」 + chủ ngữのvế suy đoán 「彼は」 + trạng từ hoàn thành hành động 「すでに」 + động từ chínhのvế phán đoán 「旅立った」 + đuôi phỏng đoán kết thúc 「ようです」.": "Cấu trúc phỏng đoán 「V-たようだ」 (có vẻ như đã...) đi từ bằng chứng đến kết luận. Chứng cứ để lại là 「机の上の手紙を見ると」 (khi nhìn bức thư để trên bàn). Suy luận rút ra là 「彼はすでに旅立った」 (có vẻ như anh ấy đã cất bước ra đi).",
    "Cấu trúc 「～ような気がする」 diễn tả cảm nhận mơ hồ. Trình tự logic: Định ngữ và trạng ngữ chỉ nơi xuất phát 「闇の」 + 「向こうから、」 + tác nhân hành động bị động 「誰かに」 + động từ bị động tiếp diễn 「見つめられている」 + liên từのcấu trúc phán đoán mơ hồ 「ような」 + đuôi chỉ cảm giác 「気がする」.": "Cấu trúc 「～ような気がする」 (có linh cảm như...) khơi dậy nỗi sợ vô hình. Sự rợn gáy đến từ 「闇の向こうから」 (từ phía bên kia màn đêm). Cảm giác bị theo dõi 「誰かに見つめられているような」 (như thể đang bị ai đó chằm chằm nhìn vào) đè nặng tâm trí.",
    "Cấu trúc 「～ようでは」 chỉ giả định tiêu cực dẫn đến hậu quả không mong muốn. Trình tự logic: Trạng từ chỉ mức độ 「これほど」 + tính từ bổ nghĩa cho danh từ làm chủ ngữ vế điều kiện 「基礎的な」 + danh từ làm chủ ngữ vế điều kiện 「技術も」 + động từ cụm phủ định 「身につかない」 + đuôi liên kết giả định tiêu cực 「ようでは、」 + vế kết quả hệ quả xấu 「プロとしては通用しない」.": "Cấu trúc giả định tiêu cực 「～ようでは」 (nếu cứ cái đà này thì...) phán quyết một kết cục tồi tệ. Sự yếu kém 「これほど基礎的な技術も」 (ngay cả những kỹ năng căn bản đến thế này). Nếu vẫn 「身につかないようでは」 (chẳng thể nào nắm vững được thì...), tương lai sẽ sụp đổ.",
    "Cấu trúc song hành 「～ようでもあり、～ようでもある」 biểu thị trạng thái không rõ ràng, mang cả hai tính chất cùng lúc. Trình tự logic: Định ngữ sở hữu 「彼の」 + định ngữ tính chất đột ngột 「突然の」 + chủ ngữ chính 「告白は、」 + danh từ tính chất thứ nhất 「冗談の」 + vế đầu cấu trúc song hành 「ようでもあり、」 + vế sau bổ sung kết thúc tính chất thứ hai 「本気のようでもあった」.": "Cấu trúc song hành 「～ようでもあり、～ようでもある」 (vừa có vẻ như là... lại vừa có vẻ như là...) vẽ ra trạng thái nước đôi mập mờ. Lời 「彼の突然の告白は」 (lời tỏ tình đường đột của anh ta). Nghe qua thì 「冗談のようでもあり」 (vừa có vẻ như là một trò đùa cợt), nhưng lại mang dấp dáng của sự chân thành phía sau."
}

for i in range(86, 103):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 4 Batch 3 (parts 86-102) manually reviewed and rewritten successfully!")
