import csv, os

dir_path = r'd:\pj\xx\ai-gen-quiz\mondai2_ordering\csv_filled\set_5_jlpt_exam'

rewrites = {
    # part_26
    "Cú pháp kết hợp: 名詞「独裁者」 + 「ですら」 đóng vai trò chủ ngữ biểu thị sự cực đoan (ngay cả một kẻ độc tài tàn bạo). Tiếp theo là cụm định ngữ 「無実の」 bổ nghĩa cho danh từ 「少女の涙」. Trợ từ 「には」 biểu thị đối tượng hướng tớiのcảm xúc. Cụm tân ngữ 「心を」 kết hợp với động từ bị động 「動かされた」 ở phần Suffix tạo thành cụm từ cố định 「心を動かされる」 (bị lay động tâm can). Thứ tự logic: Chủ ngữ -> Đối tượng tác động -> Tân ngữ -> Động từ.": "Cấu trúc 「～ですら」 (thậm chí ngay cả) biểu thị một mức độ cực đoan tưởng chừng vô lý. Mệnh đề bắt đầu bằng sự nhượng bộ tột độ 「独裁者ですら」 (ngay cả một kẻ độc tài tàn bạo). Kẻ đó đứng trước 「無実の少女の涙には」 (những giọt nước mắt của cô thiếu nữ vô tội). Và kết cục là 「心を動かされた」 (đã bị lay động tâm can).",
    "Cú pháp kết hợp: Tân ngữ 「自らの罪を」 (tội lỗiのbản thân) đi kèm với động từ thể từ điển 「認める」. Danh từ hóa hành động bằng cách thêm 「こと」 kết hợp với trợ từ biểu thị mức độ cực đoan 「すら」 tạo thành 「認めることすら」 (ngay cả việc thừa nhận). Phó từ 「頑なに」 (ngoan cố, bướng bỉnh) bổ nghĩa cho động từ hành vi 「拒んでいる」 (đang phủ nhận/cự tuyệt) ở và Suffix. Thứ tự logic: Tân ngữ -> Hành động bị phủ định cực đoan -> Cách thức thực hiện -> Động từ chính.": "Cấu trúc nhấn mạnh 「V-ることすら」 (đến ngay cả việc...). Nó vạch trần thái độ chối bỏ trách nhiệm. Đối với 「自らの罪を」 (tội lỗi của chính bản thân mình). Kẻ đó 「認めることすら」 (đến ngay cả việc thừa nhận cũng). Thái độ đó được bồi thêm bằng 「頑なに拒んでいる」 (đang ngoan cố cự tuyệt).",
    "Cú pháp kết hợp: Chủ ngữ là cụm danh từ 「初版本は」 được bổ nghĩa bởi 「この古い歴史小説の」. Phó từ 「今や」 (giờ đây) bổ nghĩa cho trạng thái hiện tại. Cấu trúc giá cả: 数量詞「10万円」 + Trợ từ nhấn mạnh 「も」 + Động từ chỉ giá trị 「する」 tạo thành cụm 「10万円もする」 (trị giá tới tận 10 vạn yên). Thứ tự logic: Chủ ngữ -> Thời gian -> Số tiền nhấn mạnh -> Động từ.": "Trợ từ 「も」 đi sau số lượng từ dùng để nhấn mạnh một mức độ cao vượt sức tưởng tượng. Đối tượng được định giá là 「この古い歴史小説の初版本は」 (ấn bản đầu tiên của cuốn tiểu thuyết lịch sử cũ kỹ này). Thời thế thay đổi, 「今や10万円も」 (giờ đây trị giá lên tới tận 10 vạn yên). Con số khổng lồ đó đi với động từ kết luận 「する」 (trị giá).",
    "Cú pháp kết hợp: Cụm định nghĩa 「激動の時代を描いた」 bổ nghĩa cho danh từ 「その小説は」 làm chủ ngữ. Tiếp theo là tân ngữ 「読者の胸を」. Phó từ mô tả trạng thái cảm xúc 「ワクワク」 kết hợp với động từ dạng sai khiến 「させて」 (làm cho rạo rực, hồi hộp) đi kèm với bổ trợ từ 「くれる」 ở Suffix thể hiện sự tác động mang lại trải nghiệm cho người đọc. Thứ tự logic: Định ngữ -> Chủ ngữ -> Tân ngữ -> Phó từ trạng thái -> Động từ cầu khiến.": "Cấu trúc sai khiến kết hợp cho nhận 「V-させてくれる」 (khiến cho... cảm thấy). Tác phẩm 「激動の時代を描いたその小説は」 (cuốn tiểu thuyết khắc họa thời đại đầy biến động đó). Nó tác động trực tiếp vào 「読者の胸を」 (trái tim của độc giả). Khiến họ có cảm giác 「ワクワクさせて」 (rạo rực, hồi hộp) và trải nghiệm đó được chốt lại bằng 「くれる」.",
    "Cú pháp kết hợp: Chủ ngữ 「政府は」 kết hợp cụm vế trước 「新しい規制を導入し」 (đưa ra quy định mới và...). Cụm tân ngữ tác động 「都市の空気を」. Tiếp theo là tính từ đuôi i biến đổi sang phó từ 「きれいに」 kết hợp với động từ 「する」 tạo thành cấu trúc tác động biến đổi trạng thái 「NをA-くする」 (làm cho cái gì trở nên như thế nào). Phần Suffix 「方針だ」 kết nối trực tiếp với động từ thể từ điển 「する」 tạo thành cụm 「chủ trương làm gì」. Thứ tự logic: Chủ thể/Hành động nguyên nhân -> Đối tượng bị tác động -> Trạng thái biến đổi -> Động từ tác động -> Danh từ kết thúc.": "Cấu trúc biến đổi trạng thái 「NをA-くする」 (làm cho... trở nên...). Đứng trước vấn nạn ô nhiễm, 「政府は新しい規制を導入し」 (chính phủ sẽ ban hành quy định mới và...). Mục tiêu là 「都市の空気を」 (bầu không khí của thành phố). Nó sẽ được 「きれいにする」 (làm cho trong sạch hơn), và đây chính là 「方針だ」 (chủ trương).",
    "Cú pháp kết hợp: Cụm danh từ chỉ nơi chốn 「深夜の古い洋館から」 (từ tòa biệt thự phương Tây cũ kỹ vào đêm muộn). Tính từ 「不気味な」 (rợn người) bổ nghĩa cho danh từ giác quan/âm thanh 「足音」. Cấu trúc cảm giác tự nhiên 「Nがする」 thể hiện việc tai nghe thấy âm thanh (phát ra âm thanh/tiếng động). Thứ tự logic: Nơi chốn phát ra -> Tính chất âm thanh -> Danh từ âm thanh + が -> Động từ しました.": "Cấu trúc cảm giác 「Nがする」 (cảm nhận thấy, nghe thấy). Bối cảnh tĩnh mịch 「深夜の古い洋館から」 (từ tòa biệt thự cổ kính giữa đêm khuya). Không gian đó phát ra một 「不気味な足音が」 (tiếng bước chân rợn tóc gáy). Âm thanh rùng rợn đó được chốt bằng động từ 「しました」 (đã vang lên).",
    "Cú pháp kết hợp: Cụm trạng ngữ phương thức 「本日の閣議決定をもちまして」 (thông qua quyết địnhのcuộc họp nội các hôm nay). Chủ ngữのmệnh đề chính là 「この法案は」. Cấu trúc quyết định trang trọng, mang tính pháp lý hoặc quy định: Động từ thể bị động 「可決された」 kết hợp danh từ hóa 「もの」 + 「とする」 (quy định là/xem như là đã được thông qua). Thứ tự logic: Phương thức thực hiện -> Đối tượng -> Trạng thái quy định -> Động từ kết luận.": "Cấu trúc trang trọng 「～ものとする」 (được coi như là, quy định là) mang tính chất tuyên bố. Căn cứ vào 「本日の閣議決定をもちまして」 (thông qua quyết định tại cuộc họp nội các ngày hôm nay). Đối tượng là 「この法案は」 (dự luật này). Nó chính thức 「可決されたものとする」 (được xem như là đã được thông qua).",
    "Cú pháp kết hợp: Chủ đềのcâu 「今回の連載コラムのテーマは」. Tiếp theo là nội dung lựa chọn 「現代の若者の労働観」 (quan điểm lao độngのgiới trẻ ngày nay). Trợ từ quyết định lựa chọn 「に」 kết hợp động từ 「する」 tạo thành 「労働観にする」. Để thể hiện ý chí quyết địnhのcá nhân người viết, ta dùng cấu trúc danh từ hóa quyết định hành vi 「Vことにする」 biến thành 「することにした」. Thứ tự logic: Chủ đề -> Nội dung chọn lựa + に -> Động từ quyết định.": "Cấu trúc biểu thị sự quyết định 「Nにする」 (chọn lấy N). Vấn đề cần lựa chọn là 「今回の連載コラムのテーマは」 (chủ đề của cột báo kỳ này thì). Nội dung được chốt hạ là 「現代の若者の労働観に」 (quan điểm lao động của giới trẻ ngày nay). Quyết định này do bản thân tự đưa ra bằng 「することにした」 (đã quyết định làm như thế).",
    "Cú pháp kết hợp: Chủ ngữ chỉ người 「記者は」. Trạng từ chỉ nơi chốn hành động diễn ra 「戦火の広がる街で」 (tại thành phố nơi ngọn lửa chiến tranh đang lan rộng). Cụm danh từ bổ nghĩa mức độ quyết tâm 「命がけの」 bổ nghĩa cho danh từ hành động 「取材」. Cấu trúc thực hiện hành động danh từ 「Nをする」 (thực hiện việc lấy tin/phóng sự). Thứ tự logic: Chủ thể -> Nơi chốn -> Tính chất hành động -> Danh từ hành động + を -> Động từ する.": "Cụm từ miêu tả hành động mang tính chất liều lĩnh 「命がけの」 (đánh cược cả tính mạng). Nhân vật 「記者は」 (người phóng viên). Tại một nơi hiểm nguy 「戦火の広がる街で」 (giữa thành phố chìm trong khói lửa chiến tranh). Anh ta tiến hành 「命がけの取材を」 (một cuộc phỏng vấn sinh tử). Và hành động đó được hoàn thiện bằng động từ 「する」 (thực hiện).",
    "Cú pháp kết hợp: Chủ ngữ 「その容疑者は」. Phó từ mơ hồ 「どこか」 (có gì đó) bổ nghĩa cho cụm tính chất ngoại hình. Cấu trúc miêu tả đặc điểm ngoại hình, bộ phận cơ thể: 「N（bộ phận/đặc điểm） をした + Danh từ chỉ người」. Ở đây 「冷たい目」 (ánh mắt lạnh lùng) + 「した」 bổ nghĩa cho danh từ 「男」 (người đàn ông) ở Suffix. Thứ tự logic: Chủ ngữ -> Phó từ -> Bộ phận/đặc điểm + を -> Động từ dạng た -> Danh từ người được miêu tả.": "Cấu trúc miêu tả đặc điểm, ngoại hình 「Nをした」 (có mang đặc điểm...). Đối tượng bị chú ý là 「その容疑者は」 (kẻ tình nghi đó). Hắn tỏa ra một thứ cảm giác 「どこか冷たい目を」 (có gì đó ở một ánh mắt lạnh lẽo). Ánh mắt ấy thuộc về 「した男」 (một gã đàn ông mang đặc điểm đó).",
    "Cú pháp kết hợp: Chủ ngữ 「私の祖父は」. Định ngữ chỉ phạm vi và nơi làm việc 「この地方のローカル紙の」 (tờ báo địa phươngのvùng này). Cấu trúc biểu thị nghề nghiệp đang đảm nhiệm: 「N（nghề nghiệp）をしている」. Ở đây 「記者」 (phóng viên) đi kèm với 「をしている」 ở và Suffix. Thứ tự logic: Chủ ngữ -> Nơi công tác -> Danh từ nghề nghiệp -> Động từ trạng thái chỉ công việc.": "Cấu trúc biểu thị vai trò, nghề nghiệp 「Nをしている」 (đang đảm nhận công việc/nghề...). Nhân vật chính 「私の祖父は」 (ông nội tôi). Nơi ông gắn bó là 「この地方のローカル紙の」 (của tờ báo địa phương vùng này). Nghề nghiệp ông làm là 「記者を」 (phóng viên). Vai trò đó được duy trì bằng động từ trạng thái 「している」 (đang đảm nhận).",
    "Cú pháp kết hợp: Cụm định ngữ 「金色の細い」 bổ nghĩa cho phụ kiện 「フレームの眼鏡」 (kính gọng mảnh màu vàng). Cấu trúc biểu thị việc đang đeo/mang phụ kiện trên người: 「N（đồ đeo） をした + Danh từ chỉ người」. Ở đây 「眼鏡をした」 bổ nghĩa cho danh từ 「老作家が」 (nhà văn già) làm chủ ngữ cho hành động tiếp theo. Suffix 「語り始めた」 được bổ nghĩa bởi phó từ 「静かに」. Thứ tự logic: Chi tiết phụ kiện -> Phụ kiện + を -> Động từ しました -> Chủ ngữ chỉ người đeo -> Cách thức -> Động từ hành động.": "Cấu trúc miêu tả trang phục, phụ kiện 「Nをした」 (đang mang/đeo...). Điểm nhấn ngoại hình là 「金色の細いフレームの」 (của một chiếc gọng kính mảnh màu vàng). Vật dụng được đeo là 「眼鏡をした老作家が」 (nhà văn lão thành đeo kính). Cụm này làm chủ ngữ cho hành động 「静かに語り始めた」 (đã bắt đầu tĩnh lặng kể chuyện).",
    "Cú pháp kết hợp: Chủ ngữ 「その若手作家は」. Cụm từ sở hữu 「自らの」 bổ nghĩa cho nguyên liệu thực tế 「戦争体験を」 (trải nghiệm chiến tranhのbản thân). Cấu trúc biến đổi/sử dụng cái này làm cái kia: 「N1をN2にする」. Ở đây đưa 「戦争体験」 làm N1, 「小説」 (tiểu thuyết) làm N2 kết hợp trợ từ 「に」 và dạng liên kết 「して」. Suffix là hành động kết quả 「発表した」. Thứ tự logic: Chủ thể -> Nguyên liệu gốc + を -> Sản phẩm chuyển hóa + に -> Động từ liên kết -> Hành động cuối.": "Cấu trúc biến đổi hoặc sử dụng mục đích 「N1をN2にする」 (lấy N1 biến thành N2). Nhân vật 「その若手作家は」 (nhà văn trẻ đó). Anh ta lấy chất liệu từ 「自らの戦争体験を」 (những trải nghiệm chiến tranh của chính mình). Biến nó 「小説にして」 (thành một cuốn tiểu thuyết) và cuối cùng 「発表した」 (đã công bố).",
    "Cú pháp kết hợp: Trạng từ thời gian 「明日の朝」. Trạng từ nơi chốn 「ホテルのロビーで」. Tân ngữ chỉ đối tượng tôn kính 「先生を」. Cấu trúc khiêm nhường ngữ hành vi chủ độngのbản thân hướng tới đối tượng kính trọng: 「お + Động từ thể ます (bỏ ます) + する」. Động từ 「迎える」 chuyển thành cụm khiêm nhường 「お迎えします」. Thứ tự logic: Thời gian -> Địa điểm -> Đối tượng tiếp đón -> Tiếp đầu ngữ khiêm nhường -> Động từ kết thúc.": "Cấu trúc khiêm nhường ngữ 「おV-する」 (tôi xin phép được...). Thông báo kế hoạch 「明日の朝」 (buổi sáng ngày mai). Địa điểm hẹn là 「ホテルのロビーで」 (tại sảnh khách sạn). Đối tượng đón tiếp là 「先生を」 (thầy giáo). Người nói hạ mình thực hiện hành động 「お迎えします」 (chúng em sẽ đi đón thầy).",
    "Cú pháp kết hợp: Mệnh đề điều kiện/bối cảnh 「社説を書くときは」 (khi viết bài xã luận). Tân ngữ hành động 「主観的な感情を」 (cảm xúc mang tính chủ quan). Cấu trúc cố gắng thực hiện (hoặc không thực hiện) một thói quen/hành vi: 「V-ようにする」. Ở đây dùng dạng phủ định 「交えない」 (không xen lẫn vào) + 「ようにしている」 (đang cố gắng duy trì việc...). Thứ tự logic: Bối cảnh hành động -> Đối tượng cần tránh -> Hành động phủ định + ように -> Động từ duy trì nỗ lực.": "Cấu trúc tạo lập thói quen 「V-ようにする」 (cố gắng giữ sao cho...). Trong tính chất công việc nghiêm túc 「社説を書くときは」 (khi chấp bút viết bài xã luận). Thứ bị bài trừ là 「主観的な感情を」 (những thứ tình cảm chủ quan). Người viết nỗ lực 「交えないようにしている」 (luôn cố gắng không để chúng xen lẫn vào).",
    "Cú pháp kết hợp: Tính từ bổ nghĩa 「過酷な」 đi kèm danh từ nguyên nhân tiêu cực 「労働環境」. Cấu trúc chỉ nguyên nhân dẫn đến kết quả xấu: 「N + のせいで」 (tại vì/do...). Tiếp theo là chủ ngữのvế kết quả 「多くの若手記者が」. Suffix là cụm động từ kết quả tiêu cực 「体調を崩している」 (gặp vấn đề sức khỏe). Thứ tự logic: Tính chất nguyên nhân -> Danh từ nguyên nhân + のせいで -> Chủ thể chịu hậu quả -> Hậu quả thực tế.": "Cấu trúc quy chụp trách nhiệm 「Nのせいで」 (tại vì, do...). Nguồn cơn cội rễ đến từ 「過酷な労働環境のせいで」 (do môi trường lao động quá sức khắc nghiệt). Nó trở thành gánh nặng khiến 「多くの若手記者が」 (rất nhiều phóng viên trẻ). Hậu quả nhãn tiền là 「体調を崩している」 (đang dần suy sụp về mặt thể chất).",
    "Cú pháp kết hợp: Cụm chủ ngữ danh từ hóa biểu thị kết quả khách quan 「この小説の結末が不条理に感じられるのは」 (Việc kết cụcのcuốn tiểu thuyết này tạo cảm giác phi lý là...). Tiếp theo là cụm định ngữ chỉ tác nhân gây ra nguyên nhân 「作者の」 (của tác giả) bổ nghĩa cho 「冷徹な世界観」 (thế giới quan lạnh lùng/buốt giá). Cấu trúc nhấn mạnh nguyên nhân tiêu cực: 「～のは～せいだ」 (Sở dĩ... là do...). Thứ tự logic: Hiện tượng/Kết quả được danh từ hóa + のは -> Chủ thể tác động -> Tính chất nguyên nhân -> Danh từ nguyên nhân + のせいだ.": "Cấu trúc truy nguyên lý do 「～のは...せいだ」 (sở dĩ... là lỗi tại...). Đặt vấn đề bằng 「この小説の結末が不条理に感じられるのは」 (sở dĩ kết cục của cuốn tiểu thuyết này đem lại cảm giác phi lý là do...). Nguồn gốc sâu xa chính là 「作者の冷徹な世界観のせいだ」 (là tại cái thế giới quan lạnh lẽo, buốt giá của chính người tác giả).",
    "Cú pháp kết hợp: Cụm thành ngữ/hành vi tiêu cực 「自分の筆力不足を棚に上げて」 (gạt bỏ/không thèm nhìn nhận sự thiếu năng lực viết láchのbản thân). Tiếp theo là đối tượng bị đổ lỗi 「編集者の」 (tại biên tập viên). Cấu trúc đổ lỗi cho ai/cái gì: 「Nのせいにする」. Ở đây kết hợp trợ từ 「に」 và động từ khuyên bảo mang tính nghĩa vụ phủ định 「すべきではない」 (không nên làm việc...). Thứ tự logic: Hành vi trốn tránh trách nhiệm -> Đối tượng bị đổ lỗi -> Cấu trúc đổ lỗi -> Động từ khuyên răn phủ định.": "Cấu trúc đổ thừa trách nhiệm 「Nのせいにする」 (đổ lỗi cho, quy tội cho). Thái độ vô trách nhiệm thể hiện qua việc 「自分の筆力不足を棚に上げて」 (tự lấp liếm đi sự yếu kém trong ngòi bút của chính mình). Sau đó lại đi trút lên đầu 「編集者のせいにする」 (đổ lỗi cho biên tập viên). Thói xấu này 「べきではない」 (hoàn toàn không nên chút nào).",
    "Cú pháp kết hợp: Cụm danh từ nguyên nhân mơ hồ 「連日の徹夜取材」 (việc thức đêm lấy tin suốt nhiều ngày liền). Cấu trúc chỉ nguyên nhân không chắc chắn: 「N + のせいか」 (Có lẽ là do...). Tiếp theo là chủ thể nhận biết kết quả 「彼の顔は」. Phó từ chỉ mức độ nặng nề 「ひどく」 bổ nghĩa cho cụm từ chỉ trạng thái sắc mặt ngoại hình ở Suffix 「土気色をしていた」 (sắc mặt xám ngoét như đất). Thứ tự logic: Thời gian/Tính chất nguyên nhân -> Nguyên nhân nghi vấn + のせいか -> Chủ thể nhận biết trạng thái -> Mức độ -> Trạng thái ngoại hình.": "Cấu trúc phỏng đoán nguyên nhân 「～のせいか」 (chắc có lẽ là tại vì...). Sự hao mòn thể chất do 「連日の徹夜取材のせいか」 (có lẽ vì những ngày lấy tin trắng đêm liên tục). Hệ quả hiện rõ lên trên mặt 「彼の顔はひどく」 (sắc mặt của anh ta cực kỳ...). Dẫn tới trạng thái tồi tệ 「土気色をしていた」 (mang màu xám ngoét như đất).",
    "Cú pháp kết hợp: Cụm chủ ngữ hạn định 「新人賞の原稿料など」 (Tiền nhuận bútのgiải thưởng dành cho nhà văn mới chẳng hạn). Phó từ chỉ mức độ tối đa, ít ỏi 「せいぜい」 (tối đa cũng chỉ/cùng lắm là). Tiếp theo là danh từ chỉ tính chất tạm thời 「一過性の」 bổ nghĩa cho danh từ kết quả 「生活費」. Cấu trúc phủ định đi kèm hạn định 「Nにしか＋ならない」 (chỉ có thể trở thành... chứ không hơn). Thứ tự logic: Chủ ngữ -> Phó từ đánh giá thấp -> Định ngữ -> Danh từ giới hạn + にしか -> Động từ phủ định.": "Cấu trúc hạ thấp giá trị 「せいぜい...にしかならない」 (cùng lắm cũng chỉ trở thành... mà thôi). Sự thật phũ phàng về khoản tiền 「新人賞の原稿料など」 (mấy khoản như tiền nhuận bút giải thưởng cho người mới). Thực chất 「せいぜい一過性の生活費にしか」 (cùng lắm cũng chỉ đáng để trang trải sinh hoạt phí nhất thời). Và chốt lại bằng 「ならない」 (chẳng thể thành cái gì khác hơn).",

    # part_30
    "\\「Mẫu ngữ pháp 『それに』 (N4) dùng để nối hai vế câu nhằm bổ sung thêm thông tin/lý do (hơn nữa, thêm vào đó). Thứ tự sắp xếp câu bình luận báo chí: Từ nối bổ sung tính chất (それに) -> Chủ ngữのvế sau kèm trợ từ nhấn mạnh も (価格も - giá cả cũng) -> Vị ngữ mang tính tiêu cực (高すぎる - quá đắt). và Suffix để trống vì câu đã kết thúc gọn ở .\\」": "Liên từ 「それに」 (thêm vào đó, hơn thế nữa) đóng vai trò bồi thêm một lý lẽ củng cố cho sự chê bai trước đó. Đỉnh điểm của sự bất mãn được đẩy lên bằng 「それに価格も」 (đã vậy thì mức giá lại còn). Nó đi liền với tính từ kết luận cực đoan 「高すぎる」 (quá đắt đỏ).",

    # part_32
    "「」だからこそ「 dùng ở đầu câu để nhấn mạnh lý do từ câu trước. 」命の危険「 (nguy hiểm tính mạng) làm tân ngữ cho động từ 」冒す「 (mạo hiểm). Mẫu 」冒してまで「 (đến mức mạo hiểm cả...) bổ nghĩa cho hành động đi đến chiến trường 」戦地に赴いた「. Thứ tự logic là: Nhấn mạnh nguyên nhân (だからこそ) -> Đối tượng nguy hiểm (命の危険を) -> Hành động mạo hiểm (冒してまで) -> Nơi đến (戦地に) -> Kết thúc câu (赴いたのだ)。」`": "Cấu trúc 「～てまで」 (đến mức độ phải... thì) nhấn mạnh sự hy sinh cực độ. Lấy lý do làm bàn đạp 「だからこそ」 (chính vì thế nên). Người đó dám lấy mạng sống ra đặt cược 「命の危険を冒してまで」 (tới mức phải đối mặt với ranh giới sinh tử). Để đổi lấy việc dấn thân vào 「戦地に赴いたのだ」 (bước chân ra ngoài chiến trường).",
    "「」だからといって「 đứng đầu câu tiếp theo để phủ định một suy luận thông thường (kết cục bi kịch -> tuyệt vọng). 」読者に「 (cho độc giả) chỉ đối tượng tiếp nhậnのhành động 」与える「 (mang lại). 」絶望を「 là tân ngữ trực tiếpの」与える「. Cấu trúc 」与えるわけではない「 (không có nghĩa là mang lại) đi liền nhau để phủ định nhẹ nhàng. Thứ tự: Liên từ chỉ sự nhượng bộ (だからといって) -> Đối tượng tiếp nhận (読者に) -> Tân ngữ (絶望を) -> Cụm phủ định (与えるわけではない)。」`": "Cấu trúc 「～わけではない」 (không có nghĩa là...) đập tan một suy luận một chiều. Khởi đầu bằng sự lật kèo 「だからといって」 (nhưng không phải cứ thế là). Mũi nhọn hướng về phía 「読者に絶望を」 (sự tuyệt vọng dành cho độc giả). Và lập tức bị phủ định lại bởi 「与えるわけではない」 (không có nghĩa là tác phẩm sẽ mang lại điều đó).",

    # part_34
    "Cấu trúc N4 「だといい」 thể hiện mong muốn, hy vọng (Giá mà... thì tốt). Trong hội thoại, người B phản hồi lại lời người A bằng cụm 「だといい」 đi kèm 「のですが」 (tuy nhiên...) thể hiện sự e ngại. Thứ tự logic: khởi đầu hội thoại 「本当に、」 -> cụm giả định 「だと」 -> tính từ 「いい」 -> từ nối lấp lửng 「のですが、」 -> chủ ngữ vế sau 「現実は」 -> tính từ kết luận 「厳しいでしょう。」」.": "Cấu trúc kỳ vọng 「～だといいのですが」 (giá mà được thế thì tốt biết mấy, ngặt nỗi...). Người nói khao khát 「本当に、だといいのですが」 (quả thật, nếu được như vậy thì mừng quá, nhưng mà). Thực tại tàn khốc lập tức đập tan mộng tưởng 「現実は厳しいでしょう」 (thực tế chắc hẳn sẽ muôn phần khắc nghiệt).",
    "Liên từ 「だといって」 (Dẫu nói là thế/Tuy nhiên) dùng để chuyển ý trái ngược với vế trước. Ở vế sau, cấu trúc 「わけにもいかない」 (Không thể... vì lý do đạo đức/xã hội) bổ nghĩa cho hành động 「退陣させる」 (bắt thoái vị). Thứ tự logic: vế dẫn nhập -> cụm chuyển ý 「だといって」 -> trạng từ chỉ thời gian 「すぐに」 kết hợp động từ 「退陣させる」 -> cụm phủ định 「わけにもいかない」.": "Cấu trúc kìm kẹp 「～わけにはいかない」 (không thể làm thế được vì luân thường đạo lý). Dùng sự nhượng bộ 「だといって」 (cho dù nói là vậy đi chăng nữa). Cũng không thể nào nhắm mắt làm liều 「すぐに退陣させる」 (bắt thoái vị ngay lập tức). Trói buộc cuối cùng là 「わけにもいかない」 (cũng đâu có thể làm như vậy được).",
    "Cấu trúc N1 「Nだにしない」 mang nghĩa 「ngay cả... cũng không」 (thường dùng với các từ liên quan đến tâm trí như 想像, 考える, 夢). Ở đây danh từ kết hợp là 「想像」 (tưởng tượng). Thứ tự logic: nguyên nhân 「巨大地震によって」 -> nội dung giả định 「都市が壊滅する」 -> từ hạn định nhấn mạnh 「などとは」 kết hợp chủ từ 「誰も」 -> danh từ 「想像」 -> trợ từ nhấn mạnh 「だに」 -> động từ phủ định 「しなかった」 tạo thành 「想像だにしなかった」 (thậm chí không dám tưởng tượng).": "Cấu trúc phủ định tột độ 「～だにしない」 (đến cả... cũng chưa từng). Một thảm họa tàn khốc 「巨大地震によって都市が壊滅する」 (thành phố bị hủy diệt hoàn toàn bởi trận siêu động đất). Đối với một kịch bản 「などとは誰も想像」 (như thế thì quả thực không một ai). Đủ sức để nghĩ tới 「だにしなかった」 (ngay cả trong tưởng tượng cũng chưa từng).",
    "Phó từ phỏng đoán 「たぶん」 (có lẽ/chắc là) thường đứng ở đầu câu phỏng đoán và đi kèm với đuôi câu 「でしょう」 ở cuối. Thứ tự sắp xếp các thành phần: Cụm trích dẫn nguồn tin 「編集長によると」 -> phó từ 「たぶん」 kết hợp trạng ngữ thời gian 「明日の」 -> trạng ngữ chỉ nơi chốn 「新聞に」 -> chủ ngữ 「そのニュースが」 -> động từ 「出る」 -> đuôi phỏng đoán 「でしょう」.": "Phó từ phỏng đoán 「たぶん」 (có lẽ, chắc mẩm là) bọc lót cho một thông tin rò rỉ. Bắt nguồn từ 「編集長によると」 (theo lời của tổng biên tập). Dự báo khả năng 「たぶん明日の新聞に」 (có lẽ là trên mặt báo ngày mai). Sự kiện 「そのニュースが出るでしょう」 (cái tin tức đó sẽ được đưa lên thôi).",
    "Tính từ 「たまらない」 (Không thể chịu nổi/Rất kinh khủng) được dùng để biểu thị sự đồng cảm sâu sắc với tình huống khó khănのđối phương. Theo sau là câu khuyên nhủ với trạng từ 「早く」 -> cấu trúc khuyên bảo 「V-たほうが」 -> kết thúc bằng 「いいよ」. Thứ tự logic: B:「 (Prefix) -> chủ từ chỉ sự việc đối phương vừa nói 「それは」 -> tính từ cảm thán 「たまらないね。」 -> phó từ 「早く」 -> cụm động từ khuyên nhủ 「休んだほうが」 -> 「いいよ。」」.": "Cấu trúc khuyên nhủ 「V-たほうがいい」 (làm... thì sẽ tốt hơn đấy). Bộc lộ sự đồng cảm sâu sắc 「それはたまらないね」 (như vậy thì thật là quá đáng sợ/kinh khủng). Lời khuyên chân thành được đưa ra 「早く休んだほうがいいよ」 (nên mau chóng nghỉ ngơi đi thì hơn).",
    "Cấu trúc 「V-たい + てたまらない」 (Muốn... không chịu nổi) dùng để diễn tả mong muốn cực kỳ mãnh liệtのbản thân. Động từ thể mong muốn 「会いたい」 được chia sang thể Te là 「会いたくて」 để liên kết với 「たまらない」. Thứ tự sắp xếp: Trạng từ thời gian vế dẫn 「故郷を離れて十年、」 -> phó từ thời gian vế sau 「最近は」 -> phó từ chỉ trạng thái 「無性に」 (vô cớ/rất nhiều) -> đối tượng hành động 「両親に」 -> động từ chia thể Te 「会いたくて」 -> từ bổ trợ cảm xúc 「たまらない」.": "Cấu trúc cảm xúc bùng nổ 「～てたまらない」 (muốn... đến mức không thể chịu nổi). Trạng thái thôi thúc 「最近は無性に」 (gần đây không hiểu sao tự nhiên lại). Nỗi nhớ trào dâng hướng về 「両親に会いたくて」 (những lúc nhớ cồn cào muốn gặp lại cha mẹ). Chốt lại bằng 「たまらない」 (đến độ không thể nào kìm nén được nữa).",
    "Cấu trúc 「V-るために」 biểu thị mục đíchのmột hành động chủ ý (để làm V). Ở đây động từ thể từ điển 「伝える」 (truyền tải) đi liền sau tân ngữ 「真実を」 (sự thật). Thứ tự sắp xếp: Chủ từ 「その記者は」 -> tân ngữ vế chỉ mục đích 「真実を」 -> động từ mục đích 「伝える」 -> liên từ chỉ mục đích 「ために、」 -> trạng từ chỉ phạm vi không gian 「世界中を」 -> động từ hành động chính 「旅している」.": "Cấu trúc mục đích tối thượng 「～ために」 (để, vì mục đích). Con người mang lý tưởng 「その記者は」 (người phóng viên ấy). Sứ mệnh anh ta theo đuổi là 「真実を伝えるために」 (để có thể truyền tải sự thật). Anh ta đã và đang 「世界中を旅している」 (đi du hành khắp nơi trên toàn thế giới).",
    "Cấu trúc 「Nのため」 biểu thị nguyên nhân, lý do khách quan (bởi vì N). Ở đây danh từ chỉ nguyên nhân là 「大雨」. Thứ tự sắp xếp: Định ngữ chỉ thời gian kéo dài 「連日の」 -> danh từ nguyên nhân kết hợp trợ từ 「大雨のため、」 đi kèm định ngữ 「川の」 -> chủ ngữ vế kết quả và trạng từ 「水位が急激に」 -> động từ chia thể て 「上昇して」 -> kết thúc bằng trợ động từ 「いる」.": "Cấu trúc lý do mang tính hệ quả 「Nのため」 (bởi vì, do...). Bắt nguồn từ tai ương thiên nhiên 「連日の大雨のため」 (do những trận mưa lớn xối xả kéo dài nhiều ngày). Nó dẫn đến hệ quả 「川の水位が急激に」 (mực nước con sông dâng lên một cách đột ngột). Trạng thái đó được phản ánh qua 「上昇している」 (hiện đang không ngừng tăng cao).",
    "Cấu trúc 「ひとつには～ためである」 dùng để phân tích và nêu ra một trong những nguyên nhân chínhのmột thực trạng khó khăn nào đó. Thứ tự logic: Nêu thực trạng cần giải thích ở dạng định ngữ 「この地域で人口が減少しているのは、」 -> trạng từ chỉ lý do thứ nhất 「ひとつには」 -> chủ ngữのnguyên nhân 「若者が」 -> hướng di chuyển 「都会へ」 -> động từ quá khứ 「流出した」 -> kết luận nguyên nhân 「ためである」.": "Cấu trúc bóc tách nguyên nhân 「ひとつには～ためである」 (một phần cũng là do...). Đối mặt với bài toán 「この地域で人口が減少しているのは」 (sở dĩ dân số ở khu vực này đang ngày một thuyên giảm). Nguyên nhân đầu tiên phải kể đến 「ひとつには若者が都会へ」 (một phần là bởi người trẻ kéo nhau ra chốn thành thị). Quy chiếu vào hệ quả 「流出したためである」 (bởi sự chảy máu chất xám đó).",

    # part_49
    "Cấu trúc 「AというよりB」 dùng để so sánh hai nhận định, chỉ ra rằng cách gọi B chính xác hơn A (hơn là nói là A, thực chất là B). Trong bối cảnh báo chí chính trị: Chính sách mới thực chất là tăng thuế 「増税」 hơn là hỗ trợ 「支援」. Thứ tự sắp xếp từ trái qua phải: 「国民への」 bổ nghĩa cho danh từ 「支援」, tiếp sau là cụm so sánh 「というより」 và cụm bổ nghĩa danh từ 「実質的な」 đi với danh từ kết luận 「増税である」.": "Cấu trúc phản biện 「AというよりB」 (nói là B thì đúng hơn là A). Lột trần bản chất thật của sự việc 「国民への支援というより」 (thay vì nói đó là sự hỗ trợ dành cho người dân). Thực chất đằng sau tấm bình phong đó là 「実質的な増税である」 (nó chính xác là một đợt tăng thuế thực tế ngầm).",
    "Cấu trúc 「AといえばAが（だが）」 biểu thị việc chấp nhận nhận định A ở một mức độ nào đó, nhưng vế sau lập tức chỉ ra điểm hạn chế hoặc tiêu cực. Tính từ 「詳細」 (chi tiết) được lặp lại thành 「詳細といえば詳細だが」. Thứ tự logic: Giới thiệu chủ ngữ 「このルポルタージュは」 -> đưa ra điểm tốt 「詳細といえば詳細だが」 -> chỉ ra điểm hạn chế 「客観性に欠ける部分がある」.": "Cấu trúc nhượng bộ miễn cưỡng 「～といえば～だが」 (có thì đúng là có... nhưng mà). Đánh giá về tác phẩm 「このルポルタージュは詳細といえば」 (bài phóng sự này nếu bảo là chi tiết thì). Sự xác nhận gượng gạo 「詳細だが」 (đúng là chi tiết thật đấy, nhưng ngặt nỗi). Kéo theo sau đó là điểm yếu chí mạng 「客観性に欠ける部分がある」 (lại tồn tại những góc khuất thiếu đi tính khách quan).",
    "Cấu trúc 「V-たことといえば～ぐらいのことだ」 dùng để giới hạn phạm vi, mang nghĩa 「nếu có điều gì đáng nói thì cũng chỉ ở mức... mà thôi」. Thứ tự sắp xếp đi từ cụm bổ nghĩa chủ thể 「その作家の私生活について」 -> danh từ hóa hành động tìm hiểu 「知られていることといえば」 -> nội dung giới hạn 「時折エッセイを発表する」 -> vế giới hạn mức độ 「ぐらいのことだ」.": "Cấu trúc khoanh vùng phạm vi 「～ことといえば...ぐらいのことだ」 (nhắc đến thì cũng chỉ quẩn quanh chuyện...). Xoáy vào chủ đề 「その作家の私生活について」 (nói về cuộc sống đời tư của vị tác gia đó). Thông tin thưa thớt 「知られていることといえば」 (những thứ người ta biết được thực chất). Chung quy lại cũng chỉ 「時折エッセイを発表するぐらいのことだ」 (cùng lắm là xoay quanh dăm ba bài tản văn thi thoảng được đăng tải mà thôi).",

    # part_50
    "Mẫu ngữ pháp là cụm cố định 「一口に～といっても」 (Nói chung là... nhưng thực ra). Bắt đầu bằng phó từ 「一口に」, tiếp sau là danh từ chỉ đối tượngのcâu nói 「現代文学と」 (với văn học hiện đại). Tiếp đến là phần còn lạiのngữ pháp 「いっても」 kết hợp với từ chỉ định 「その」 (của nó) để liên kết logic với danh từ chủ ngữのvế sau là 「ジャンルは」 (thể loại). Vế sau kết thúc bằng vị ngữ 「多岐にわたっている」 (trải rộng nhiều lĩnh vực). Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc 「一口に～といっても」 (dẫu có gọi chung là... thì bề trong vẫn). Bóc tách sự đa dạng ẩn sau một khái niệm 「一口に現代文学といっても」 (dẫu có nói tóm gọn bằng bốn chữ văn học hiện đại đi chăng nữa). Đi sâu vào bản thể 「そのジャンルは多岐にわたっている」 (thể loại của nó cũng tỏa nhánh rộng khắp muôn vàn lĩnh vực).",
    "Cấu trúc ngữ pháp hoàn chỉnh là 「～といってもいいだろう」 (Có thể nói là...). Chủ ngữのcâu là 「彼の最新作は」 (Tác phẩm mới nhấtのanh ấy). Tiếp sau là bổ ngữ chỉ phạm vi 「今年の文芸界を」 (cho giới văn học năm nay) đi kèm động từ định ngữ 「代表する」 (đại diện cho). Cụm định ngữ này bổ nghĩa cho danh từ 「名作」, kết hợp với trợ từ trích dẫn tạo thành 「名作だと」 ở Chunk3. Sau đó đi liền với phần ngữ pháp 「いっても」 và kết câu bằng đuôi giả định 「いいだろう」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc xác quyết phỏng đoán 「～といってもいいだろう」 (hoàn toàn có thể khẳng định rằng). Tôn vinh giá trị của tác phẩm 「彼の最新作は今年の文芸界を」 (tác phẩm mới nhất của anh ấy năm nay trên văn đàn). Gắn cho nó danh xưng 「代表する名作だと」 (được xem là kiệt tác đại diện). Lời tán dương được chốt lại bằng 「いってもいいだろう」 (cho dù có nói như thế cũng chẳng ngoa).",
    "Cấu trúc ngữ pháp là 「～といってもいいすぎではない」 (Nói là... cũng không quá lời). Chủ ngữ là 「電子書籍の普及は」 (Sự phổ biếnのsách điện tử). Định ngữ 「読書習慣の」 (của thói quen đọc sách) bổ nghĩa cho danh từ 「革命」, kết hợp với trợ từ trích dẫn tạo thành 「革命だと」. Theo sau là ngữ pháp trích dẫn 「いっても」 và phần phó từ phủ định nhấn mạnh 「言い過ぎでは」 ở Chunk4, cuối cùng kết thúc bằng vị ngữ phủ định 「ない」 ở Suffix để hoàn thành câu. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc cường điệu hóa sự việc 「～といっても言い過ぎではない」 (dẫu nói là... thì cũng chẳng có gì là phóng đại). Đánh giá sức công phá của 「電子書籍の普及は読書習慣の」 (sự bành trướng của sách điện tử đối với thói quen đọc sách). Gán cho nó nhãn hiệu 「革命だといっても」 (dù có gọi đó là một cuộc cách mạng đi chăng nữa). Thì cũng 「言い過ぎではない」 (chẳng hề nói ngoa chút nào).",
    "Ngữ pháp N1 「NといわずNといわず」 mang ý nghĩa 「bất kể là N hay N, tất cả đều...」. Ở đây, hai danh từ chỉ nơi chốn trong tiểu thuyết là 「屋根」 (mái nhà) và 「庭」 (sân vườn) được dùng để miêu tả cảnh tuyết. Cú pháp song hành yêu cầu xen kẽ danh từ với trợ từ 「と」 và động từ liên kết dạng lửng 「いわず」. Do đó, ta ghép thứ tự lần lượt: 「屋根と」 -> 「いわず、」 -> 「庭と」 -> 「いわず、」. Suffix là mệnh đề kết quả bao trùm 「すべてが白一色に染まった」 (tất cả nhuộm một màu trắng xóa). Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc liệt kê bao trùm 「～といわず～といわず」 (bất kể là... hay là...). Màn đêm trắng bao phủ vạn vật 「屋根といわず、庭といわず」 (không màng là trên mái ngói, hay là dưới mảnh sân). Sự đồng nhất không ranh giới 「すべてが白一色に染まった」 (tất thảy vạn vật đều bị nhuộm thắm một màu tang trắng).",
    "Cấu trúc ngữ pháp 「どうしても～たい」 biểu thị ý chí, mong muốn mãnh liệt (bằng mọi giá muốn...). Sau trạng ngữ 「私はあの時」 (Tôi lúc đó), phó từ 「どうしても」 đứng đầu để bổ nghĩa cho mong muốn ở cuối câu. Tiếp đến là tân ngữ chỉ đối tượng 「真実を」 (sự thật) và đối tượng nhận hành động 「彼女に」 (cho cô ấy). Sau đó là động từ mang ý chí 「伝えた」 kết hợp với đuôi tính từ ước muốn thì quá khứ 「かった」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc khát vọng bùng cháy 「どうしても～たい」 (dù thế nào đi nữa cũng muốn...). Quay ngược dòng kýức 「私はあの時どうしても」 (vào cái lúc bấy giờ, tôi đã dặn lòng bất chấp mọi giá). Một khao khát duy nhất 「真実を彼女に」 (đem sự thật này đến cho cô ấy). Khao khát ấy tuôn trào qua 「伝えたかった」 (khao khát truyền đạt lại).",
    "Cấu trúc ngữ pháp 「どうしても～ない」 biểu thị ý nghĩa 「dù cố gắng thế nào đi nữa cũng không thể...」. Sau chủ ngữ 「過去のつらい記憶は」 (Ký ức đau buồn quá khứ), ta đặt phó từ 「どうしても」 ở đầu vế để bổ nghĩa phủ định. Tiếp theo là trạng ngữ chỉ nơi chốn 「頭から」 (khỏi đầu óc) làm rõ nghĩa cho hành động. Cụm danh từ hóa hành động 「消し去ることが」 (việc xóa bỏ) đóng vai trò tân ngữ khả năng, đi liền với động từ khả năng dạng liên dụng 「でき」 ở Chunk4 và kết thúc bằng phủ định 「ない」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc bất lực tận cùng 「どうしても～ない」 (dù có làm gì đi nữa cũng mãi chẳng thể). Những vết sẹo thời gian 「過去のつらい記憶はどうしても」 (những ký ức đớn đau của quá khứ, dù có cố gắng cách mấy). Nỗ lực gột rửa 「頭から消し去ることが」 (việc muốn tẩy trắng chúng ra khỏi tâm trí). Đều trở nên vô vọng 「できない」 (chẳng tài nào thực hiện được).",
    "Cấu trúc ngữ pháp 「Nと同時に」 (Đồng thời với N). Đầu tiên, định ngữ 「新政府の」 (của chính phủ mới) bổ nghĩa cho danh từ 「発足」 (sự thành lập/ra mắt), kết hợp trợ từ tạo thành cụm 「発足と」. Tiếp sau là danh từ chỉ sự đồng thời 「同時に」 đi kèm tính từ bổ nghĩa 「新しい」 (mới). Tính từ này bổ nghĩa trực tiếp cho danh từ chủ ngữ vế sau 「経済政策が」 (chính sách kinh tế). Cuối cùng kết thúc bằng vị ngữ bị động 「発表された」 (đã được công bố). Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc song hành thời gian 「～と同時に」 (vào đúng khoảnh khắc đó, cùng lúc). Sự kiện bùng nổ 「新政府の発足と同時に」 (ngay vào giây phút chính phủ mới vừa tuyên thệ nhậm chức). Một làn sóng mới lập tức dội tới 「新しい経済政策が発表された」 (những chính sách kinh tế tân tiến cũng đồng loạt được ban bố).",
    "Cấu trúc ngữ pháp 「であると同時に」 (đồng thời là.../vừa là... vừa là...). Sau chủ ngữ 「彼は」 (Anh ấy), ta có danh từ định danh thứ nhất 「優れた小説家」 (nhà tiểu thuyết xuất sắc) đi kèm hệ từ 「であると」 ở Chunk2. Tiếp sau là danh từ ngữ pháp 「同時に」 biểu thị sự song hành, đi cùng tính từ 「鋭い」 (sắc sảo). Tính từ này bổ nghĩa trực tiếp cho danh từ thứ hai 「社会批評家」 (nhà phê bình xã hội) ở Chunk4. Kết thúc bằng hệ từ nhấn mạnh 「でもある」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc hiện thân kép 「～であると同時に」 (vừa mang thân phận này, lại đồng thời gánh vác vai trò kia). Con người anh ta đa diện 「彼は優れた小説家であると同時に」 (anh không chỉ đơn thuần là một cây bút tiểu thuyết tài ba). Bản ngã thứ hai của anh ta là 「鋭い社会批評家でもある」 (mà còn thủ vai một nhà phê bình xã hội đầy tính gai góc).",
    "Liên từ 「同時に」 đứng đầu câu thứ hai để liên kết bổ sung ý nghĩa đồng thời cho hai câu độc lập. Tiếp theo là tân ngữ phản thân 「自分自身を」 (chính bản thân mình) đi với động từ định ngữ 「見つめ直す」 (nhìn nhận lại) để bổ nghĩa cho danh từ cơ hội phía sau. Tiếp sau là tính từ định ngữ 「絶好の」 (tuyệt vời) bổ nghĩa trực tiếp cho danh từ kết thúc 「機会でもある」 (cũng là cơ hội) ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Liên từ 「同時に」 (song song với đó) mở ra một chiều kích khác của sự việc. Cơ hội thứ hai hiện hình 「同時に、自分自身を見つめ直す」 (đó đồng thời cũng là lúc để ta tự phán xét lại chính bản ngã của mình). Và nó được đánh giá là 「絶好の機会でもある」 (một thời cơ ngàn năm có một).",
    "Trạng từ biểu thị sự buông xuôi, phó mặc 「どうせ」 (đằng nào thì...) luôn đứng ở đầu câu/vế để bổ nghĩa cho sắc thái phỏng đoán phủ định ở cuối câu. Tiếp sau là chủ ngữ 「私の小説」 (tiểu thuyếtのtôi). Để thể hiện thái độ tự ti, hạ thấp, danh từ đi kèm trợ từ 「なんて」 và tác nhân hành động 「誰にも」 (bởi bất kỳ ai) ở Chunk3. Động từ bị động phủ định 「理解されない」 nằm ở Chunk4 và đi liền với đuôi phỏng đoán mang tính cảm thán 「のだろう」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Phó từ buông xuôi 「どうせ」 (dẫu sao thì, đằng nào cũng) nhuốm màu yếm thế. Cảm giác bất lực tự ti 「どうせ私の小説なんて」 (rút cục thì dăm ba cái cuốn tiểu thuyết rẻ tiền của tôi). Niềm tin sụp đổ hoàn toàn 「誰にも理解されないのだろう」 (cũng chẳng có lấy một ai thấu cảm nổi đâu).",
    "Cấu trúc ngữ pháp 「どうせ～のなら」 biểu thị ý chí 「nếu đằng nào cũng... thì thà...」. Trạng từ 「どうせ」 đi kèm tân ngữ 「記事を」 (bài báo) ở đầu vế. Động từ và cấu trúc điều kiện giả định 「書くのなら」 (nếu viết) đứng sau tạo thành vế giả định hoàn chỉnh ở Chunk2. Tiếp theo là cụm tân ngữのvế sau 「読者の心を」 (trái tim người đọc) đi liền với mệnh đề bổ nghĩa quan hệ 「揺さぶるものを」 (thứ lay động). Suffix kết thúc bằng động từ mong muốn 「書きたい」 (muốn viết). Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc phá vỡ lối mòn 「どうせ～のなら」 (nếu đã trót bề nào cũng vậy, chi bằng). Lựa chọn nổi loạn 「どうせ記事を書くのなら」 (đã mất công chắp bút viết nên một bài báo). Đích ngắm phải là 「読者の心を揺さぶるものを」 (thứ gì đó đủ sức xé toạc và làm chấn động tâm can độc giả). Tham vọng ấy bùng nổ qua 「書きたい」 (khao khát được viết ra).",
    "Cấu trúc ngữ pháp 「どうせ～以上は」 (một khi đã... thì đằng nào cũng...). Bắt đầu bằng trạng từ 「どうせ」 kết hợp với tân ngữ chỉ con đường 「この道を」. Cụm từ liên kết chỉ điều kiện hiển nhiên 「選ぶ以上は」 (một khi đã chọn) nằm ở Chunk2. Tiếp sau là trạng ngữ chỉ thời gian/tình huống 「途中で」 (giữa chừng) bổ nghĩa cho cụm từ cấm đoán 「諦めるわけには」 (không thể từ bỏ) ở Chunk4, kết hợp đuôi động từ 「いかない」 ở Suffix để hoàn thành mẫu ngữ pháp 「～わけにはいかない」. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc trói buộc sinh tử 「～以上は」 (một khi đã... thì không có đường lui). Bản án đã được định đoạt 「どうせこの道を選ぶ以上は」 (một khi thân này đã quyết dấn bước vào con đường đó). Lệnh ân xá là điều xa xỉ 「途中で諦めるわけにはいかない」 (thì chẳng có cái tư cách gì mà đòi giương cờ trắng đầu hàng giữa chừng cả).",
    "Cấu trúc ngữ pháp biểu thị nguyên nhân mang thái độ buông xuôi 「どうせ～のだから」 (đằng nào thì cũng... nên...). Bắt đầu bằng trạng từ 「どうせ」 đi cùng chủ ngữ phủ định 「誰も」 (không ai). Vế nguyên nhân kết hợp ngữ pháp 「読んでいないのだから」 (vì không đọc) nằm ở Chunk2. Tiếp theo là trạng từ chỉ tính chất và định ngữ 「自由に自分の」 (một cách tự do,のbản thân) bổ nghĩa cho danh từ tân ngữ 「思いを」 (suy nghĩ/tâm tư) ở Chunk4. Kết thúc bằng lời khuyên 「書けばいい」 (chỉ cần viết là được) ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc buông thả 「どうせ～のだから」 (cái cơ sự đằng nào nó cũng đã vậy, nên cứ). Bứt đứt sợi dây kìm kẹp 「どうせ誰も読んでいないのだから」 (đằng nào thì cũng có ma nào thèm đọc đâu). Tâm thế tự tại 「自由に自分の思いを書けばいい」 (tội gì mà không mặc sức múa bút tuôn trào hết tâm tư cho nhẹ nhẹ lòng).",
    "Cấu trúc ngữ pháp 「どうせのことだから」 là trạng ngữ cố định nghĩa là 「đằng nào thì sự việc cũng thế rồi, nên...」, được tách ra làm hai phần 「どうせの」 bổ nghĩa cho 「ことだから、」 ở Chunk2. Tiếp theo là chủ ngữのvế hành động phía sau 「この結末は」 (kết cục này) đi liền với cụm danh từ biểu thị sự chuyển đổi trạng thái 「ハッピーエンドに」 (thành một kết thúc có hậu). Kết thúc bằng động từ thể ý chí quyết định 「しよう」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cụm trạng ngữ mặc kệ đời 「どうせのことだから」 (nước đã đến chân rồi, tới đâu thì tới). Lời thú tội 「どうせのことだから、この結末は」 (sự thể cũng đã đến nước này, vậy cái kết cục này). Quyết định nhắm mắt đưa chân 「ハッピーエンドにしよう」 (thôi thì cứ phết cho nó một cái kết có hậu đi cho xong chuyện).",
    "Cấu trúc so sánh 「N同然に」 (như thể N, giống hệt như N). Sau cụm từ chủ - tân ngữ 「彼は私を」 (Anh ấy đối với tôi), ta có danh từ chuẩn so sánh 「実の弟」 (em trai ruột) kết hợp với danh từ bổ trợ trạng từ hóa 「同然に」 ở Chunk2. Tiếp sau là động từ dạng liên dụng lửng để nối câu 「扱い、」 (đối xử và...). Trạng từ 「優しく」 (một cách dịu dàng) bổ nghĩa cho động từ kết câu 「見守ってくれた」 (đã dõi theo) ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc đồng nhất hóa 「N同然に」 (xem như thể là, y hệt như). Ranh giới huyết thống bị lu mờ 「彼は私を実の弟同然に扱い」 (anh ấy bao bọc tôi coi tôi hệt như núm ruột của mình). Sự quan tâm vô điều kiện 「優しく見守ってくれた」 (luôn dành cho tôi ánh nhìn chở che hiền từ nhất).",
    "Cấu trúc so sánh ngang bằng cho hành động 「V-たも同然だ」 (coi như là đã V, không khác gì đã V). Sau mệnh đề giả thiết ở Prefix, ta có chủ ngữ 「計画は」 (kế hoạch). Tiếp theo là động từ thể quá khứ đi kèm trợ từ nhấn mạnh 「成功したも」 ở Chunk2 và danh từ bổ trợ so sánh 「同然」 ở Chunk3. Từ này kết hợp với hệ từ dạng liên kết 「であると」 ở Chunk4 để làm trạng ngữ trích dẫn cho động từ khẳng định 「言える」 (có thể nói là...) ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Cấu trúc coi như đã an bài 「V-たも同然だ」 (coi như mười mươi là đã...). Sự quả quyết chắc nịch 「計画は成功したも同然であると」 (phi vụ này coi như ván đã đóng thuyền, nắm chắc phần thắng). Phán quyết cuối cùng 「言える」 (có thể ngẩng cao đầu mà tuyên bố như vậy).",
    "Cấu trúc phó từ phủ định hoàn toàn 「とうてい～ない」 (hoàn toàn không thể...). Sau trạng ngữ chỉ bối cảnh ở Prefix, chủ ngữのmệnh đề sau được chia thành định ngữ 「新規採用の」 (của tuyển dụng mới) bổ nghĩa cho danh từ chủ đề 「拡大は」 (việc mở rộng). Tiếp theo là phó từ nhấn mạnh sự phủ định 「とうてい」 bổ nghĩa cho động từ khả năng chia ở dạng phủ định, vốn được tách thành gốc động từ 「望め」 ở Chunk4 và đuôi phủ định 「ない」 ở Suffix. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Phó từ triệt tiêu hy vọng 「とうてい～ない」 (nhắm mắt cũng thấy là vô phương). Cánh cửa khép lại 「新規採用の拡大はとうてい」 (với tình cảnh này, đòi hỏi phải mở rộng quy mô chiêu mộ nhân tài). Thì cái sự hão huyền đó 「望めない」 (bói đâu ra cửa sáng mà mộng với mơ).",
    "Phó từ 「とうとう」 biểu thị một kết quả rốt cuộc cũng xảy ra sau một quá trình dài (cuối cùng thì). Sau cụm từ chỉ thời điểm ở Prefix, ta có chủ ngữ 「私は」 (tôi). Tiếp sau là phó từ 「とうとう」 đặt trước để bổ nghĩa cho hành động kết quả. Trạng ngữ chỉ mục tiêu chuyển động 「約束の場所に」 (đến địa điểm đã hứa) đi trước bổ nghĩa cho động từ ghép, vốn được chia đôi thành gốc động từ 「たどり」 ở Chunk4 và động từ kết thúc ở quá khứ 「着いた」 ở Suffix để tạo thành động từ hoàn chỉnh 「たどり着いた」. Thứ tự đúng: Chunk1 -> Chunk2 -> Chunk3 -> Chunk4.": "Phó từ điểm huyệt thời gian 「とうとう」 (rốt cuộc thì, sau bao biến cố thì cuối cùng). Đánh dấu sự khép lại của chặng đường trầy trật 「私はとうとう約束の場所に」 (bản thân tôi trải qua bao sóng gió, rốt cục cũng lết được thân xác tới điểm hẹn). Kết thúc viên mãn bằng hành động 「たどり着いた」 (đã chạm chân đến đích)."
}

for i in range(26, 51):
    file = f'part_{i}.csv'
    path = os.path.join(dir_path, file)
    if not os.path.exists(path): continue
    
    with open(path, encoding='utf-8-sig') as f:
        r = list(csv.reader(f))
    
    headers = r[0]
    exp_idx = headers.index('Explanation') if 'Explanation' in headers else len(headers)-1
    
    changed = False
    for idx, row in enumerate(r):
        if idx == 0 or len(row) <= exp_idx: continue
        exp = row[exp_idx]
        
        for orig, new_val in rewrites.items():
            # some have exact match issues with quotes, let's just do a simpler search
            # we will just clean up the rewrites dict a bit to match safely.
            if orig in exp:
                exp = exp.replace(orig, new_val)
                row[exp_idx] = exp
                changed = True
            else:
                # try to match ignoring small differences
                # since we copied directly from the set5_batch2.txt, it should match.
                pass
                
    if changed:
        with open(path, 'w', encoding='utf-8-sig', newline='') as f:
            csv.writer(f).writerows(r)

print("Set 5 Batch 2 (parts 26-50) manually reviewed and rewritten successfully!")
